// SnapShift i18n — bilingual EN/ZH
(function () {
  const LANG = {
    en: {
      home: 'Home',
      templates: 'Templates',
      create: 'Create',
      prompts: 'Prompts',
      howItWorks: 'How It Works',
      faq: 'FAQ',
      freeBetaTag: '🎁 Free Beta',
      heroTitle: 'Transform any photo.',
      heroTitle2: 'AI templates.',
      heroDesc: 'Not just another filter. Turn portraits into movie posters, pets into oil paintings, city shots into anime \u2014 all in seconds.',
      tryFree: 'Try SnapShift Free',
      browseTemplates: 'Browse Templates',
      statsTemplates: '🎭 Templates',
      statsQuality: '🖼️ 1K & 2K Quality',
      statsInstant: '⚡ Instant Generation',
      promptInspire: 'Prompt inspiration',
      morePrompts: 'More prompts \u2192',
      aiTemplates: 'AI Templates',
      aiTemplatesDesc: 'Pick a template, upload your photo, and transform it instantly.',
      moreTemplates: 'More Templates \u2192',
      seeDifference: 'See the difference.',
      dragSlider: 'Drag the slider to compare before and after',
      readyCreate: 'Ready to create?',
      readyCreateDesc: 'Upload a photo, pick from 53 AI templates, and transform it instantly \u2014 all on one page.',
      startCreating: 'Start Creating \u2192',
      readyTransform: 'Ready to transform your photos?',
      readyTransformDesc: 'All templates, 1K & 2K quality, completely free in Beta.',
      howSection: 'How SnapShift Works',
      how1Title: 'Upload',
      how1Desc: 'Any photo \u2014 portrait, pet, landscape, or product.',
      how2Title: 'Pick a template',
      how2Desc: 'Dozens of creative, scene, and style templates to choose from.',
      how3Title: 'Generate & download',
      how3Desc: 'Get your transformed image in seconds. 1K or 2K quality.',
      faq1: 'Is SnapShift free?',
      faq1a: 'Yes \u2014 completely free during Beta. All templates, 1K & 2K included.',
      faq2: 'Do I need an account?',
      faq2a: 'No account required. Just upload a photo and start transforming.',
      faq3: 'How long does it take?',
      faq3a: 'Most generations take 10-30 seconds depending on resolution.',
      faq1: 'Is SnapShift free?',
      faq1a: 'Yes — during our Free Beta, all templates are completely free.',
      faq2: 'What photos can I use?',
      faq2a: 'Portraits, pets, landscapes, objects, products — almost anything. Clear images work best.',
      faq3: 'What is 2K quality?',
      faq3a: '2K doubles the output resolution for sharper, print-ready images. 1K is fine for social media.',
      faq5: 'Are my photos uploaded to a server?',
      faq5a: 'Photos are only used for generation and are not stored or shared.',
      faq4: 'Can I use the images commercially?',
      faq4a: 'Yes — for personal and commercial use, as long as you own the original photo.',
      faq6: 'Will pricing change?',
      faq6a: 'SnapShift is free during Beta. In the future, some premium features may have a small cost.',
      footerCopyright: '© 2026 SnapShift. All rights reserved.',
      createTitle: 'Create your transformation',
      createDesc: 'Upload a photo, pick a template, get the result in seconds.',
      uploadHere: 'Drop or click to upload',
      uploadHint: 'JPG / PNG, up to 5 photos',
      addMore: 'Click to add more photos',
      genNoPhoto: 'Generate without photo',
      aspectRatio: 'Aspect Ratio',
      resolution: 'Resolution',
      template: 'Template',
      freeMode: 'Free Mode',
      more: 'More +',
      advancedOptions: 'Advanced Options',
      customPrompt: 'Custom Prompt',
      promptInspireLink: 'Need inspiration? Try example prompts',
      customPromptPlaceholder: 'Add details to refine the template...',
      genBtn: 'Enter a prompt or select a template',
      featuredTransformations: 'Featured transformations',
      transforming: 'Transforming your image...',
      download: 'Download',
      share: 'Share',
      tryAgain: 'Try Again',
      tryAnother: 'Try Another',
      need2Photos: 'Upload subject + background photos',
      uploadSubjectBg: 'Upload subject (1st) + background (2nd)',
      needBgPhoto: 'Need background photo (2nd)',
      uploadSubjectOutfit: 'Upload subject + outfit reference',
      needOutfitPhoto: 'Need outfit photo (2nd)',
      backTop: '\u2191',
      before: 'Before',
      after: 'After',
      promptLibrary: 'Prompt Library',
      free: 'Free',
      shareTitle: 'Share SnapShift',
      shareDesc: 'Help us spread the word.',
      shareCreation: 'Share your creation',
      footerTagline: 'SnapShift \u2014 Free AI Photo Transformer',
      footerPrivacy: 'Privacy Policy',
      footerTerms: 'Terms of Use',
      footerContact: 'Contact',
      faqTitle: 'FAQ',
      allTemplates: 'All Templates',
      filterAll: 'All',
      allTemplatesCount: 'All Templates (53 styles)',
      allTemplatesSub: 'Every AI template we have. Click any to try it in the generator.',
      searchPlaceholder: 'Search templates...',
      mode: 'MODE',
      popular: 'POPULAR',
      isNew: 'NEW',
      cat3dToys: '3D & Toys',
      catAnime: 'Anime & Cartoon',
      catArt: 'Art & Painting',
      catComic: 'Comic & Line Art',
      catPhoto: 'Photo & Realistic',
      catDesign: 'Design & Product',
      catUtility: 'Utility',
      catOther: 'Other',
      catToy: 'Toy',
      catSciFi: 'Sci-Fi',
      catPortrait: 'Portrait',
      catAnimals: 'Animals',
      catFantasy: 'Fantasy',
      catAbstract: 'Abstract',
      catFood: 'Food',
      catNature: 'Nature',
      catUrban: 'Urban',
      catStillLife: 'Still Life',
      tplCyberpunk: 'Cyberpunk',
      tplMoviePoster: 'Movie Poster',
      tpl3DFigurine: '3D Figurine',
      tplAnime: 'Anime',
      tplOilPainting: 'Oil Painting',
      tplFunkoPop: 'Funko Pop',
      tplProductRender: 'Product Render',
      tplGhibli: 'Ghibli',
      tpl3DCartoon: '3D Cartoon',
      tplPixelArt: 'Pixel Art',
      tplVintage: 'Vintage',
      tplMagazineCover: 'Magazine Cover',
      tplFigurine: 'Figurine',
      tplAnimeFigure: 'Anime Figure',
      tplLegoMinifig: 'LEGO Minifig',
      tplLegoStyle: 'LEGO Style',
      tplActionFigure: 'Action Figure',
      tplChibi3D: 'Chibi 3D',
      tpl3DPolaroid: '3D Polaroid',
      tplPlushToy: 'Plush Toy',
      tplCrochetDoll: 'Crochet Doll',
      tplAcrylicKeychain: 'Acrylic Keychain',
      tplCosplay: 'Cosplay',
      tplPixar: 'Pixar',
      tplSnoopy: 'Peanuts / Snoopy',
      tplPowerpuffGirls: 'Powerpuff Girls',
      tplJapaneseIllust: 'Japanese Illustration',
      tplAnimalCrossing: 'Animal Crossing',
      tplGouache: 'Gouache',
      tplVanGogh: 'Van Gogh',
      tplMarkerSketch: 'Marker Sketch',
      tplPaletteSwap: 'Palette Swap',
      tplPaintingProcess: 'Painting Process',
      tplMangaFashion: 'Manga Fashion',
      tplMangaLineArt: 'Manga Line Art',
      tplYonkoma: '4-Panel Comic',
      tplLineArt: 'Line Art',
      tplVectorIllustration: 'Vector Illustration',
      tplHyperRealistic: 'Hyper-Realistic',
      tplHDEnhance: 'HD Enhance',
      tplPoseReference: 'Pose Reference',
      tplSubjectExtraction: 'Subject Extraction',
      tplCanDesign: 'Can Design',
      tplIndustrialDesign: 'Industrial Design',
      tpl3DScreenEffect: '3D Screen Effect',
      tplBgReplace: 'Background Replace',
      tplOil: 'Oil',
      tplWater: 'Water',
      tplTradingCard: 'Trading Card',
      tplAlbumCover: 'Album Cover',
      tplAnimeCity: 'Anime City',
      tplAnimeStreet: 'Anime Street',
      tplBWPortrait: 'B&W Portrait',
      tplBlindBox: 'Blind Box',
      tplManga: 'Manga',
      tplRetroPoster: 'Retro Poster',
      tplComic: 'Comic',
      tplSportsCard: 'Sports Card',
      tplPixelRPG: 'Pixel RPG',
      tplMagazine: 'Magazine',
      tplProduct: 'Product',
      tplPeko: 'Peko',
      tplFantasy: 'Fantasy',
      tplPixel: 'Pixel',
      tplWatercolor: 'Watercolor',
      tplChibi: 'Chibi',
      tplFelt: 'Felt',
      tplSportsCard: 'Sports Card',
      tplCartoon: 'Cartoon',
      tpl4PanelComic: '4-Panel Comic',
      tplEnamelPin: 'Enamel Pin',
      tplLuxuryWatch: 'Luxury Watch',
      tplArtOverlay: 'Art Overlay',
      tplDisney: 'Disney',
      tplIceQueen: 'Ice Queen',
      tplArchitectureModel: 'Architecture Model',
      tplCyberpunkDesc: 'Neon city lights, cybernetic future',
      tplMoviePosterDesc: 'Cinematic Hollywood blockbuster',
      tpl3DFigurineDesc: 'Glossy collectible toy figure',
      tplAnimeDesc: 'Vibrant Japanese anime style',
      tplOilPaintingDesc: 'Classical oil painting elegance',
      tplFunkoPopDesc: 'Vinyl Pop! collectible figure',
      tplProductRenderDesc: 'Premium product showcase',
      tplGhibliDesc: 'Studio Ghibli magical nature',
      tpl3DCartoonDesc: 'Pixar-style 3D animation',
      tplPixelArtDesc: 'Retro 16-bit pixel game art',
      cyberpunkDesc: 'Transform this photo into a cyberpunk scene. Rain-slicked neon city streets at night, holographic advertisements and glowing neon signs reflecting on wet pavement, volumetric fog and dramatic cinematic lighting. Preserve the original subject.',
      animeDesc: 'Convert this photo into high-quality anime art. Vibrant cel shading colors, clean line work. The face, features, hair color, and eye color follow the original subject. Soft beautiful lighting, hand-drawn animation look.',
      oilDesc: 'Reimagine this photo as a classical oil painting with thick impasto technique, heavy visible brushstrokes, palette knife texture, layered paint, thick pigment buildup, rich oil colors, renaissance fine art quality, dramatic chiaroscuro lighting, museum-worthy masterpiece with tangible paint texture and bold brush marks.',
      movieDesc: 'Transform this photo into a cinematic movie poster with dramatic Hollywood composition. Warm golden hour lighting, volumetric fog, deep depth of field, and realistic film grain texture. Preserve the original subject.',
      cartoonDesc: 'Transform this photo into a Pixar-style 3D cartoon. The face, features, and body follow the original subject. Smooth glossy shading, animated movie quality. Keep the original background.',
      plushDesc: 'Turn this photo into an adorable plush stuffed toy. Soft fuzzy fabric texture, stitched seam details. The face and features follow the original subject. Warm toy store photography.',
      crochetDesc: 'Turn this photo into a handmade crochet yarn doll. Visible knitted stitch texture, soft wool appearance. The face and features follow the original subject. Cozy handmade quality.',
      acrylicKeychain: 'Turn this photo into a cute acrylic keychain charm. Transparent printed plastic with metal keyring attached. The face and features follow the original subject. Glossy flat surface, trendy accessory mockup style.',
      enamelPin: 'Transform this subject into a collectible enamel pin badge, polished metal edges with vibrant colored enamel fill, shiny metallic finish, flat-lay product photography.',
      funkoPop: 'Turn this photo into a Funko Pop style collectible figure. The face, body shape, and key features follow the original subject. Glossy vinyl Funko Pop finish with large black circular eyes. Keep the original background and lighting.',
      legoStyle: 'Rebuild this scene entirely from LEGO bricks, blocky geometric construction, visible stud connections on every surface, realistic plastic brick texture, authentic brick-built look.',
      legoMinifig: 'Turn the subject in this photo into a LEGO minifigure. Keep the original background.',
      ghibliDesc: 'Transform this photo into Studio Ghibli animation style. Soft watercolor hand-painted backgrounds, warm nostalgic lighting with gentle rim light, and a dreamy pastel color palette. Preserve the original subject.',
      vintageDesc: 'Transform this photo into a vintage 1970s film photograph. Warm sepia tones, heavy visible film grain, and slightly faded desaturated colors. Preserve the original subject.',
      pixelDesc: 'Transform this photo into 16-bit retro pixel art. Visible pixel grid with crisp square pixels and clean hard edges, limited SNES-era color palette with dithered shading. Preserve the original subject composition and key features.',
      waterDesc: 'Convert this photo into a soft watercolor painting. Wet-on-wet technique with transparent pigment washes, visible cold-pressed paper texture, and gentle color bleeding at edges. Preserve the original subject.',
      magazineDesc: 'Turn this photo into a magazine cover layout with bold masthead typography overlay and cover-style composition, magazine title text overlay, professional print quality, clean composition.',
      promptsTitle: 'All Prompts',
      searchPrompts: 'Search prompts...',
      backToGenerator: '\u2190 Back to Generator',
      promptsCount: '400 prompts',
      templatesIntro: 'Browse 52 AI-powered photo templates — from cyberpunk city scenes and Studio Ghibli landscapes to 3D collectible figures, oil paintings, and cinematic movie posters. Pick a style, upload your photo, and get a stunning transformation in seconds. All templates are free during Beta and output in crisp 1K or 2K quality, perfect for social media posts, creative projects, or just having fun with AI art.',
      promptsIntro: 'Explore 400 carefully crafted AI image prompts across 8 categories — Portrait, Animals, Fantasy, Abstract, Food, Nature, Urban, and Still Life. Each prompt is a real copy-paste example you can use in SnapShift or any AI image generator. Click any card to preview the full prompt, copy it, or jump straight to the creator.',
      aboutTitle: 'About SnapShift',
      aboutSubtitle: 'Free AI photo transformation — no signup, no limits.',
      aboutWhatTitle: 'What We Do',
      aboutWhatDesc1: 'SnapShift uses artificial intelligence to transform your photos into stunning artwork, collectible figures, movie posters, anime scenes, oil paintings, and more — instantly, in your browser.',
      aboutWhatDesc2: 'Pick from 50+ AI templates, upload any photo, and get a high-quality transformation in seconds. Output in 1K or 2K resolution — perfect for social media, prints, or creative projects.',
      aboutWhyFree: 'Why Free?',
      aboutWhyFreeDesc: 'SnapShift is currently in public beta. Our goal is to make AI creative tools accessible to everyone — artists, content creators, small business owners, and anyone who wants to explore the possibilities of AI-powered image generation.',
      aboutTemplatesTitle: 'Our Templates',
      aboutTemplatesDesc: 'From cyberpunk neon cities and Studio Ghibli landscapes to 3D collectible figurines and cinematic movie posters — our AI template library covers a wide range of creative styles. Each template uses a carefully crafted prompt designed to produce consistent, high-quality results.',
      contactTitle: 'Contact Us',
      contactSubtitle: 'Got a question, suggestion, or business inquiry? We\'d love to hear from you.',
      contactEmail: 'Email',
      contactResponse: 'We typically respond within 24 hours.',
      contactFollow: 'Follow Us',
      contactFollowDesc: 'Stay updated on new templates, features, and AI art inspiration.',
      privacyTitle: 'Privacy Policy',
      termsTitle: 'Terms of Use',
      lastUpdated: 'Last updated:',
      privacyS1Title: '1. Information We Collect',
      privacyS1Desc: 'When you use SnapShift, you may upload photos for AI image generation. We do not require account creation or personal information to use the service.',
      privacyS2Title: '2. How We Use Your Photos',
      privacyS2Desc: 'Photos you upload are sent to our AI image generation provider (Agnes AI) to create the requested images. We do not store, sell, or share your uploaded photos. Generated images are returned to you and are not retained on our servers.',
      privacyS3Title: '3. Cookies and Analytics',
      privacyS3Desc: 'We may use basic analytics and cookies to understand website usage and improve our service. These do not identify you personally.',
      privacyS4Title: '4. Third-Party Services',
      privacyS4Desc: 'We use Cloudflare for website hosting and security, and Agnes AI for image generation. These services have their own privacy policies.',
      privacyS5Title: '5. Children\'s Privacy',
      privacyS5Desc: 'SnapShift is not intended for children under 13. We do not knowingly collect data from children.',
      privacyS6Title: '6. Changes to This Policy',
      privacyS6Desc: 'We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated date.',
      privacyS7Title: '7. Contact Us',
      privacyS7Desc: 'If you have questions about this Privacy Policy, contact us at hello@snapshit.fun.',
      termsS1Title: '1. Acceptance of Terms',
      termsS1Desc: 'By using SnapShift, you agree to these Terms of Use. If you do not agree, please do not use the service.',
      termsS2Title: '2. Use of the Service',
      termsS2Desc: 'SnapShift is an AI-powered image generation tool. You may upload photos and select styles to generate new images. You must only upload photos that you have the right to use, including photos of yourself or people who have given you permission.',
      termsS3Title: '3. Content Ownership and License',
      termsS3Desc: 'You retain ownership of the photos you upload. You are granted a license to use the AI-generated images for personal and commercial purposes, subject to applicable laws. We do not claim ownership of your uploaded photos or generated images.',
      termsS4Title: '4. Prohibited Uses',
      termsS4Desc: 'You may not use SnapShift to create content that is illegal, harmful, defamatory, discriminatory, sexually explicit, or that infringes on the rights of others. You may not use photos of individuals without their consent.',
      termsS5Title: '5. No Warranty',
      termsS5Desc: 'The service is provided "as is" without warranties of any kind. AI-generated results may vary and we do not guarantee specific outcomes.',
      termsS6Title: '6. Limitation of Liability',
      termsS6Desc: 'To the maximum extent permitted by law, SnapShift and its operators are not liable for any damages arising from your use of the service.',
      termsS7Title: '7. Changes to Terms',
      termsS7Desc: 'We may update these Terms of Use at any time. Continued use of the service after changes means you accept the updated terms.',
      termsS8Title: '8. Contact',
      termsS8Desc: 'For questions about these terms, contact us at hello@snapshit.fun.',
      morePrompt: 'More +',
      examplePrompts: 'Example Prompts',
      usePrompt: 'Use this prompt',
      copyPrompt: 'Copy prompt',
      copied: 'Copied!',
      copyFailed: 'Copy failed',
    },
    zh: {
      home: '首页',
      templates: '模板',
      create: '创作',
      prompts: '提示词',
      howItWorks: '使用教程',
      faq: '常见问题',
      freeBetaTag: '🎁 免费公测',
      heroTitle: '照片变艺术。',
      heroTitle2: 'AI 模板一键。',
      heroDesc: '不只是滤镜。把你的头像变成电影海报，把宠物变成油画，把城市街拍变成动漫——几秒钟搞定。',
      tryFree: '免费试用 SnapShift',
      browseTemplates: '浏览模板',
      statsTemplates: '🎭 模板',
      statsQuality: '🖼️ 1K 和 2K 画质',
      statsInstant: '⚡ 即时生成',
      promptInspire: '提示词灵感',
      morePrompts: '更多提示词 →',
      aiTemplates: 'AI 模板',
      aiTemplatesDesc: '选一个模板，上传你的照片，立刻转换。',
      moreTemplates: '更多模板 →',
      seeDifference: '看看效果。',
      dragSlider: '拖动滑块对比前后效果',
      readyCreate: '准备好了吗？',
      readyCreateDesc: '上传照片，选 AI 模板，一键转换——全在一页搞定。',
      startCreating: '开始创作 →',
      readyTransform: '准备转换你的照片吗？',
      readyTransformDesc: '所有模板、1K 和 2K 画质，公测期间完全免费。',
      howSection: '如何使用 SnapShift',
      how1Title: '上传',
      how1Desc: '任何照片——人像、宠物、风景或产品。',
      how2Title: '选模板',
      how2Desc: '数十种创意、场景和风格模板任你选择。',
      how3Title: '生成下载',
      how3Desc: '几秒钟获得转换后的图像。1K 或 2K 画质。',
      faq1: 'SnapShift 免费吗？',
      faq1a: '是的——公测期间完全免费，所有模板免费使用。',
      faq2: '可以用什么照片？',
      faq2a: '人像、宠物、风景、物品、产品——几乎什么都可以。清晰的照片效果最好。',
      faq3: '什么是 2K 画质？',
      faq3a: '2K 可将输出分辨率提高一倍，获得更清晰、可打印的图像。1K 适合社交媒体。',
      faq5: '照片会上传到服务器吗？',
      faq5a: '照片仅用于生成，不会被存储或分享。',
      faq4: '能用生成的图片商用吗？',
      faq4a: '可以——个人和商业用途均可，前提是你拥有原始照片。',
      faq6: '价格会变吗？',
      faq6a: 'SnapShift 公测期间免费。将来部分高级功能可能会有少量费用。',
      footerCopyright: '© 2026 SnapShift. 保留所有权利。',
      createTitle: '开始创作',
      createDesc: '上传照片，选模板，几秒出结果。',
      uploadHere: '拖拽或点击上传',
      uploadHint: 'JPG / PNG，最多 5 张',
      addMore: '点击添加更多照片',
      genNoPhoto: '无需照片生成',
      aspectRatio: '画面比例',
      resolution: '分辨率',
      template: '模板',
      freeMode: '自由模式',
      more: '更多 +',
      advancedOptions: '高级选项',
      customPrompt: '自定义提示词',
      promptInspireLink: '需要灵感？试试示例提示词',
      customPromptPlaceholder: '添加细节优化模板效果...',
      genBtn: '输入提示词或选择一个模板',
      featuredTransformations: '精选效果展示',
      transforming: '正在转换你的图像...',
      download: '下载',
      share: '分享',
      tryAgain: '再试一次',
      tryAnother: '再来一张',
      need2Photos: '请上传主体和背景两张照片',
      uploadSubjectBg: '上传主体（第1张）+ 背景（第2张）',
      needBgPhoto: '还需要背景照片（第2张）',
      uploadSubjectOutfit: '上传主体 + 服装参考',
      needOutfitPhoto: '还需要服装照片（第2张）',
      backTop: '\u2191',
      before: '转换前',
      after: '转换后',
      promptLibrary: '提示词库',
      free: '免费',
      shareTitle: '分享 SnapShift',
      shareDesc: '帮我们传播出去。',
      shareCreation: '分享你的作品',
      footerTagline: 'SnapShift — 免费 AI 照片转换器',
      footerPrivacy: '隐私政策',
      footerTerms: '使用条款',
      footerContact: '联系我们',
      faqTitle: '常见问题',
      allTemplates: '全部模板',
      filterAll: '全部',
      allTemplatesCount: '全部模板（53种风格）',
      allTemplatesSub: '我们所有的 AI 模板。点击任意一个在生成器中试用。',
      searchPlaceholder: '搜索模板...',
      mode: '模式',
      popular: '热门',
      isNew: '新品',
      cat3dToys: '3D & 玩具',
      catAnime: '动漫 & 卡通',
      catArt: '艺术 & 油画',
      catComic: '漫画 & 线稿',
      catPhoto: '照片 & 写实',
      catDesign: '设计 & 产品',
      catUtility: '实用工具',
      catOther: '其他',
      catToy: '玩具',
      catSciFi: '科幻',
      catPortrait: '人像',
      catAnimals: '动物',
      catFantasy: '奇幻',
      catAbstract: '抽象',
      catFood: '美食',
      catNature: '自然',
      catUrban: '都市',
      catStillLife: '静物',
      tplCyberpunk: '赛博朋克',
      tplMoviePoster: '电影海报',
      tpl3DFigurine: '3D 公仔',
      tplAnime: '动漫',
      tplOilPainting: '油画',
      tplFunkoPop: 'Funko Pop',
      tplProductRender: '产品渲染',
      tplGhibli: '吉卜力',
      tpl3DCartoon: '3D 卡通',
      tplPixelArt: '像素艺术',
      tplVintage: '复古',
      tplMagazineCover: '杂志封面',
      tplFigurine: '公仔',
      tplAnimeFigure: '动漫手办',
      tplLegoMinifig: '乐高人仔',
      tplLegoStyle: '乐高风格',
      tplActionFigure: '可动人偶',
      tplChibi3D: 'Q版3D',
      tpl3DPolaroid: '3D 拍立得',
      tplPlushToy: '毛绒玩具',
      tplCrochetDoll: '钩针娃娃',
      tplAcrylicKeychain: '亚克力钥匙扣',
      tplCosplay: '角色扮演',
      tplPixar: '皮克斯',
      tplSnoopy: '史努比',
      tplPowerpuffGirls: '飞天小女警',
      tplJapaneseIllust: '日系插画',
      tplAnimalCrossing: '动物森友会',
      tplGouache: '水粉',
      tplVanGogh: '梵高',
      tplMarkerSketch: '马克笔',
      tplPaletteSwap: '配色替换',
      tplPaintingProcess: '绘画过程',
      tplMangaFashion: '漫画时装',
      tplMangaLineArt: '漫画线稿',
      tplYonkoma: '四格漫画',
      tplLineArt: '线稿',
      tplVectorIllustration: '矢量插画',
      tplHyperRealistic: '超写实',
      tplHDEnhance: '高清增强',
      tplPoseReference: '姿势参考',
      tplSubjectExtraction: '主体提取',
      tplCanDesign: '易拉罐设计',
      tplIndustrialDesign: '工业设计',
      tpl3DScreenEffect: '3D 屏幕效果',
      tplBgReplace: '背景替换',
      tplOil: '油画',
      tplWater: '水彩',
      tplTradingCard: '球星卡',
      tplAlbumCover: '专辑封面',
      tplAnimeCity: '动漫城市',
      tplAnimeStreet: '动漫街景',
      tplBWPortrait: '黑白人像',
      tplBlindBox: '盲盒',
      tplManga: '漫画',
      tplRetroPoster: '复古海报',
      tplComic: '漫画',
      tplSportsCard: '运动卡',
      tplPixelRPG: '像素 RPG',
      tplMagazine: '杂志',
      tplProduct: '产品',
      tplPeko: 'Peko',
      tplFantasy: '奇幻',
      tplPixel: '像素',
      tplWatercolor: '水彩画',
      tplChibi: 'Q版',
      tplFelt: '毛毡',
      tplSportsCard: '球星卡',
      tplCartoon: '卡通',
      tpl4PanelComic: '四格漫画',
      tplEnamelPin: '珐琅胸针',
      tplLuxuryWatch: '奢侈名表',
      tplArtOverlay: '艺术叠加',
      tplDisney: '迪士尼',
      tplIceQueen: '冰雪女王',
      tplArchitectureModel: '建筑模型',
      tplCyberpunkDesc: '霓虹城市，赛博朋克未来',
      tplMoviePosterDesc: '好莱坞大片质感',
      tpl3DFigurineDesc: '光泽可收藏公仔',
      tplAnimeDesc: '鲜艳日本动漫风',
      tplOilPaintingDesc: '古典油画优雅',
      tplFunkoPopDesc: 'Vinyl Pop! 公仔',
      tplProductRenderDesc: '高级产品展示',
      tplGhibliDesc: '吉卜力魔法自然',
      tpl3DCartoonDesc: '皮克斯风3D动画',
      tplPixelArtDesc: '16位像素复古游戏',
      cyberpunkDesc: '将这张照片转换为赛博朋克场景。雨夜的霓虹街道，全息广告和发光招牌倒映在湿漉漉的路面上，体积雾和戏剧性的电影灯光。保留原始主体。',
      animeDesc: '将这张照片转换为高品质动漫艺术。鲜艳的赛璐珞着色，干净的线条。面部、特征、发色和眼睛颜色遵循原始主体。柔和美丽的光线，手绘动画质感。',
      oilDesc: '将这张照片重塑为一幅古典油画，厚重的厚涂技法，明显的可见笔触，调色刀纹理，层次感颜料，丰富的油画色彩，文艺复兴美术品质，戏剧性明暗对比灯光，具有可触摸的颜料质感和大胆笔触的博物馆级杰作。',
      movieDesc: '将这张照片转换为电影海报，具有戏剧性的好莱坞构图。温暖的金色时刻灯光，体积雾，深景深和真实的胶片颗粒纹理。保留原始主体。',
      cartoonDesc: '将这张照片转换为皮克斯风格的3D卡通。面部、特征和身体遵循原始主体。光滑的光泽阴影，动画电影画质。保持原始背景。',
      plushDesc: '将这张照片变成一个可爱的毛绒玩具。柔软的绒毛织物纹理，缝合线细节。面部和特征遵循原始主体。温暖的玩具店摄影风格。',
      crochetDesc: '将这张照片变成一个手工钩针编织的纱线娃娃。可见的针织针脚纹理，柔软的羊毛外观。面部和特征遵循原始主体。舒适的手工质感。',
      acrylicKeychain: '将这张照片变成一个可爱的亚克力钥匙扣挂饰。透明印刷塑料，附带金属钥匙环。面部和特征遵循原始主体。光泽平面，潮流配饰模型风格。',
      enamelPin: '将主体转换为收藏级珐琅胸针徽章，抛光金属边缘搭配鲜艳的彩色珐琅填充，闪亮的金属光泽，平铺产品摄影。',
      funkoPop: '将这张照片转换为 Funko Pop 风格的收藏人偶。面部、体型和关键特征遵循原始主体。光泽乙烯基 Funko Pop 质感，大大的黑色圆形眼睛。保持原始背景和灯光。',
      legoStyle: '用乐高积木重建整个场景，块状几何结构，每个表面都可见凸起连接点，逼真的塑料积木纹理，真实的积木搭建效果。',
      legoMinifig: '将这张照片中的主体变成乐高人仔。保持原始背景。',
      ghibliDesc: '将这张照片转换为吉卜力动画风格。柔和的水彩手绘背景，温暖的怀旧光线搭配柔和的边缘光，梦幻般的粉彩色调。保留原始主体。',
      vintageDesc: '将这张照片转换为1970年代复古胶片照片风格。温暖的棕褐色调，明显的可见胶片颗粒，略显褪色的低饱和度色彩。保留原始主体。',
      pixelDesc: '将这张照片转换为16位复古像素艺术。可见的像素网格，清晰的方形像素和干净的硬边缘，有限的SFC时代调色板搭配抖动阴影。保留原始主体构图和关键特征。',
      waterDesc: '将这张照片转换为柔和的水彩画。湿画法技法，透明的颜料渲染，可见的冷压纸纹理，边缘处柔和的色彩渗透。保留原始主体。',
      magazineDesc: '将这张照片变成杂志封面布局，粗体刊头字体叠加和封面式构图，杂志标题文字叠加，专业印刷品质，简洁的构图。',
      promptsTitle: '全部提示词',
      searchPrompts: '搜索提示词...',
      backToGenerator: '\u2190 返回生成器',
      promptsCount: '400条提示词',
      templatesIntro: '浏览52款AI照片模板——赛博朋克城市风光、吉卜力自然风景，到3D收藏公仔、油画和电影海报。选风格，上传照片，几秒钟获得惊艳效果。全部模板公测期间免费，输出清晰1K或2K画质，适合社交媒体、创意项目，或者纯粹享受AI艺术的乐趣。',
      promptsIntro: '探索400条精心设计的AI图片提示词，涵盖8大分类——人像、动物、奇幻、抽象、美食、自然、都市和静物。每条都是可直接复制使用的真实范例，可用于SnapShift或任何AI图像生成器。点击任意卡片预览完整提示词，一键复制，或直接跳转到创作页。',
      aboutTitle: '关于SnapShift',
      aboutSubtitle: '免费AI照片转换——无需注册，无限制。',
      aboutWhatTitle: '我们做什么',
      aboutWhatDesc1: 'SnapShift利用人工智能将你的照片变成惊艳的艺术作品、收藏公仔、电影海报、动漫场景、油画等——即时在浏览器中完成。',
      aboutWhatDesc2: '从50多款AI模板中选择，上传任意照片，几秒钟获得高质量转换效果。支持1K或2K分辨率输出——完美适用于社交媒体、打印或创意项目。',
      aboutWhyFree: '为什么免费？',
      aboutWhyFreeDesc: 'SnapShift目前处于公开测试阶段。我们的目标是让AI创意工具惠及所有人——艺术家、内容创作者、小企业主，以及任何想探索AI图像生成可能性的人。',
      aboutTemplatesTitle: '我们的模板',
      aboutTemplatesDesc: '从赛博朋克霓虹城市和吉卜力工作室的自然风光，到3D收藏公仔和电影海报——我们的AI模板库涵盖各种创意风格。每款模板都使用精心设计的提示词，确保输出一致的高质量效果。',
      contactTitle: '联系我们',
      contactSubtitle: '有问题、建议或商务合作？我们期待收到你的消息。',
      contactEmail: '邮箱',
      contactResponse: '我们通常在24小时内回复。',
      contactFollow: '关注我们',
      contactFollowDesc: '获取最新模板、功能和AI艺术灵感更新。',
      privacyTitle: '隐私政策',
      termsTitle: '使用条款',
      lastUpdated: '最后更新：',
      privacyS1Title: '1. 我们收集的信息',
      privacyS1Desc: '使用SnapShift时，你可能会上传照片用于AI图像生成。我们不要求创建账号或提供个人信息即可使用本服务。',
      privacyS2Title: '2. 我们如何使用你的照片',
      privacyS2Desc: '你上传的照片会发送给我们的AI图像生成服务商（Agnes AI）来创建所需的图像。我们不存储、不出售、不分享你上传的照片。生成的图像会返回给你，且不会保留在我们的服务器上。',
      privacyS3Title: '3. Cookie和分析',
      privacyS3Desc: '我们可能使用基础分析和Cookie来了解网站使用情况并改进服务。这些不会识别你的个人身份。',
      privacyS4Title: '4. 第三方服务',
      privacyS4Desc: '我们使用Cloudflare提供网站托管和安全服务，使用Agnes AI进行图像生成。这些服务各自有其隐私政策。',
      privacyS5Title: '5. 儿童隐私',
      privacyS5Desc: 'SnapShift不面向13岁以下的儿童。我们不会故意收集儿童的数据。',
      privacyS6Title: '6. 本政策的变更',
      privacyS6Desc: '我们可能会不时更新本隐私政策。变更内容将发布在本页面，并附上更新日期。',
      privacyS7Title: '7. 联系我们',
      privacyS7Desc: '如果你对本隐私政策有疑问，请通过 hello@snapshit.fun 联系我们。',
      termsS1Title: '1. 条款接受',
      termsS1Desc: '使用SnapShift即表示你同意本使用条款。如果你不同意，请勿使用本服务。',
      termsS2Title: '2. 服务使用',
      termsS2Desc: 'SnapShift是一个AI驱动的图像生成工具。你可以上传照片并选择风格来生成新图像。你只能上传你有权使用的照片，包括你本人或已获得他人许可的照片。',
      termsS3Title: '3. 内容所有权和许可',
      termsS3Desc: '你保留对上传照片的所有权。你获得使用AI生成图像的个人和商业用途许可，受适用法律约束。我们不主张对你上传的照片或生成图像的所有权。',
      termsS4Title: '4. 禁止使用',
      termsS4Desc: '你不得使用SnapShift创建非法、有害、诽谤、歧视、色情或侵犯他人权利的内容。未经同意，你不得使用他人肖像。',
      termsS5Title: '5. 无担保',
      termsS5Desc: '本服务按"原样"提供，不附带任何形式的担保。AI生成的结果可能有所不同，我们不保证特定结果。',
      termsS6Title: '6. 责任限制',
      termsS6Desc: '在法律允许的最大范围内，SnapShift及其运营方不对你使用本服务产生的任何损害承担责任。',
      termsS7Title: '7. 条款变更',
      termsS7Desc: '我们可能随时更新本使用条款。变更后继续使用本服务即表示你接受更新后的条款。',
      termsS8Title: '8. 联系我们',
      termsS8Desc: '如对这些条款有疑问，请通过 hello@snapshit.fun 联系我们。',
      morePrompt: '更多 +',
      examplePrompts: '示例提示词',
      usePrompt: '使用此提示词',
      copyPrompt: '复制提示词',
      copied: '已复制！',
      copyFailed: '复制失败',
    }
  };


  // Auto-detect language
  const saved = localStorage.getItem('snapshift-lang');
  const browserLang = (navigator.language || '').startsWith('zh') ? 'zh' : 'en';
  let currentLang = saved || browserLang;

  function setLang(lang) {
    currentLang = lang;
    localStorage.setItem('snapshift-lang', lang);
    applyLang(lang);
    // Update toggle buttons
    document.querySelectorAll('.lang-btn').forEach(b => {
      b.classList.toggle('active', b.dataset.lang === lang);
    });
    // Notify listeners (e.g., strip + showcase re-render)
    window.dispatchEvent(new CustomEvent('langchange', { detail: { lang } }));
  }

  function applyLang(lang) {
    const strings = LANG[lang] || LANG.en;
    // Apply to all elements with data-l10n
    document.querySelectorAll('[data-l10n]').forEach(el => {
      const key = el.dataset.l10n;
      if (strings[key] !== undefined) {
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
          el.placeholder = strings[key];
        } else {
          el.textContent = strings[key];
        }
      }
    });
    // Update button text for generate button
    document.querySelectorAll('[data-l10n-if]').forEach(el => {
      const expr = el.dataset.l10nIf;
      const [key, val] = expr.split('=');
      if (val && el.dataset[key] !== val) return;
      const k = el.dataset.l10n || '';
      if (strings[k] !== undefined) el.textContent = strings[k];
    });
    document.documentElement.lang = lang;
  }

  // Auto-init after DOM loads
  document.addEventListener('DOMContentLoaded', () => {
    window.initLang();
  });

  // Build globe button + dropdown
  function buildLangToggle() {
    const html = `
      <button class="lang-globe" aria-label="Language" id="langGlobe">🌐</button>
      <div class="lang-dropdown" id="langDropdown">
        <button class="lang-option" data-lang="en">English</button>
        <button class="lang-option" data-lang="zh">中文</button>
      </div>
    `;
    document.querySelectorAll('.lang-toggle').forEach(t => {
      t.innerHTML = html;
    });
    // Toggle dropdown
    document.querySelectorAll('.lang-globe').forEach(btn => {
      btn.addEventListener('click', e => {
        e.stopPropagation();
        btn.parentElement.classList.toggle('open');
      });
    });
    // Click option
    document.querySelectorAll('.lang-option').forEach(opt => {
      opt.addEventListener('click', e => {
        e.stopPropagation();
        setLang(opt.dataset.lang);
        document.querySelectorAll('.lang-toggle').forEach(t => t.classList.remove('open'));
      });
    });
    // Close on outside click
    document.addEventListener('click', () => {
      document.querySelectorAll('.lang-toggle').forEach(t => t.classList.remove('open'));
    });
  }

  // Expose globally
  window.setLang = setLang;
  window.getLang = () => currentLang;
  window.t = (key) => {
    const lang = currentLang;
    const strings = LANG[lang] || LANG.en;
    return strings[key] !== undefined ? strings[key] : key;
  };
  window.initLang = () => {
    buildLangToggle();
    applyLang(currentLang);
  };

})();
