window.promptZh = {
  "Portrait/001-corporate.png": "30多岁自信商务女性的专业头像，藏蓝色西装外套，真诚微笑，白色背景，影棚灯光，佳能85mm f/1.4拍摄，锐利对焦，8K画质",
  "Urban/001-cyberpunk.png": "未来赛博朋克夜景城市，日文霓虹灯牌，雨水浸湿的街道反射灯光，飞行汽车，撑伞的行人，银翼杀手风格，电影感，8K画质",
  "Still Life/001-luxury.png": "瑞士奢华腕表特写，抛光精钢表壳，蓝色表盘，黑色皮质表带，戏剧性影棚灯光带反射，产品摄影，商业品质，高端质感，8K画质",
  "Fantasy/001-ghibli.png": "吉卜力动画风格的田园乡村，起伏的绿色山丘点缀着野花，小石屋烟囱升起炊烟，手绘质感，温暖的午后光线",
  "Nature/001-landscape.png": "日出时的雪山山脉，橙粉色云彩，高山草甸野花盛开，湖面倒影，广角风景，国家地理级品质，8K画质",
  "Still Life/002-food.png": "美食汉堡，层次分明的食材，芝麻面包，生菜，番茄，融化的车达芝士，多汁牛肉饼，专业美食摄影，令人垂涎，戏剧性灯光，菜单级品质，8K画质",
  "Fantasy/002-dragon.png": "山峰上的威严巨龙，彩虹色鳞片，双翼展开，山谷中的中世纪城堡，暴风云，史诗奇幻艺术，高度细节，概念艺术，戏剧性灯光，8K画质",
  "Nature/002-forest.png": "晨雾中的古老森林，阳光穿过树冠形成丁达尔光效，苔藓覆盖的地面，蕨类植物，魔法氛围，奇幻风景，电影感，细节丰富，8K画质",
  "Fantasy/009-cyberanime.png": "动漫风格年轻女性肖像，霓虹粉色双马尾，面罩反射霓虹城市景观，带LED灯条的赛博朋克夹克，戏剧性霓虹灯光，MAPPA工作室品质",
  "Portrait/002-1970s.png": "70年代胶片摄影肖像，二十多岁的女性，法拉·福西特时代的羽毛层次发型，碎花裹身裙，柔和温暖逆光，重度胶片颗粒，柯达Ektar胶片模拟",
  "Fantasy/003-castle.png": "云海上方巨大漂浮城堡的电影概念艺术，瀑布从边缘倾泻入虚空，哥特式尖塔上温暖的发光窗户，带闪电的暴风云，史诗奇幻",
  "Abstract/001-vhs.png": "VHS故障美学肖像，蓬松80年代发型和浓妆的模特，横向扫描线失真，色彩通道溢出，白色时间戳叠加，重度数字噪点和静电纹理",
  "Fantasy/004-atlantis.png": "水下古城废墟，珊瑚覆盖的建筑，热带鱼穿梭于柱间，阳光穿透蓝色海水，失落的亚特兰蒂斯美学，奇幻场景，氛围感，高度细节，8K画质",
  "Abstract/002-abstract.png": "抽象流体艺术，旋转的大理石纹理，海军蓝、金色和白色，有机流动图案，奢华美学，数字艺术，高分辨率，迷幻感，优雅，8K画质",
  "Portrait/003-documentary.png": "60多岁饱经风霜渔夫的特写肖像，灰白胡须，深蓝色眼睛，黄色雨衣，海洋背景，阴天光线，纪实风格，照片级真实，高度细节，8K画质",
  "Fantasy/005-alien.png": "科幻概念艺术，外星卫星表面，两颗太阳在地平线落下投下双重阴影，前景生物发光的紫色植物，画面中央穿舱外宇航服的宇航员剪影，电影感超广角，詹姆斯·卡梅隆级视觉效果概念艺术",
  "Abstract/003-photorealistic-miniature-construction-on-giant-kfc-french-fr.png": "超现实超写实场景，微型建筑工人用小工具和梯子雕刻一个巨大的肯德基脆皮鸡腿。鸡腿放在印有公司logo的品牌盒子上。温暖影棚灯光，俏皮富有想象力的氛围。",
  "Abstract/018-miniature-construction-on-air-jordan-1-sneaker-art-diorama.png": "超写实电影感商业微距摄影。Air Jordan 1化身为神圣的建筑丰碑。一只巨大的Air Jordan 1球鞋如摩天大楼般垂直耸立。",
  "Abstract/021-playful-banana-google-logo-search-page-design.png": "Google主页截图，带香蕉版Google涂鸦，将手气不错按钮改为Go bananas。不要猴子。",
  "Abstract/022-vintage-digital-camera-portrait-y2k-aesthetic-nostalgia.png": "俯拍特写，一台黑色2000年代初期紧凑型数码相机放在有纹理的蓝色牛仔布上。背面LCD屏幕亮起，显示一位年轻女性的低保真、颗粒感、闪光灯自拍。屏幕中的人物有深色波浪卷发，浓重的Y2K风格粉色腮红涂在脸颊和鼻头，翼形眼线，亮泽嘴唇，回眸柔光凝视。相机机身可见按键和方向键。浅景深，对焦在LCD屏幕上，边缘略微模糊。",
  "Abstract/024-candid-90s-party-photo-young-man-laughing-red-eye.png": "1998年一次性相机拍摄的闪光灯快照。混乱家庭派对中的一个男人。红眼效果，硬阴影，运动模糊和胶片颗粒。构图略微倾斜且凌乱。",
  "Abstract/004-extreme-close-up-broken-pencil-graphite-wood-texture.png": "想象通过显微镜看到的铅笔尖。想象铅笔尖的样子并创作一张图像。",
  "Abstract/005-geometric-abstract-composition.png": "极简几何抽象艺术，交叉的圆形三角形正方形，柔和色彩，干净线条，留白空间，现代画廊美学，数字艺术，8K画质",
  "Abstract/006-fluid-marble-ink-swirl.png": "水中流动的大理石墨水旋涡，金色与深蓝色，液体艺术微距摄影，有机流动图案，高对比度，艺术抽象，8K画质",
  "Abstract/007-minimalist-gradient-wave.png": "极简渐变波浪设计，流畅曲线，日落色系从粉色到深紫色，光滑洁净表面，3D渲染，现代抽象艺术，宁静感",
  "Abstract/008-fractal-crystal-growth.png": "分形晶体生长微距摄影，几何图案，冰蓝与银色，锐利边缘与光滑平面，微观细节，科学抽象艺术，8K画质",
  "Abstract/009-neon-light-tube-sculpture.png": "抽象霓虹灯管雕塑，弯曲玻璃管发出粉、青、蓝光，深色影棚背景，抛光地板上的反射，现代艺术装置",
  "Abstract/010-color-explosion-powder-art.png": "彩色粉末爆炸定格瞬间，彩虹色颜料，高速摄影，黑色背景，灵感来自洒红节，鲜艳抽象，动感十足",
  "Abstract/011-origami-paper-landscape.png": "抽象折纸风景，折叠的几何山脉与山谷，柔和色纸质纹理，柔软阴影，极简构图，微距细节，艺术纸工艺",
  "Abstract/012-liquid-metal-reflection.png": "液态水银铬球体，完美反射彩色影棚灯光，光滑金属表面，微距细节，未来感抽象，产品摄影风格，8K画质",
  "Abstract/013-kaleidoscope-mandala.png": "精致万花筒曼陀罗，完美对称，宝石色调翡翠绿蓝宝石紫水晶，几何精度，催眠图案，数字冥想艺术，灵性抽象",
  "Fantasy/006-bugdroid-internal-scan-sci-fi-thermal-x-ray-robot-art.png": "Google Android机器人，高对比度科学影棚渲染，纯黑虚空背景。紧凑的右侧轮廓，采用假色热成像X射线美学，透明外壳下清晰展示电池、驱动器和传感器的内部结构，使用鲜艳热力图渐变。颜色从深冷蓝过渡到强烈的黄色和红色高光，营造未来感临床外观，正交透视，柔和霓虹般辉光。",
  "Fantasy/035-romantic-comedy-poster-how-to-lose-a-guy-in-10-days.png": "干净的2000年代初期浪漫喜剧海报合成。两个成年人背靠背站立，姿态俏皮自信，都侧目看向对方带着愉悦表情。左侧女性双臂交叉，优雅姿态。右侧男性双手插兜，放松倾斜。全身可见，留有充足标题空间。女性：无袖抹胸缎面金黄色落地长裙，光泽顺滑，简约珠宝。男性：深炭色或黑色定制西装，白衬衫，无领带或低调领带。",
  "Fantasy/007-cinematic-desert-walk-solitary-figure-in-orange-haze.png": "一个穿长外套的孤独身影在浓密的橙红色雾中穿过荒芜大地。",
  "Fantasy/010-elven-forest-kingdom.png": "古老森林中隐藏的精灵王国，发光水晶建筑，瀑布穿过树冠倾泻，魔法漂浮光点，空灵氛围，奇幻概念艺术",
  "Fantasy/011-necromancer-dark-tower.png": "嶙峋山顶的黑暗巫师塔，紫色闪电劈下，骸骨巨龙盘旋上空，山谷中亡灵大军，哥特奇幻艺术，阴郁氛围",
  "Fantasy/012-steampunk-airship-battle.png": "巨型蒸汽朋克飞艇舰队空中交战，黄铜与铜质船体，螺旋桨引擎，炮火，戏剧性日落云层，维多利亚科幻美学，史诗规模",
  "Fantasy/013-underwater-atlantis-ruins.png": "深海水下古亚特兰蒂斯废墟，珊瑚覆盖的巨型大理石雕像，生物发光水母，阳光穿透水面，神秘氛围，概念艺术",
  "Fantasy/014-floating-castle-islands.png": "漂浮岛上的奇幻城堡，瀑布倾泻入下方云海，龙在岛屿间飞翔，多月亮的戏剧性天空，史诗奇幻风景",
  "Fantasy/040-ice-queen-frozen-throne.png": "冰晶王座上的冰雪女王，半透明冰冠，霜冻魔法环绕指尖，北极宫殿内部，冷蓝色环境光，奇幻角色艺术",
  "Fantasy/015-dwarf-forge-underground.png": "地下深处的矮人铁匠铺，熔岩河流，巨大铁砧，发光武器，精致石头建筑，温暖橙色火光，奇幻环境艺术",
  "Fantasy/016-forest-spirit-deer.png": "威严森林精灵鹿，鹿角由发光树枝组成，月光空地，萤火虫飞舞，魔法古老森林，吉卜力工作室风格，柔和灯光",
  "Fantasy/044-warrior-vs-giant-monster.png": "孤身战士面对巨型暗影怪物，高举发光剑刃，废墟神庙战场，戏剧性闪电，史诗奇幻动作场景，电影感，高对比度",
  "Fantasy/041-cyberpunk-samurai-duel.png": "霓虹小巷中的赛博朋克武士，发光刀刃的武士刀，下雨，全息樱花，未来装甲与传统元素混搭，电影感动作",
  "Fantasy/017-phoenix-rising-from-ashes.png": "从火山灰中升起的凤凰，活火焰双翼，下方熔岩，戏剧性红橙色灯光，神话生物艺术，重生象征，8K画质",
  "Fantasy/018-pirate-ghost-ship-storm.png": "超自然风暴中航行的幽灵海盗船，发光绿色船帆，骷髅船员，巨型疯狗浪，黑暗奇幻氛围，月光",
  "Fantasy/048-angel-vs-demon-battle.png": "天使军团与恶魔大军的空中大战，金色光芒对抗黑暗之火，末日天空，废墟大教堂，史诗奇幻艺术，戏剧性构图，8K画质",
  "Fantasy/049-mermaid-lagoon-discovery.png": "黄昏时隐藏的美人鱼泻湖，生物发光珊瑚，美人鱼坐在岩石上梳理彩虹色头发，满月倒影，被施魔法的氛围，奇幻插画",
  "Fantasy/019-time-traveler-steampunk-lab.png": "维多利亚蒸汽朋克时光旅行实验室，黄铜机械，发光传送门，发条装置，地图和图表，温暖煤气灯，精细环境艺术，儒勒·凡尔纳风格",
  "Fantasy/020-giant-robot-ancient-ruins.png": "沙漠废墟中半埋的巨型古代机甲，藤蔓和苔藓覆盖金属，考古学家在旁边渺小如蚁，神秘发光核心，科幻奇幻",
  "Fantasy/021-magical-library-infinite.png": "无限魔法图书馆，漂浮的书籍，永无止境的螺旋楼梯，发光水晶照明，长袍学者，温暖琥珀色氛围，埃舍尔遇上哈利波特",
  "Fantasy/022-werewolf-full-moon-forest.png": "满月下的狼人变身，撕裂的衣服，黑暗森林空地，银色月光，雾气升腾，恐怖奇幻艺术，戏剧性毛发细节，电影感",
  "Fantasy/054-alien-jungle-planet.png": "遥远系外行星上的外星丛林，生物发光植物，天空中有三个太阳，奇异生物，穿宇航服的探险者，科幻奇幻风景，8K概念艺术",
  "Fantasy/023-sky-whale-cloud-voyager.png": "巨型天空鲸鱼在海洋上空的云层中漂浮，生物发光纹路，太阳在身后落下，小鸟在旁飞翔，梦幻奇幻场景，柔和色彩",
  "Nature/056-miniature-man-resting-on-plant-seedling-photorealistic.png": "一个小人坐在高大的豆芽旁靠着休息。放松地坐在地上，在巨大的植物茎下歇息。土壤、石子、根系和幼苗的细致纹理",
  "Nature/003-alpine-village-majestic-snow-capped-mountains-landscape.png": "史诗奇幻写实，超清晰日光，电影级自然之美，极致原始与宁静。陡峭的翠绿色山间梯田，鲜亮苔藓草地散落粉色高山花，与老树和悬崖层叠。高地小木屋和寺庙建在石头地基上，手工木作，风化屋顶，聚集在岩架和台地上",
  "Nature/058-whimsical-cat-journey-sketch-to-photorealistic-forest.png": "温馨房间，墙壁看起来像巨大的纸质插画，扁平墨线和水彩渲染，但纸墙的一角被掀开，露出后面完整的3D森林。掀开的边缘像厚卡纸一样向外卷曲，在插画表面投下真实阴影。错觉效果：2D绘制物体投射逼真的3D阴影，而3D森林投射淡淡的墨水阴影，仿佛正在变成绘画。一只猫半进半出：前爪在3D森林苔藓中，后半身在2D素描形态中，无缝融合。柔和晨光",
  "Nature/004-photorealistic-cloud-world-map-art-on-blue-sky.png": "逼真的天空云朵照片，独特地呈现出世界各大洲的形状，云层中可见每个大洲清晰分明的轮廓。背景是明亮蓝天，散布几朵较小的普通云。阳光微妙地照亮云朵，突出其独特形状",
  "Nature/005-misty-mountain-valley-sunrise.png": "雾蒙蒙山谷上空的日出，温暖金色光线，体积雾，超写实风景摄影，前景岩石和草地细节丰富",
  "Nature/006-sunlit-forest-path.png": "茂密森林小径，高大树木间柔和阳光射线，地面落叶，逼真景深，高分辨率自然照片，4K级叶片细节",
  "Nature/007-rocky-coastline-waves.png": "岩石海岸线，巨浪拍打悬崖，阴沉天空，戏剧性海景，逼真灯光和水花，长曝光效果",
  "Nature/008-snowy-mountain-peak.png": "晴朗蓝天下被雪覆盖的山峰，清脆细节，远处山峰为背景，逼真高山摄影，锐利对比度",
  "Nature/009-tropical-beach-paradise.png": "热带海滩，碧绿松石色海水，白色沙滩上柔和波浪，棕榈树，温暖阳光，超写实旅行明信片场景，晴空和倒影",
  "Nature/010-forest-river-long-exposure.png": "森林河流，长曝光柔滑水面，苔藓岩石，柔和自然光，逼真风景照片，高细节植被",
  "Nature/011-desert-dunes-sunset.png": "日落时分的沙漠沙丘，长长阴影，温暖色调，沙子精细纹理细节，超写实沙漠场景，清晰渐变天空，4K画质",
  "Nature/012-mirror-lake-reflection.png": "平静湖面完美倒映山景，清晨薄雾，柔和日出天空，超锐利风景照片，宁静祥和，照片级真实水面",
  "Nature/013-jungle-waterfall.png": "茂密丛林瀑布，浓密绿色植被，空气中水雾，逼真灯光，电影级自然摄影，湿润岩石和苔藓纹理",
  "Nature/014-milky-way-night-sky.png": "乡村景观上方的夜空，明亮星辰和可见银河，树木剪影，长曝光写实，深蓝与紫色，无光污染",
  "Nature/015-golden-wheat-field.png": "高大金色麦田，低矮阳光掠过麦穗顶部，远处农舍，逼真镜头光晕，夏日乡村氛围，高细节",
  "Nature/016-northern-lights-aurora.png": "雪景上空的北极光，绿色和紫色极光丝带，冰冻湖面反射色彩，超写实夜空，清冽冬空气息",
  "Nature/017-wildflower-spring-meadow.png": "春季野花草甸，前景色彩缤纷的花朵，远处山脉，柔和午后光线，逼真景深，自然摄影",
  "Nature/018-dawn-foggy-lake-pier.png": "黎明雾湖，前景小木码头，柔和淡雅色彩，平静水面，极简构图，超写实自然拍摄，8K画质",
  "Nature/019-winter-forest-blue-hour.png": "雪覆盖树木的冬季森林，蓝调时刻光线，树干间淡淡雾气，雪中逼真脚印，高细节，寒冷但宁静",
  "Nature/020-turquoise-bay-cliffs.png": "松石色海湾上方的悬崖，船只停泊在岸边，明亮正午阳光，逼真水面焦散和阴影，地中海海岸，假日风格",
  "Nature/021-winding-river-aerial.png": "俯瞰蜿蜒河流，两侧拼布般田野，傍晚阳光，逼真航拍风景，清脆细节，4K照片",
  "Nature/022-rolling-hills-storm.png": "戏剧性暴风云下起伏的绿色山丘，草地上阳光斑块，逼真远处降雨，阴郁氛围，自然摄影",
  "Nature/023-rocky-canyon-river.png": "底部有河流的岩石峡谷，悬崖上温暖日落光线，逼真侵蚀纹理，航拍视角，自然纪录片风格",
  "Nature/024-countryside-road-golden-hour.png": "两侧树木排列的乡间道路，黄金时刻光线，柏油路上长长阴影，逼真镜头光晕，宁静乡村氛围，高分辨率风景",
  "Nature/025-cherry-blossom-spring-park.png": "公园小径两旁盛开的樱花树，粉色花瓣飘落，柔和春日阳光穿过枝叶，梦幻氛围，日本春天，8K画质",
  "Nature/026-autumn-forest-canopy.png": "秋季森林树冠航拍，鲜艳红橙黄色叶片，下方蜿蜒河流，黄金时刻阳光，令人惊叹的秋色，无人机摄影",
  "Nature/027-sahara-sand-dunes-dawn.png": "黎明时分的撒哈拉沙漠沙丘，金色光线照在涟漪状沙纹上，沙脊上孤独骆驼剪影，无尽地平线，国家地理风格，8K画质",
  "Nature/028-alpine-lake-crystal-clear.png": "瑞士阿尔卑斯山清澈高山湖，松石绿水色，湖床可见鹅卵石，雪峰倒影，岸边野花，原始自然",
  "Nature/029-bamboo-forest-kyoto.png": "京都高耸竹林，翠绿竹竿直指天空，柔和阳光过滤洒下，蜿蜒小径，宁静日本自然，禅意氛围",
  "Nature/030-iceland-glacier-ice-cave.png": "冰岛冰川冰洞内部，璀璨蓝色半透明冰壁，上方天然天窗，冰冻瀑布纹理，异世之美，探险摄影",
  "Nature/031-lavender-field-provence.png": "法国普罗旺斯无尽的薰衣草田，紫色花行延伸至地平线，孤零零的柏树，金色日落，梦幻田园风景，8K摄影",
  "Nature/032-thunderstorm-over-ocean.png": "开阔海面上的戏剧性雷暴，闪电劈击水面，阴暗翻涌云层，汹涌波浪，大自然力量场景，史诗级天气摄影",
  "Nature/033-coral-reef-underwater.png": "生机勃勃的珊瑚礁水下场景，色彩斑斓的热带鱼，清澈松石色海水，阳光从水面穿透，海洋生物多样性，水肺潜水摄影",
  "Nature/034-african-savannah-sunset.png": "日落时分的非洲大草原，金合欢树剪影，远处象群行走，金橙色天空，野生动物摄影，国家地理，8K画质",
  "Nature/035-mount-fuji-cherry-blossom.png": "前景樱花映衬的富士山，经典日本风景，平静湖面倒影，粉色花瓣，春日清晨，标志旅行摄影，葛饰北斋风格",
  "Nature/036-patagonia-mountain-range.png": "日出时的巴塔哥尼亚山脉，锯齿状雪峰，下方松石色冰川湖，戏剧性云层，极限风景摄影，荒野，8K画质",
  "Nature/037-rainbow-over-waterfall.png": "巨型瀑布，雾中形成彩虹，葱郁绿色热带悬崖，强大水流，黄金时刻光线产生棱镜效果，史诗级自然摄影",
  "Nature/038-mono-lake-tufa-towers.png": "日出时莫诺湖凝灰岩塔，外星般的石灰岩构造从平静水面升起，粉紫色天空倒影，超现实风景，艺术自然摄影",
  "Nature/039-santorini-sunset-aegean.png": "日落时的希腊圣托里尼，白色立方体建筑配蓝色圆顶俯瞰爱琴海，温暖金色光线，三角梅绽放，地中海天堂，8K画质",
  "Nature/040-yosemite-valley-autumn.png": "秋天的约塞米蒂谷，酋长岩和半穹顶，金色秋叶，默塞德河倒影，晨雾，安塞尔·亚当斯风格，壮丽风景摄影",
  "Nature/041-great-barrier-reef-aerial.png": "澳大利亚大堡礁航拍，松石色与翠绿色海水，从空中可见精致珊瑚图案，白色沙洲，自然奇观，无人机摄影",
  "Nature/042-new-zealand-milford-sound.png": "黎明时的新西兰米尔福德峡湾，米特峰从峡湾拔起，雾蒙蒙的瀑布，平静深水倒影，雨林覆盖的悬崖，指环王风景",
  "Nature/043-death-valley-star-trails.png": "夜晚的死谷，星轨在沙漠景观上方旋转，岩层剪影，鲜艳银河核心，长曝光天文摄影，8K画质",
  "Nature/044-hawaii-volcano-lava-flow.png": "基拉韦厄火山熔岩夜间入海，蒸汽爆炸，发光橙色熔岩对比黑暗海面，戏剧性自然现象，夏威夷自然摄影",
  "Portrait/004-woman-post-workout-hydration-fitness-gym-scene.png": "年轻女性坐在瑜伽垫上，用毛巾擦汗，手持水瓶。充满成就感，微微气喘，自信微笑。高马尾，因运动略显凌乱有碎发",
  "Portrait/101-cheerful-woman-selfie-in-miami-convertible-university-of-mia.png": "年轻美国女性在敞篷车中自拍，风吹过头发，一只手俏皮地触碰脸部微笑，后方可见迈阿密海滩海洋。明亮真诚露齿笑，无忧无虑快乐能量，俏皮活泼，因真诚笑声和阳光微微眯眼。阳光亲吻的金发，自然高光和层次感",
  "Portrait/102-elegant-women-formal-dresses-fireworks-night-event.png": "深色波浪长发年轻女性，穿着米色金色无袖亮片礼服，对镜头温柔微笑，银色垂坠耳环。棕色头发扎起的年轻女性，穿着亮红色挂脖蕾丝裙，兴奋地高举一只手臂，仰头大笑，大号金色耳环",
  "Portrait/103-redhead-woman-indoor-portrait-vintage-aesthetic.png": "20岁健身女孩，白皙肤色健美身材，坐在地毯上。自然红色长发松松扎起，几缕碎发框住脸庞。浅蓝灰色眼睛，柔和聚焦的目光看向镜头",
  "Portrait/104-young-woman-mirror-selfie-black-activewear-casual-portrait.png": "浅肤色年轻女性，金发扎成高马尾，散落碎发框住脸庞，红润脸颊，颈部侧面耳后可见小纹身。黑色长袖紧身压缩上衣或连体衣。赤脚（附近地板上可见粉色Crocs洞洞鞋）。",
  "Portrait/005-stylish-woman-mirror-selfie-pink-top-gold-skirt-fashion.png": "镜面反射中涂抹唇彩的魅力女性。年轻女性，柔顺深色高马尾。大号白色花朵耳钉配金色中心",
  "Portrait/006-professional-corporate-headshot.png": "30多岁自信白人男性的专业头像，藏蓝色西装，真诚微笑，模糊办公室背景，自然窗光，佳能85mm，企业摄影，8K画质",
  "Portrait/007-studio-beauty-portrait.png": "白人女性影棚美妆肖像，无瑕妆容，柔光箱灯光，干净白色背景，专业化妆艺术，眼部锐利对焦，8K画质",
  "Portrait/008-candid-street-portrait.png": "时尚年轻白人男性的街头抓拍肖像，城市背景，自然表情，85mm镜头，浅景深，街头时尚摄影，照片级真实",
  "Portrait/009-dramatic-noir-portrait.png": "黑白艺术肖像，高对比度黑色电影灯光，白人女性脸上的戏剧性阴影，经典好莱坞魅力，单色，永恒感",
  "Portrait/010-bohemian-sunset-couple.png": "日落时浪漫的白人情侣肖像，波西米亚风格服装，海滩上欢笑跳舞，黄金时刻逆光，真实情感，生活方式摄影",
  "Portrait/011-vintage-1970s-portrait.png": "70年代胶片摄影白人女性肖像，羽毛层次发型，碎花裹身裙，柔和温暖逆光，重度胶片颗粒，柯达Ektar胶片模拟",
  "Portrait/012-athletic-action-portrait.png": "白人男性运动员运动中动态肖像，汗水飞溅，专注表情，体育场灯光，体育摄影，85mm镜头，戏剧性灯光，照片级真实",
  "Portrait/013-child-wonder-portrait.png": "好奇白人儿童的抓拍肖像，充满惊奇的大眼睛，自然窗光，柔焦背景，真实的童年瞬间，生活方式摄影，温暖色调",
  "Portrait/014-senior-wisdom-portrait.png": "年迈白人男性的性格肖像，饱经风霜的面容，述说故事的深邃皱纹，眼中的智慧，戏剧性窗光，黑白摄影",
  "Still Life/003-chocolate-chip-cookie-splash.png": "动态超写实巧克力曲奇悬浮半空，奶油牛奶活力飞溅，新鲜烘焙，柔光背景，美食摄影，8K画质",
  "Still Life/004-minimalist-perfume-bottle.png": "反光水面上的奢华香水瓶，优雅玻璃设计，柔光箱影棚灯光，柔和色调，干净极简构图，产品摄影，8K画质",
  "Portrait/117-golden-hour-portrait.png": "令人惊叹的逼真年轻女性肖像，黄金时刻阳光穿过发丝创造温暖光晕效果，秋季树木柔和散景背景，真诚温柔微笑，奶油色针织毛衣，佳能EOS R5 85mm f/1.4拍摄，编辑级品质，温暖色调，电影感景深",
  "Portrait/055-mirror-selfie.png": "超写实浴室对镜自拍场景。年轻女性正面站在镜前，光泽缎面真丝短上衣，配套真丝短裤。白色瓷砖浴室墙面带垂直缝隙。柔和自然日光。超写实，高分辨率，锐利细节。",
  "Portrait/119-quiet-defiance.png": "男性斜躺在复古木摇椅上的黑白编辑肖像，对角线构图。宽松白色纽扣衬衫，翻开的书举至胸口上方，直视镜头。单一柔和方向光，经典明暗对照法。编辑级艺术摄影，高对比度，超写实。",
  "Portrait/056-sculpted-stillness.png": "高清时尚肖像，9:16。年轻女性坐在影棚地板上，浅灰色无缝背景。合身长袖白色连体衣，透明白色蕾丝丝袜，银色尖头高跟鞋。柔和漫射影棚灯光。高级时尚编辑感，雕塑感，现代，优雅。",
  "Portrait/121-winter-selfie.png": "超精细户外冬季自拍，特写，面部居中。雪中森林里的年轻女性，俏皮眨眼表情，深棕色皮草帽，黑色罗纹高领毛衣。阴天冬季天空的柔和漫射日光。俏皮冬季时尚美学，自然肌肤光泽，氛围感。",
  "Still Life/122-thors-hand-grips-electrified-sprite-bottle-in-storm.png": "钢铁侠手套悬浮在漂浮的可口可乐罐下方，电影感城市背景，戏剧性电影海报灯光。",
  "Still Life/123-golden-fried-chicken-splashing-in-creamy-dill-sauce.png": "超写实主图：炸鸡腿肉悬在半空，浓郁塔塔酱四溅，刺山柑、莳萝和切碎的酸黄瓜碎屑定格在空中。酱汁飞溅...",
  "Still Life/124-gourmet-burger-food-photography-appetizing-menu-design.png": "超写实主图：热汉堡悬在半空，浓郁塔塔酱四溅，刺山柑、莳萝和切碎的酸黄瓜碎屑定格在空中。酱汁飞溅...",
  "Still Life/125-taco-ingredients-breakdown-fresh-food-photography.png": "同款墨西哥卷饼的分解图，呈现为干净的商业食谱式拆解。正好五种食材，从上到下垂直分离排列，间距均匀完美对齐。食材顺序（上到下）：新鲜番茄莎莎酱40克、车达芝士碎30克、烤鸡肉块80克、脆生菜25克、软质小麦卷饼皮60克（底部）。为每种食材添加清晰的信息图式标注，包含食材名称和精确克重。",
  "Still Life/005-fresh-fruit-still-life.png": "质朴木桌上的时令鲜果静物，戏剧性侧光，温暖色调，丰富纹理，荷兰黄金时代绘画风格，美食摄影",
  "Still Life/006-sneaker-product-studio.png": "单只现代运动球鞋，四分之三视角，干净白色无缝背景，专业影棚灯光，锐利细节，柔和阴影，电商风格",
  "Still Life/007-macaron-pastel-display.png": "大理石台面上色彩缤纷的马卡龙展示，柔和粉蓝黄色调，柔和自然光，优雅烘焙摄影，干净背景，法式甜品",
  "Still Life/008-sushi-platter-japanese.png": "精美摆盘的寿司拼盘，新鲜三文鱼金枪鱼卷，陶瓷盘，酱油碟，筷子，温暖餐厅环境光，日式料理摄影",
  "Still Life/009-gold-jewelry-flat-lay.png": "金色极简珠宝平铺，戒指链条耳环置于白色大理石上，柔和自然日光，优雅构图，时尚配饰产品摄影",
  "Still Life/010-handcrafted-pottery-collection.png": "手工陶瓷器皿系列，哑光大地色釉面，多样形状和尺寸，温暖自然光，工匠工作室背景，波西米亚美学产品摄影",
  "Still Life/011-fresh-baked-bread-loaf.png": "新鲜出炉的手工酸面包，蒸汽升腾，裂开表皮纹理，撒粉表面，质朴木板，温暖窗光，烘焙摄影",
  "Still Life/012-smartphone-clean-product.png": "极简白色底座上的现代智能手机，干净屏幕显示抽象渐变，戏剧性影棚灯光，反光玻璃表面，科技产品摄影",
  "Still Life/013-floral-bouquet-arrangement.png": "玫瑰牡丹桉树的优雅花束插花，柔和淡雅色彩，水晶花瓶，晨间窗光，婚礼花卉摄影，浪漫",
  "Still Life/135-wine-glass-pour-motion.png": "红酒倒入水晶杯，液体飞溅定格瞬间，戏剧性逆光影棚灯光，深色氛围背景，高级餐饮摄影，奢华",
  "Still Life/014-skincare-products-lineup.png": "极简护肤品系列，磨砂玻璃瓶，白色标签，散落绿色植物元素，柔和自然光，纯净美妆摄影，水疗美学，8K画质",
  "Still Life/015-vintage-film-camera-product.png": "木质桌上的经典单镜头旁轴徕卡胶片相机，深色包浆机身，戏剧性侧光，产品摄影，干净极简背景",
  "Still Life/138-tacos-mexican-street-food.png": "质朴木板上的街头墨西哥塔可，新鲜香菜青柠莎莎酱，烤肉牛排，温热玉米饼，鲜艳色彩，俯拍，美食摄影，8K画质",
  "Still Life/016-sunglasses-brand-photography.png": "反光黑色表面上的高端太阳镜，渐变镜片，金色金属框，带彩色滤光片的戏剧性影棚灯光，奢华时尚配饰摄影",
  "Still Life/017-lipstick-beauty-macro.png": "奢华唇膏微距特写，可见奶油质地，金色外壳，柔粉色背景，美妆产品广告摄影，优雅女性美学，8K画质",
  "Still Life/018-ice-cream-sundae-dessert.png": "诱人冰淇淋圣代，巧克力酱滴落，顶部奶油樱桃，华夫筒碎片，彩色糖针，餐厅美学，美食摄影，令人垂涎",
  "Still Life/019-mechanical-watch-movement.png": "机械腕表机芯极限微距，可见齿轮和发条，金色组件，精密工程，深色戏剧性灯光，钟表制造摄影",
  "Still Life/020-tea-ceremony-japanese.png": "日式抹茶茶道布置，陶瓷茶碗，竹制茶筅，绿茶粉，极简禅意构图，柔和自然光，传统美学摄影",
  "Still Life/021-vinyl-record-player.png": "复古黑胶唱片机播放LP唱片，温暖环境灯光，复古音响设备，怀旧氛围，音乐爱好者美学，胶片摄影风格",
  "Still Life/022-candle-collection-minimalist.png": "极简蜡烛系列，大豆蜡，棉质烛芯，中性大地色调，柔和自然光，干净构图，家居装饰产品摄影，宁静美学",
  "Still Life/023-running-shoes-action-freeze.png": "跑鞋悬浮半空，泥土颗粒定格，动态运动捕捉，戏剧性影棚灯光，运动产品摄影，能量与性能，8K画质",
  "Urban/002-tokyo-shinjuku-night-alley.png": "夜晚东京新宿，窄巷布满日文霓虹灯牌，自动售货机发光，湿鹅卵石路面，粉蓝霓虹倒影，小雨，街头摄影",
  "Urban/148-futuristic-transit-hub.png": "未来交通枢纽超精细内部，弧形玻璃天窗屋顶，悬浮磁悬浮列车，抛光石材地板，自然方向光，洁净未来主义",
  "Urban/149-floating-holographic-district.png": "夜间商业区漂浮全息广告牌，行人与全息影像互动，动态青色和琥珀色灯光，粒子效果，超写实材质",
  "Urban/003-dusk-skyline-flying-cars.png": "黄昏时分的未来城市天际线，黄金时刻光线，玻璃钢尖塔，数百辆飞行器留下光轨，层次雾霾，温暖轮廓光，照片级真实",
  "Urban/151-rooftop-garden-arcology.png": "日出时生态建筑塔楼屋顶花园的超写实场景，温暖柔和阳光，垂直农场和梯田，太阳能板，穿未来服装的人群，茂密植被",
  "Urban/152-subterranean-neon-market.png": "超级城市下方密集地下市场，多层结构，霓虹摊位售卖异域商品，温暖悬挂灯笼与冷色LED混合，多样人物，明暗对照灯光",
  "Urban/004-megastructure-construction-twilight.png": "巨型建筑施工中的阴郁黄昏，裸露桁架，起重机剪影映衬紫橙色天空，安全警示灯，工人渺小提供比例参照，HDR细节",
  "Urban/005-european-old-town-square.png": "蓝调时刻迷人的欧洲老城广场，鹅卵石街道，历史建筑温暖发光的窗户，露天咖啡座串灯，教堂尖塔，浪漫",
  "Urban/006-london-rainy-street-reflection.png": "雨后伦敦街道，湿路面反射红色双层巴士和大本钟，灰色阴天，温暖琥珀色路灯，经典英伦氛围",
  "Urban/007-san-francisco-morning-fog.png": "黎明时分的旧金山，金门大桥穿过的翻滚雾气，陡峭山坡上的维多利亚式房屋，温暖晨光穿透薄雾，氛围感摄影",
  "Urban/008-paris-montmartre-morning.png": "日出时的巴黎蒙马特，圣心大教堂，空旷鹅卵石街道，温暖晨光，经典法式建筑，浪漫氛围，街头摄影",
  "Urban/009-hong-kong-neon-night.png": "太平山顶夜景香港，弥敦道霓虹森林，海港灯光倒影，活力不夜城，氛围感城市摄影",
  "Urban/010-venice-canal-gondola.png": "黄金时刻的威尼斯运河，带条纹船桨的贡多拉，历史意大利建筑倒映在平静水面，拱桥，浪漫地中海城市景观",
  "Urban/011-seoul-night-street-food.png": "首尔夜市街头美食，冒着热气的炒年糕摊位，韩文霓虹灯牌，拥挤小巷，温暖橙色灯光，烤架上升起的烟雾，活力城市夜生活",
  "Urban/012-barcelona-gothic-quarter.png": "巴塞罗那哥特区狭窄石巷，中世纪建筑，锻铁阳台，温暖午后光线，西班牙魅力，亲切城市场景，旅行摄影",
  "Urban/013-amsterdam-canal-bikes.png": "阿姆斯特丹运河旁排列的自行车，经典荷兰山墙房屋倒映水中，窗台郁金香，船屋，黄金时刻，迷人城市景观摄影",
  "Urban/014-prague-charles-bridge-dawn.png": "黎明时的布拉格查理大桥，空荡桥梁上的雕像，背景布拉格城堡，雾蒙蒙的伏尔塔瓦河，金色晨光，童话般欧洲城市，氛围感",
  "Urban/164-manhattan-rooftop-party.png": "日落时曼哈顿屋顶派对，背景帝国大厦，串灯，时尚人群，天际线全景，温暖黄金时刻，奢华生活方式摄影",
  "Urban/015-moscow-red-square-snow.png": "新雪覆盖的莫斯科红场，圣瓦西里大教堂彩色穹顶，克里姆林宫城墙，冬日氛围，俄罗斯建筑，阴沉天空，旅行摄影",
  "Urban/016-singapore-marina-bay.png": "蓝调时刻的新加坡滨海湾，滨海湾金沙酒店，艺术科学博物馆莲花造型，城市天际线倒映在平静海湾，未来花园城市，8K画质",
  "Urban/017-copenhagen-nyhavn-colorful.png": "哥本哈根新港彩色历史港口建筑倒映水中，停靠的老式木船，晴天，丹麦hygge舒适氛围，迷人斯堪的纳维亚城市景观",
  "Animals/001-golden-retriever-reading-newspaper-fireplace.png": "金毛犬戴着老花镜坐在壁炉旁的皮椅上，用爪子捧着打开的报纸，温暖的琥珀火光，舒适的维多利亚风格图书馆配书架，油画风格，伦勃朗式灯光，高度细节，8K画质",
  "Animals/002-octopus-inside-glass-teapot-steaming.png": "发光小章鱼在玻璃茶壶里漂浮，壶嘴冒出蒸汽，生物荧光的紫色和蓝色触手贴在玻璃上，暗色阴郁背景，微距摄影，魔幻现实主义，浅景深，8K画质",
  "Animals/003-flamingo-neon-rooftop-cyberpunk-night.png": "粉色火烈鸟单腿站在发光的霓虹屋顶招牌上，夜晚赛博朋克东京天际线，雨水浸透的表面反射洋红和青色灯光，远处飞行汽车，合成波色调，电影级广角镜头，8K画质",
  "Animals/004-snail-carrying-medieval-castle-mossy-forest.png": "花园蜗牛壳上驮着精致的中世纪城堡，在苔藓覆盖的森林地面爬行，清晨露珠，蕨类叶间透过的黄金时刻光线，童话故事书插画，水彩与墨水，复杂细节",
  "Animals/005-penguin-tuxedo-monte-carlo-casino.png": "穿着合身燕尾服的帝企鹅穿过金色赌场大门，蒙特卡洛奢华内景，水晶吊灯，红丝绒地毯，狗仔相机闪光灯，电影低角度镜头，黑色电影灯光，8K画质",
  "Animals/006-koi-fish-swimming-through-sky-clouds-sunset.png": "巨锦鲤在金色日落云层中游弋，鳞片反射橙粉色光芒，超现实梦境，受日本浮世绘影响，空灵薄雾，下方飞鸟作为比例参考，庄严，8K画质",
  "Animals/007-fox-sleeping-hollow-tree-snowfall.png": "红狐蜷缩在空心橡树干里睡觉，外面正在下雪，冷空气中可见温暖呼吸，故事书插画，柔和的粉末蓝与焦橙色色调，温柔月光，温馨氛围，细腻毛发质感",
  "Animals/008-hummingbird-glowing-crystal-flower-dark-cave.png": "蜂鸟在黑暗洞穴中靠近发光水晶花，生物荧光蘑菇在洞壁上投射蓝绿色光芒，彩虹色羽毛反射微光，奇幻概念艺术，戏剧性明暗对照灯光，复杂细节，8K画质",
  "Animals/009-elephant-made-of-autumn-leaves-foggy-meadow.png": "完全由旋转秋叶构成的巨象穿过雾蒙蒙草地，超现实主义绘画风格，马格利特影响，琥珀红与金色树叶，柔和大地色调，梦境般氛围，纯艺术品质，8K画质",
  "Animals/010-cat-round-sunglasses-vinyl-record-shop.png": "橘色虎斑猫坐在复古黑胶唱片店柜台后的凳子上，戴着圆形列侬墨镜，1970年代美学，温暖钨丝灯光，背后墙上挂满专辑封面，胶片颗粒质感，柯达Portra 400效果，8K画质",
  "Animals/011-owl-librarian-ancient-library-candlelight.png": "智慧的仓鸮戴着小圆眼镜栖息在古老教堂图书馆的皮装书堆上，烛光在羊皮纸卷轴上投射温暖金光，光束中漂浮的尘埃微粒，文艺复兴油画风格，卡拉瓦乔式明暗对照法，高度细节的羽毛，8K画质",
  "Animals/012-turtle-japanese-garden-on-shell-ukiyoe.png": "古老乌龟背上驮着微型日式枯山水庭院，配有盆栽松、石灯笼和小瀑布，黎明时分行走在雾蒙蒙的山路上，樱花花瓣飘落，浮世绘木版画风格，葛饰北斋风格，靛蓝与玫瑰色调",
  "Animals/180-wolf-howling-double-moon-alien-forest.png": "白狼站在悬崖上对着两轮巨月长嚎，周围是散发蓝色生物荧光的外星森林和悬浮岩石岛，紫色星云天空划过流星，科幻概念艺术，戏剧性轮廓光，詹姆斯·格尼风格，高度细节，8K画质",
  "Animals/181-iguana-top-hat-pipe-victorian-sitting-room.png": "巨大的蓝色鬣蜥戴着小礼帽和金边单片眼镜，慵懒地躺在维多利亚风格客厅的酒红色天鹅绒躺椅上，抽着雕花花烟斗吐出彩虹色烟圈，瓷茶杯和古董怀表散落在边桌上，深色花卉壁纸，油画，超现实主义，高度细节，8K画质",
  "Animals/182-stag-beetle-knight-jousting-on-pencil-macro.png": "披着闪亮银色铠甲的锹甲虫化身中世纪骑士，骑在黄色铅笔上用牙签长矛比武，橡皮擦战场上散落着图钉巨石，极端微距摄影，浅景深，戏剧性影棚灯光，微缩世界奇幻，8K画质",
  "Animals/013-jellyfish-floating-subway-station-surreal.png": "巨大的半透明水母在废弃地铁站中漂浮，触手瀑布般垂下自动扶梯，生物荧光的蓝光照亮瓷砖墙壁和闸机口，超现实梦境，背景是空荡的车厢，长曝光摄影美学，忧郁之美，8K画质",
  "Animals/014-polar-bear-ice-fishing-aurora-frozen-lake.png": "北极熊夜晚坐在冰封的北极湖面上，守着冰洞钓鱼，绿色和紫色北极光在天空舞动，光滑冰面上的倒影，远山轮廓，国家地理野生动物摄影，清冽寒冷的氛围，8K画质",
  "Animals/015-chameleon-stained-glass-window-gothic.png": "变色龙完美融入高耸的哥特式大教堂彩绘玻璃窗中，皮肤模仿复杂的铅条图案和宝石色调玻璃碎片，阳光透过投射出彩色光影在石板地面，微距摄影，宗教艺术融合，高度细节，8K画质",
  "Animals/016-crow-detective-fedora-foggy-london-alley.png": "黑色乌鸦在维多利亚伦敦雨水浸透的鹅卵石小巷中直立站立，穿着微型米色侦探风衣和小软呢帽，尖喙叼着放大镜，煤气灯在浓雾中投射橙色光芒，两侧砖房，黑色电影摄影，单色配选择性暖色，8K画质",
  "Animals/017-lion-made-of-constellations-night-sky.png": "威严的雄狮完全由星座和星尘构成，银河鬃毛随星云流动在深空之中，身体由相连的星星和宇宙尘埃组成，对着满月咆哮的剪影，宇宙艺术，天文摄影融合，极致细节，8K画质",
  "Animals/018-penguin-band-iceberg-jazz-vintage-poster.png": "五只帝企鹅组成爵士乐队站在漂浮的冰山上，分别吹萨克斯、弹低音提琴、敲冰块鼓、吹小号、唱歌，装饰艺术风格复古旅行海报，大胆几何造型，冷蓝与金色调，8K画质",
  "Animals/019-hippo-bubble-bath-rubber-ducks-whimsical.png": "胖河马慵懒地泡在独立爪足浴缸的泡泡浴中，周围漂着几十只黄色橡皮鸭，SPA氛围配蜡烛和叠好的毛巾，河马鼻子上顶着泡泡，趣味商业摄影，明亮欢快的灯光，幽默感，8K画质",
  "Animals/020-giraffe-lighthouse-rocky-coast-surreal.png": "长颈鹿站在岩石海岸上，长脖子充当灯塔工作着，光束从两只角之间射出，下方海浪拍岸，海鸥盘旋，暴风云在日落时分散开，超现实主义绘画风格，达利风格，温暖金光穿透灰云，8K画质",
  "Animals/021-peacock-tail-feathers-famous-paintings-art-nouveau.png": "孔雀展开尾羽，每根羽毛的眼斑中包含一幅不同的世界名画复制品，蒙娜丽莎、星夜、呐喊、维纳斯的诞生、神奈川冲浪，站在新艺术运动风格的花园中，穆夏风格装饰金边，美术馆灯光，8K画质",
  "Animals/022-bear-hibernating-candy-cave-fantasy.png": "棕熊在完全由水晶糖和冰糖构成的洞穴中酣睡，橡皮糖钟乳石、焦糖石笋、棉花糖床铺，糖晶墙壁散发温暖琥珀色光芒，奇幻插画风格，罗尔德·达尔故事书风格，异想天开又温馨，8K画质",
  "Animals/023-dolphin-leaping-out-of-painting-into-gallery.png": "宽吻海豚跳跃中冲出金色画框中的海景画进入真实的美术馆展厅，水花溅到抛光大理石地板上，画布边缘撕裂，背景中困惑的参观者，打破第四面墙，当代艺术装置，戏剧性灯光，8K画质",
  "Animals/024-squirrel-golden-acorns-autumn-library.png": "红松鼠鼓着腮帮在秋日高耸的图书馆里囤积金色橡果，橡果堆在古董书之间，橡树叶散落在阅读桌上，背景有壁炉暖光，午后光线中的尘埃微粒，毕翠克丝·波特插画风格，水彩与墨水，温馨细节，8K画质",
  "Animals/025-tiger-bamboo-forest-chinese-ink-wash.png": "老虎在茂密竹林中悄然潜行，传统中国水墨画风格，竹子用浓墨粗笔，虎纹用淡墨渲染，雾气在竹间流动，角落有红色印章，宣纸质感，水墨美学，极简而有力",
  "Animals/196-spider-web-dew-drops-spelling-words-macro.png": "园蛛的蛛网上布满晨露，水珠排列拼出DREAM一词，蜘蛛在网中心等待，雾蒙蒙草地上的微距摄影，每颗露珠如同微小的镜头反射着风景，极端特写，黄金时刻逆光，浅景深，8K画质",
  "Animals/197-raven-pirate-crows-nest-stormy-sea.png": "黑色渡鸦戴着小海盗三角帽和黑色眼罩，紧抓着高桅帆船桅杆顶部木质瞭望台的绳索，下方是狂风暴雨的海面和巨浪，闪电照亮乌云，海盗旗在风中飘扬，戏剧性海景油画，艾瓦佐夫斯基风格，阴郁而史诗感，8K画质",
  "Animals/026-koala-astronaut-moon-eucalyptus-flag.png": "可爱的考拉戴着复古白色太空头盔和银色宇航服，在灰色月球表面插一面桉树叶小旗，黑暗星空背景中地球正在升起，阿波罗任务摄影风格，漂浮的尘埃微粒，电影感，8K画质",
  "Animals/027-swan-ballerina-opera-stage-tutu.png": "优雅的白天鹅穿着淡粉色芭蕾舞短裙和足尖鞋，在宏伟歌剧院舞台上做优美的阿拉贝斯克舞姿，红色天鹅绒幕布，金色聚光灯，落地镜反射场景，德加油画风格，柔和粉彩色调，8K画质",
  "Animals/028-mantis-shrimp-boxer-boxing-ring.png": "真实的螳螂虾直立在拳击台帆布上， powerful 棒状爪子上戴着 oversized 红色拳击手套，分节腹部系着闪亮的冠军腰带，戏剧性顶部竞技场聚光灯，黑暗背景中观众剪影，体育摄影，高对比度，8K画质",
  "Animals/029-sloth-steampunk-clock-tower-pocket-watch.png": "昏昏欲睡的树懒倒挂在高耸蒸汽朋克钟楼里的巨大黄铜怀表上，周围全是齿轮和钟摆，彩色玻璃窗透进温暖金光，蒸汽管道，维多利亚机械奇幻，高度细节，电影感，8K画质",
  "Animals/030-hedgehog-yarn-ball-knitting-needles.png": "可爱的刺猬蜷缩成一团五彩缤纷的羊毛线球，旁边交叉放着两根木质棒针，散落的线头拖到温馨木桌上，柔和窗光，田园美学，异想天开插画，温暖舒适，8K画质",
  "Animals/031-axolotl-victorian-bathtub-rose-petals.png": "粉色蝾螈带着蓬松的外鳃，惬意地躺在装满水和漂浮玫瑰花瓣的维多利亚爪足浴缸中，池边放着蜡烛，背后是华丽的金色镜子，洛可可浴室装饰，柔和温暖灯光，魔幻现实主义，梦幻氛围，8K画质",
  "Animals/204-camel-caravan-sea-of-clouds-sunrise.png": "骆驼商队在日出时穿越浩瀚的金色云海，剪影倒映在如水面般的云层上，远处山峰若隐若现，披着飘逸长袍的贝都因骑手，空灵奇幻风景，温暖的橙粉色光线，8K画质",
  "Animals/032-sheep-rainbow-sweater-scottish-highland.png": "毛茸茸的绵羊穿着手工编织的彩虹条纹毛衣，站在黎明时分雾蒙蒙的苏格兰高地草甸上，背景是起伏的绿色山丘和石屋，草上的晨露，温馨田园美学，柔和粉彩光线，异想天开田园摄影，8K画质",
  "Animals/033-otter-kelp-forest-teacup.png": "海獭安详地漂浮在一只巨大的瓷茶杯里，周围是水下海带森林，小鱼在 seaweed 间游动，气泡上升，柔和的蓝绿色光线从上方洒下，异想天开奇幻，纯艺术自然摄影，8K画质",
  "Animals/034-peacock-spider-disco-ball-dance.png": "雄性孔雀蜘蛛在镜面迪斯科球上跳着色彩斑斓的求偶舞，彩虹色腹部图案反射出五彩缤纷的光芒，深紫色洋红色聚光灯的夜店背景，微距摄影，幽默而活力，8K画质",
  "Animals/208-armadillo-armored-knight-desert-tournament.png": "穿着由抛光骨节构成板甲的犰狳骑士，手持小长矛，骑着一匹犰狳般的坐骑在沙漠比武场奔驰，沙丘、彩色三角旗，电影动作镜头，温暖日落光线，8K画质",
  "Animals/035-puffin-raincoat-stormy-scottish-cliff.png": "大西洋海鹦穿着亮黄色渔夫雨衣和防雨帽，站在狂风暴雨中的潮湿岩石悬崖上，下方巨浪拍岸，风雨交加，阴郁戏剧性天空，国家地理野生动物摄影，浓郁色彩，8K画质",
  "Animals/036-gecko-jewelry-seller-moroccan-bazaar.png": "色彩斑斓的日行守宫在热闹的摩洛哥集市小摊位后面，戴着小圆眼镜和绿色背心，兜售手工串珠首饰和微型宝石戒指，头顶黄铜灯笼，图案地毯，温暖的香料市场灯光，异想天开插画，8K画质",
  "Animals/037-owl-clockwork-gears-steampunk-workshop.png": "完全由黄铜齿轮、铜板和发条弹簧构成的机械猫头鹰，栖息在蒸汽朋克发明家工作室的工作台上，发光的琥珀色眼睛，小气孔冒出蒸汽，工具和蓝图散落，温暖钨丝灯光，复杂细节，8K画质",
  "Animals/212-seahorse-chariot-fish-citizens-coral-city.png": "威严的海马拉着一辆微型金色战车穿过色彩斑斓的水下珊瑚城市，一只戴着王冠的彩色小鱼坐在战车里，鱼儿居民从珊瑚屋窗户中观看，发光水母路灯，远处水下宫殿，奇幻概念艺术，生物荧光色彩，8K画质",
  "Animals/038-raccoon-burglar-jewelry-store-night.png": "戴着黑色眼罩和窃贼帽的浣熊，夜晚从一家豪华珠宝店橱窗爬出，爪子里攥着钻石项链，警报灯闪烁，下方是雨水湿滑的城市街道，黑色电影摄影风格，戏剧性阴影，8K画质",
  "Animals/039-dragonfly-stained-glass-wings-lily-pond.png": "巨型蜻蜓停在黎明时分宁静的百合池塘上方，半透明翅膀由彩绘玻璃面板构成，每个翅段闪耀宝石色彩，下方是睡莲和荷花，柔和薄雾，纯艺术摄影，魔幻现实主义，8K画质",
  "Animals/040-walrus-sea-captain-ice-ship.png": "长着浓密白色胡须的海象穿着海军船长大衣和尖顶帽，站在一艘破冰木船的舵轮旁，船在冰封的北极水域航行，雪花飘落，头顶北极光，复古海事插画，英勇而坚毅，8K画质",
  "Animals/041-fennec-fox-headphones-sahara-dunes.png": "大耳廓狐戴着大号专业耳机和小飞行员夹克，日落时分盘腿坐在撒哈拉金色沙丘顶上，旁边放着便携式音乐播放器，温暖的橙紫色天空，Lo-fi嘻哈美学，悠闲氛围，8K画质",
  "Animals/217-tapir-day-of-dead-sugar-skull-mexico.png": "贝尔德貘脸上画着复杂的亡灵节糖骷髅彩绘，脖子上挂着鲜艳万寿菊，夜晚站在烛光点亮的墨西哥墓地中，头顶是剪纸横幅，温暖烛光，民间艺术风格，文化庆典，8K画质",
  "Animals/042-narwhal-lightsaber-tusk-underwater.png": "独角鲸在深蓝北极水域中游动，长长的螺旋长牙像蓝色光剑一样发光，身后留下生物荧光浮游生物轨迹，背景是冰洞墙壁，空灵的水下灯光，科幻奇幻跨界，电影广角镜头，8K画质",
  "Animals/219-meerkat-family-victorian-portrait.png": "五只猫鼬一家穿着正式的维多利亚服装，在风景画背景前僵硬地摆姿势拍全家福，父亲戴高礼帽，母亲戴软帽，小宝宝穿水手服， sepia 色调古董照片，8K画质",
  "Animals/043-chinchilla-cotton-candy-cloud-bed.png": "毛茸茸的龙猫蜷缩在粉色棉花糖云朵上睡觉，周围漂浮着柔和的彩色糖果和小星星，梦幻粉彩天空背景，可爱奇幻插画，柔和漫射光， adorable 又温馨，8K画质",
  "Animals/221-tardigrade-kaiju-city-monster.png": "巨大的水熊虫怪兽夜晚行走在现代城市中，汽车四散奔逃，高楼林立，霓虹灯招牌反射在它分节的身体上，怪兽电影海报风格，戏剧性电影灯光，暴风雨般的黑暗天空，8K画质",
  "Animals/222-cockatoo-punk-mohawk-electric-guitar.png": "白色凤头鹦鹉顶着亮粉色朋克莫霍克发型，在烟雾弥漫的摇滚演唱会舞台上弹奏红色电吉他，背后是音箱堆叠，彩色舞台灯光，观众剪影欢呼，动感动作 pose，朋克摇滚演唱会摄影，8K画质",
  "Food/001-pancake-stack-syrup-waterfall-kayakers.png": "高耸的金色煎饼堆，枫糖浆如瀑布般倾泻而下，底部的糖浆河里有 tiny 皮划艇运动员划桨，蓝莓和草莓像巨石散落，晨光透过温馨厨房窗户，微缩食物摄影，异想天开且细节丰富，8K画质",
  "Food/224-sushi-roll-spaceship-soy-sauce-nebula.png": "未来感寿司卷形如流线型宇宙飞船，在由旋转酱油构成的黑暗星云中飞行，远处是芥末星星和姜片行星，生物荧光三文鱼光芒，科幻食物概念艺术，戏剧性电影灯光，8K画质",
  "Food/002-croissant-crescent-moon-paris-rooftops.png": "巨大的酥皮牛角面包像新月一样发光，悬浮在黄昏时分的巴黎屋顶之上，温暖金光照亮石板瓦，远处埃菲尔铁塔剪影，柔和薰衣草色天空，魔幻现实主义食物摄影，梦幻氛围，8K画质",
  "Food/003-ramen-cyberpunk-alley-neon-signs.png": "一碗热气腾腾的豚骨拉面放在赛博朋克东京小巷雨水打湿的吧台上，日文霓虹灯招牌倒映在汤里，悬浮的全息筷子，粉色和青色光芒中升起蒸汽，电影街头美食摄影，银翼杀手美学，8K画质",
  "Food/227-chocolate-cake-geological-gold-layers.png": "博物馆里展示的一片巧克力蛋糕，像地质剖面一样切开，黑巧克力、甘纳许和可食用金箔层犹如矿物地层，黄铜小标签标注每一层，优雅画廊灯光，纯艺术食物摄影，8K画质",
  "Food/004-avocado-toast-tiny-hipster-cafe.png": "酸面团牛油果吐司，上面 tiny 潮人坐在小桌子旁，小杯浓缩咖啡和盆栽多肉，大理石咖啡桌，清晨阳光，俯视平铺微缩世界，时髦早午餐摄影，8K画质",
  "Food/005-macarons-impressionist-palette.png": "色彩缤纷的法式马卡龙像印象派油画颜料一样排列在画家调色板上，柔和的粉色、薰衣草紫、薄荷绿和柠檬黄，旁边放着调色刀和画笔，自然窗光，莫奈风格静物，优雅糕点摄影，8K画质",
  "Food/006-burger-ingredients-zero-gravity.png": "精致汉堡被拆解成漂浮食材，黑色太空背景中，芝麻面包、牛肉饼、融化芝士、番茄、生菜、酸黄瓜和培根悬浮在零重力中，戏剧性聚光灯，科幻食物摄影，8K画质",
  "Food/007-pho-steam-forming-dragon.png": "越南河粉盛在深陶瓷碗中，蒸汽升腾卷曲成空灵龙的形状，新鲜香草、青柠和辣椒片漂浮，暗色阴郁背景，温暖逆光，魔幻现实主义食物摄影，8K画质",
  "Food/008-pizza-slice-swimming-pool-tiny-swimmers.png": "巨大的意大利辣香肠披萨片变成度假村游泳池，融化的芝士作为日光浴平台，tiny 游泳者坐在彩色浮具上，饼皮边缘有泳池梯子，明亮夏日，鸟瞰视角，超现实食物摄影，8K画质",
  "Food/009-coffee-latte-art-galaxy.png": "一杯咖啡的特写，拉花描绘着旋转的星河与星云，奶泡表面反射宇宙紫色和蓝色，陶瓷杯放在深色木桌上，柔和晨光，天文摄影与咖啡艺术结合，8K画质",
  "Food/010-donut-planet-with-sprinkle-rings.png": "巨大的粉色糖霜甜甜圈像行星一样漂浮在太空，周围环绕着彩色糖屑组成的星环，tiny 宇航员探索表面，背景是星星和星系，异想天开宇宙食物艺术，8K画质",
  "Food/011-lobster-roll-new-england-beach-sunset.png": "龙虾卷放在切开的布里欧修面包里，大块新鲜龙虾肉配柠檬黄油，放在新英格兰海滩风化木板上，金色日落在海平面上，远处帆船，夏日美食摄影，温暖诱人，8K画质",
  "Food/012-dim-sum-hot-air-balloons.png": "竹蒸笼变成彩色热气球，漂浮在日出时雾蒙蒙的中国山谷上空，编织缝隙中可见里面的饺子，丝带拖曳，下方是传统水墨山水，超现实食物奇幻，8K画质",
  "Food/013-ice-cream-cone-melting-dali-clock.png": "香草冰淇淋蛋筒从桌边融化滴落，液滴形成柔软的达利风格融化时钟，粉蓝和粉红背景，超现实主义食物绘画，柔焦，异想天开如梦似幻，8K画质",
  "Food/014-tacos-day-of-dead-celebration.png": "三个色彩鲜艳的街头玉米卷放在装饰祭坛上，周围环绕万寿菊、糖骷髅和发光蜡烛，头顶剪纸横幅，温暖节日灯光，墨西哥民间艺术风格，文化食物摄影，8K画质",
  "Food/015-bagel-lox-new-york-cityscape.png": "全味贝果配奶油芝士和烟熏三文鱼，排列成微型纽约城市景观，刺山柑当窗户，红洋葱片当建筑，莳萝当树，白色盘子里插着自由女神像牙签，异想天开早餐摄影，8K画质",
  "Food/016-matcha-tea-ceremony-bamboo-forest.png": "宁静的竹林中的传统日本抹茶茶道布置，石板小径，苔藓覆盖地面，陶瓷碗中升起蒸汽，竹制茶筅和甜点摆放在漆器托盘上，柔和漫射绿光，禅意氛围，8K画质",
  "Food/017-cupcake-tower-fairy-tale-castle.png": "一摞精心装饰的纸杯蛋糕堆成童话城堡，粉彩糖霜塔楼，糖珍珠窗户，翻糖吊桥，放在魔法森林空地的银盘上，柔和金光，异想天开糕点艺术，8K画质",
  "Food/018-steak-volcanic-rock-lava-glow.png": "完美煎制的五分熟牛排放在黑色火山岩石板上，裂缝下发出红橙色熔岩光芒，迷迭香和百里香枝条冒烟，戏剧性高级餐厅环境，高端美食摄影，8K画质",
  "Food/019-waffles-berries-kandinsky-painting.png": "比利时华夫饼放在白盘上，莓果和奶油排列成康定斯基抽象画的样子，草莓、蓝莓和奶油的 bold 几何造型，明亮色彩，俯视平铺，现代主义食物艺术，8K画质",
  "Food/020-bento-box-japanese-garden.png": "打开的日式便当盒呈现精心布置的微型日本庭园，米饭塑成枯山水石园，刺身鱼片当锦鲤池，枝豆当树，海苔当踏脚石，木质便当盒，俯视视角，8K画质",
  "Food/021-cinnamon-roll-spiral-galaxy.png": "肉桂卷俯视特写，螺旋图案形成金色星系，糖晶像星星一样闪烁，温暖肉桂光芒，柔和虚化背景，宇宙糕点摄影，梦幻诱人，8K画质",
  "Food/022-soup-dumplings-bamboo-steamer-spaceship.png": "竹蒸笼像宇宙飞船一样在太空飞行，里面装满晶莹剔透的小笼包，蒸汽轨迹形成火箭尾焰，远处行星和星星，亚洲未来主义食物概念，戏剧性灯光，8K画质",
  "Food/023-french-fries-golden-forest.png": "酥脆金黄薯条直立像微型森林，底部蜿蜒着番茄酱小河，tiny 野餐场景配毯子，温暖快餐店灯光， playful 超现实食物摄影，8K画质",
  "Food/024-bubble-tea-tapioca-planets.png": "巨大珍珠奶茶杯作为宇宙场景，黑色珍珠像行星一样漂浮在奶白色星云中，粗吸管当太空电梯，粉紫和粉红渐变背景，流行台湾饮品摄影，超现实，8K画质",
  "Food/025-cheese-board-mountain-landscape.png": "精致烤芝士三明治对半切开，融化的芝士在两端之间拉伸成一座金色吊桥，tiny 汽车行驶其上，下方番茄浓汤如河流，异想天开微缩食物摄影，温暖治愈，8K画质",
  "Food/026-risotto-glowing-moon-italian-vineyard.png": "黑色碗中的奶油蘑菇烩饭，蒸汽升腾勾勒出红瓦屋顶的地中海村落剪影，新鲜香草点缀，深色质朴木桌，魔幻现实主义食物摄影，8K画质",
  "Food/027-pretzel-bavarian-clock-tower.png": "巨大的软椒盐卷饼扭成巴伐利亚钟楼形状，芥末酱细节当窗户，设在传统啤酒节帐篷中，长木桌和蓝白旗帜，金色午后光线，节日美食摄影，8K画质",
  "Food/028-fruit-tart-stained-glass-window.png": "俯视新鲜水果挞，莓果和切片猕猴桃排列成哥特式彩绘玻璃窗图案，光泽杏子釉，金黄酥皮，明亮自然光，艺术甜点摄影，8K画质",
  "Food/253-hot-chocolate-volcano-marshmallow-lava.png": "巨大的热巧克力杯上演棉花糖火山喷发，融化的棉花糖熔岩从巧克力杯壁流下，顶部奶油雪冠，可可粉灰云，底部肉桂棒树木，温暖冬夜小屋灯光透过磨砂窗，异想天开食物摄影，8K画质",
  "Food/029-crepe-bridge-nutella-river.png": "薄法式可丽饼折叠成拱桥形状横跨在一池温热的巧克力榛果酱上，新鲜草莓半块和香蕉片放在可丽饼上，糖粉撒在顶部，榛子散落在盘子上，柔和烘焙灯光，异想天开甜点摄影，8K画质",
  "Food/030-peking-duck-lantern-temple.png": "整只烤北京烤鸭皮脆如漆悬挂在中国传统寺庙庭院的红色纸灯笼之间，梅花枝条，鸭身升起蒸汽，灯笼金光，月夜，文化美食摄影，电影氛围，8K画质",
  "Food/031-gelato-colorful-sand-dunes.png": "多色意式冰淇淋球排列成俯视沙漠沙丘，开心果绿、草莓粉、香草奶油、巧克力棕和柠檬黄沙丘，华夫筒棕榈树投下长影，糖屑当沙漠花朵，温暖日落色调，鸟瞰食物艺术，8K画质",
  "Food/032-sourdough-bread-hollow-bakery.png": "挖空的酸面团面包变成微型面包店内部，tiny 木架上摆着面包，小型石砌壁炉有火苗，面粉袋，擀面杖桌子，温暖琥珀色光从内部透出，剖面视角，异想天开微缩食物艺术，8K画质",
  "Food/033-mochi-moons-japanese-night-sky.png": "各种口味麻薯冰淇淋球漂浮在暗色日本夜空中如一团满月，抹茶绿、草莓粉、黑芝麻和香草白，每个发出柔光，樱花瓣飘落，下方宝塔剪影，梦幻魔幻食物摄影，8K画质",
  "Food/034-paella-sunken-treasure-coral-reef.png": "巨大的西班牙海鲜饭锅俯视如海底沉船宝藏，藏红花米饭当沙质海底，虾和青口当珊瑚礁生物，甜椒条当海草，柠檬角当宝箱金子，藏红花丝当珠宝，水下灯光效果，超现实西班牙食物艺术，8K画质",
  "Food/035-eclair-victorian-railway-carriage.png": "细长巧克力闪电泡芙形如维多利亚铁路车厢，巧克力釉当抛光木板，奶油泡芙当车轮，裱花糖霜窗户里有 tiny 剪影，放在手指饼干做的轨道上，糖粉蒸汽，复古火车站背景，8K画质",
  "Food/036-dumpling-origami-crane.png": "一只精美的褶皱中国饺子折叠成折纸鹤的样子，半透明皮子隐约可见馅料，放在一汪黑醋酱油上，芝麻散落，筷子放在一旁，极简深色背景，纯艺术食物摄影，8K画质",
  "Food/037-tiramisu-archaeological-dig.png": "方形提拉米苏切片展示为考古挖掘现场，马斯卡彭和咖啡浸手指饼干层如地质层，可可粉当挖掘尘土，小型挖掘工具和刷子，白巧克力做的 tiny 恐龙骨从层中露出，博物馆灯光，8K画质",
  "Food/038-kebab-skewer-totem-pole.png": "竖直的烤肉串作为太平洋西北图腾柱，腌制的羊肉块和蔬菜雕刻着动物面孔，下方烤架火焰投出戏剧性上升阴影，烟雾形成灵兽形状，暗色森林背景，部落食物艺术，8K画质",
  "Food/039-cheesecake-art-deco-skyscraper.png": "高耸的纽约芝士蛋糕切片竖立在盘子上，全麦饼干碎底座，光滑奶油芝士馅料配光泽莓果酱顶，奶油尖峰，周围是巧克力做的微型建筑，暗色城市夜景背景配 tiny 可食用闪粉星星，8K画质",
  "Food/040-scone-english-garden-maze.png": "对切司康饼配凝脂奶油和草莓酱放在微型英式花园迷宫中心，面包屑小路向外延伸，盆栽香草当树篱，小型茶水喷泉，俯视视角，柔和午后花园光线，异想天开英式食物艺术，8K画质",
  "Food/041-bibimbap-color-wheel-painter-studio.png": "石碗韩式拌饭排列成画家色轮，胡萝卜橙、菠菜绿、蛋黄黄、蘑菇棕、豆芽白和辣椒酱红从中心辐射，俯视视角放在木制画家桌上，旁边画笔和颜料管，8K画质",
  "Food/042-churros-golden-spiral-staircase.png": "肉桂糖吉拿棒盘旋成金色螺旋楼梯环绕黑巧克力酱中央塔，顶部小巧克力杯当观景台，每级台阶上肉桂粉闪烁，温暖金光，异想天开甜点建筑，8K画质",
  "Food/043-creme-brulee-starry-night.png": "焦糖布丁特写，焦糖表面裂开露出内部蛋奶中的梵高星空，旋转的可食用金色和蓝色，糖晶做的小星星，裂缝边缘发出琥珀光，暗色浪漫灯光，8K画质",
  "Food/044-spring-rolls-chinese-pagoda.png": "金黄春卷堆叠排列成多层中国宝塔，甜辣酱当屋瓦，香菜当悬挂灯笼，芝麻当装饰飞檐，放在莲池上蘸料当倒影水面，俯视角度，8K画质",
  "Food/045-pavlova-cloud-fruit-rainbow.png": "帕芙洛娃蛋白霜像柔软白云漂浮在粉彩天空，顶部新鲜水果彩虹拱门，草莓、芒果、猕猴桃、蓝莓和百香果，奶油当云絮，水果糖浆 tiny 雨滴落下，梦幻甜点摄影，柔和漫射光，8K画质",
  "Food/046-gyoza-lotus-flower-pond.png": "煎饺子圆形排列如暗色池塘上绽放的莲花瓣，金黄脆底朝上如阳光花瓣，黑芝麻当莲蓬，葱丝当荷叶，蘸料当池水，俯视视角，8K画质",
  "Food/047-brownie-geode-crystal-interior.png": "布朗尼对半掰开露出闪亮晶洞内部，可食用糖晶呈紫色、蓝色和琥珀色从巧克力壁生长，金箔碎片，糖粉当矿物粉尘，暗色阴郁背景，戏剧性聚光灯，地质甜点摄影，8K画质",
  "Food/048-ratatouille-pixel-art-mosaic.png": "普罗旺斯炖菜俯视排列成像素艺术马赛克，精确切割的西葫芦、茄子、番茄和甜椒圆片重复排列，每片蔬菜当一个像素，温暖普罗旺斯色调，橄榄油光泽，放在质朴陶瓷盘上，现代主义法国食物艺术，8K画质",
  "Food/049-cannoli-roman-columns-forum.png": "意式奶油煎饼卷竖立如微型古罗马广场的石柱，奶油馅当科林斯柱头，开心果碎当装饰楣板，巧克力碎片当石刻，糖粉当地面大理石粉尘，金色时分地中海光线，8K画质",
  "Food/050-smores-campfire-marshmallow-tents.png": "篝火烤棉花糖场景，全麦饼干搭成 tiny A 字形帐篷围绕巧克力条火坑，棉花糖在树枝上烤，棉花糖霜当烟雾，巧克力酱当木柴，星空背景有全麦饼干屑星座，异想天开户外食物艺术，8K画质",
  "Food/051-mapo-tofu-volcanic-eruption.png": "一碗麻婆豆腐拍摄成火山喷发场景，鲜红辣椒油如流动熔岩，白嫩豆腐块当火山岩，花椒当飞溅碎片，蒸汽当喷发云，筷子夹起瞬间溅出如岩浆迸发，暗色戏剧灯光，8K画质",
  "Food/052-profiterole-wedding-cake-topiary.png": "奶油泡芙塔堆叠成优雅婚礼蛋糕形如螺旋造型树，焦糖丝如常春藤缠绕，白巧克力花在层间绽放，金箔点缀，顶部拉糖蝴蝶，柔和浪漫虚化背景，8K画质",
  "Abstract/014-ink-drop-water-city-skyline.png": "黑色墨水滴入清水中，扩散的卷须形成蔓延的城市天际线剪影，水下湍流创造云状烟柱，戏剧性侧光，抽象流体艺术摄影，高对比度，8K画质",
  "Abstract/015-liquid-mercury-geometric-crystals.png": "液态水银向上飞溅并瞬间冻结成锐利的几何晶体，镜面反射从深紫到琥珀的渐变天空，暗色背景，高速微距摄影，抽象金属艺术，8K画质",
  "Abstract/016-neon-light-magnetic-field-bending.png": "电蓝色和洋红色霓虹光束在黑暗虚空中绕着看不见的磁场线弯曲旋转，光迹留下渐隐余晖，体积雾捕捉光芒，长曝光光绘美学，8K画质",
  "Abstract/017-gemstone-sand-dunes-wind-tunnel.png": "风洞中由粉碎宝石构成的沙丘，石榴红、蓝宝石蓝、祖母绿和黄玉金色颗粒在雕琢的脊线上流动，微距质感细节，戏剧性掠射光，抽象矿物风景，8K画质",
  "Abstract/019-smoke-rings-mathematical-equations.png": "优雅的白色烟环漂浮在暗色工作室中，每个环变形为不同的数学符号，积分号、无穷符号和斐波那契螺旋，柔和逆光使烟雾发光，超现实抽象摄影，8K画质",
  "Abstract/283-bokeh-constellation-human-emotions.png": "数百个暖冷色调失焦光点散落在暗色背景上，自行排列成暗示人类面部表情的星座图案，柔和圆形散景，梦幻景深，抽象情感星图，8K画质",
  "Abstract/020-molten-glass-frozen-explosion-color.png": "熔融玻璃在爆炸碎裂的精确瞬间被捕捉，鲜艳的橙色、钴蓝色和红宝石碎片悬浮在零重力中，每片碎片以不同方式折射光线，黑色背景，高速抽象玻璃艺术摄影，8K画质",
  "Abstract/023-yarn-threads-topographic-map.png": "数百根彩色纱线在三维层中拉伸编织，形成虚构风景的抽象地形图，暖红和冷蓝创造海拔对比，掠射侧光揭示深度，纺织艺术微距，8K画质",
  "Abstract/025-prismatic-light-rainforest-canopy.png": "一束白光进入茂密雨林树冠并分裂成完整棱镜光谱，每个色带照亮不同层次的雾气和树叶，天堂光，体积光，抽象自然光谱学，8K画质",
  "Abstract/026-ferrofluid-baroque-cathedral-spires.png": "黑色铁磁流体响应隐藏磁铁，形成类似巴洛克教堂剪影的高耸尖刺结构，下方反光铬面，上方戏剧性聚光灯，暗色阴郁抽象科学艺术，8K画质",
  "Abstract/027-paint-splatter-inner-galaxy.png": "爆炸性颜料飞溅在半空中定格，中心出人意料地展现出颜料液滴内旋转的星系，蓝色和紫色丙烯在黑色画布上，颜料拉丝如宇宙丝状结构，微距抽象艺术，8K画质",
  "Abstract/028-cracked-ice-mandala-northern-lights.png": "鸟瞰开裂的冰冻湖面形成天然曼陀罗图案，绿色和紫色北极光在湿润冰面上反射，雪填充裂缝形成精致线条，北极夜空，抽象自然摄影，8K画质",
  "Abstract/029-honey-slow-motion-abstract-calligraphy.png": "金色蜂蜜在极度慢动作中滴落，下落的流扭曲成抽象书法笔触，仿佛拼写被遗忘的文字，温暖琥珀逆光，深色板岩背景，微距流体动力学艺术，8K画质",
  "Abstract/030-aurora-reflected-liquid-gold-pool.png": "绿色和紫色北极光倒映在完美静止的液态金池中，涟漪将光线扭曲成抽象波纹图案，远处北极山脉剪影，超现实抽象风景，8K画质",
  "Abstract/031-stained-glass-butterfly-wing-reassembly.png": "破碎的彩色玻璃碎片悬浮在半空中并重新组合成巨大蝴蝶翅膀的图案，红宝石、蓝宝石、祖母绿和琥珀碎片以不同角度折射光线，暗色背景，抽象马赛克艺术，8K画质",
  "Abstract/032-light-painting-dream-architecture.png": "长曝光光绘在空中勾勒出不可能的梦境建筑轮廓，发光的蓝色和白色光线形成通往虚无的楼梯和打开向虚空的门，黑暗废弃仓库场景，8K画质",
  "Abstract/033-petals-dissolving-watercolor-pixels.png": "樱花花瓣在下落中溶解，碎裂成微小的水彩像素如五彩纸屑般散开，每个像素是略微不同的粉色调，白色背景，抽象数字与有机融合艺术，微距摄影，8K画质",
  "Abstract/034-bismuth-crystals-spiral-staircase.png": "虹彩彩虹色铋晶体以不可能的螺旋楼梯形态生长，金属氧化物呈蓝色、金色和紫色，几何矩形漏斗晶体，微距矿物摄影，暗色背景，8K画质",
  "Abstract/035-soap-film-sunset-microscopic.png": "薄皂膜气泡表面的微距摄影，虹彩干涉图案创造日落橙、蓝绿和洋红的抽象旋转色带，薄膜缓慢变薄和移动，黑色背景，科学抽象艺术，8K画质",
  "Abstract/036-marbled-paper-alien-planet-landscape.png": "俯视传统大理石纹纸张艺术，旋转墨纹像外星球鸟瞰图，有河流、山脉和峡谷，呈不可能的紫色、蓝绿和铜色，掠射光照在湿润表面，8K画质",
  "Abstract/037-resin-art-frozen-storm-system.png": "圆形环氧树脂艺术品捕捉微型冻结风暴系统，白色和灰色颜料旋转如云，银箔如闪电，中心是平静的蓝色风眼，俯视视角，光泽表面，抽象天气艺术，8K画质",
  "Abstract/038-lichen-ancient-map-patterns.png": "风化石头上多彩地衣的极限微距，图案像海岸线和贸易路线的古代地图，鲜艳的橙色、灰绿色和黄色壳状形态，天然抽象制图学，柔和漫射光，8K画质",
  "Abstract/039-shattered-mirror-kaleidoscope-memories.png": "破碎镜片散落在暗色表面上，每片反射不同的模糊场景如记忆碎片，暖冷色调交织，单一明亮光源创造复杂反射图案，抽象内省艺术，8K画质",
  "Abstract/040-copper-sulfate-crystals-growing-reef.png": "电蓝色硫酸铜晶体在暗色表面生长，形态像外星珊瑚礁，锐利几何边缘与有机分支生长形成对比，微距矿物摄影，戏剧性侧光，抽象化学艺术，8K画质",
  "Abstract/041-origami-paper-folds-shadow-geometry.png": "数百个小白色折纸折叠排列在灯台上，它们的阴影创造精致的几何抽象图案，纸张捕捉暖光而阴影形成对比的冷蓝网格，俯视视角，极简抽象艺术，8K画质",
  "Portrait/015-lavender-field-auburn-hair-woman.png": "红褐色长发的欧洲女性站在薰衣草花田中，柔和的黄金时刻光线，风扬起裙摆，身后是普罗旺斯乡村风景，梦幻散景，电影感人像摄影",
  "Portrait/016-elderly-storyteller-wooden-porch.png": "双手布满皱纹、眼神温和的白人老年男性坐在木制门廊上，做着手势讲故事，背景是质朴农舍，温暖的午后阳光，纪录片风格人像，浅景深",
  "Portrait/017-teenage-artist-paint-stained-overalls.png": "背带裤沾满颜料的欧洲少女手持画笔站在阳光普照的画室里，周围是画布和调色板，充满创作能量，凌乱头发，温暖画室光线，真实抓拍照",
  "Portrait/018-woman-archaeologist-desert-excavation.png": "白人女性考古学家在沙漠发掘现场，脸上沾着泥土，手持古代陶片，沙丘后的日落，冒险精神，国家地理风格人像，戏剧性阴影",
  "Portrait/019-young-man-navy-suit-rooftop-bar.png": "身着定制藏青色西装的欧洲年轻男子站在夜间屋顶酒吧，身后是城市天际线，手持威士忌酒杯，自信姿态，忧郁的蓝琥珀色灯光，时尚编辑人像",
  "Portrait/020-mother-daughter-strawberry-garden.png": "欧洲母亲和蹒跚学步的女儿在阳光花园中摘草莓，两人都戴着草帽，孩子伸手去够成熟草莓，母爱温柔，柔和自然光，生活风人像",
  "Portrait/057-ballet-dancer-arabesque-empty-stage.png": "欧洲芭蕾舞者在空旷剧院舞台做阿拉贝斯克舞姿，戏剧性聚光灯，光束中漂浮尘埃，黑色紧身衣和飘逸舞裙，表情坚定，剧场人像",
  "Portrait/310-firefighter-woman-full-gear.png": "身着全套装备的欧洲女性消防员，摘下头盔，额头有汗珠，站在消防车前，坚强而坚韧的表情，烟雾弥漫的氛围，粗犷英雄人像",
  "Portrait/021-grandfather-grandson-fishing-misty-lake.png": "欧洲祖父在黎明薄雾湖边教孙子钓鱼，两人呈剪影，耐心与智慧，轻柔晨雾，水中倒影，情感代际人像",
  "Portrait/022-woman-scientist-lab-coat-microscope.png": "穿白大褂的欧洲女性科学家，身后是荧光显微镜，屏幕上有发光细胞，戴眼镜专注表情，研究实验室环境，冷蓝色灯光，专业人像",
  "Portrait/023-street-musician-saxophone-rainy-paris.png": "欧洲女性街头音乐家在巴黎雨中 sidewalk 吹萨克斯，潮湿鹅卵石路面反射暖色街灯，雨衣和贝雷帽，忧郁之美，城市黑色电影人像",
  "Portrait/024-flapper-dress-1920s-jazz-club.png": "身着复古1920年代飞女郎礼服的欧洲年轻女子，羽毛和珍珠装饰，爵士俱乐部内部，烛光，复古魅力，黑金色调，装饰艺术风格人像摄影",
  "Portrait/025-male-chef-wok-flames-action.png": "穿白色制服的欧洲男性厨师，锅中火焰升腾，表情专注，厨房动作镜头，戏剧性火光，烹饪热情，高对比度人像",
  "Portrait/026-little-girl-yellow-raincoat-puddles.png": "穿黄色雨衣的欧洲小女孩在水洼中踩水，脸上洋溢着纯粹的喜悦，雨天，背景有其他孩子的彩色雨伞，无忧无虑的童年，活力生活风人像",
  "Portrait/027-woman-mountain-climber-summit-victory.png": "欧洲女性登山者站在山顶，风吹乱头发，双臂高举的胜利姿势，身后是雪峰，晨光破云而出，史诗级成就人像",
  "Portrait/058-tattoo-artist-woman-neon-studio.png": "欧洲女性纹身师在工作室中，手指沾着墨水，客户手臂上有精致纹身，前卫审美，霓虹招牌光芒，创意亚文化，城市人像",
  "Portrait/028-couple-tango-buenos-aires-milonga.png": "欧洲情侣在昏暗的布宜诺斯艾利斯探戈舞厅中翩翩起舞，两人之间充满激情，戏剧性舞姿，红色礼服和黑色西装，亲密氛围，舞蹈人像摄影",
  "Portrait/029-woman-librarian-bookshelves-manuscript.png": "被高耸书架环绕的欧洲女性图书管理员，正在阅读珍贵手稿，阳光中漂浮尘埃，粗花呢外套和阅读眼镜，安静知性之美，温暖图书馆人像",
  "Portrait/321-surfer-man-carrying-board-dawn-beach.png": "欧洲男性冲浪者抱着冲浪板走在阳光海滩上，头发上沾着海水，手上有冲浪蜡，黎明光线，背景是海浪，健康古铜肤色，运动生活风人像",
  "Portrait/030-woman-astronaut-training-simulator.png": "接受训练的欧洲女性宇航员，身处空间站模拟器内，暗示零重力的飘浮头发，连体服上的任务徽章，未来感灯光，决心与惊奇，科幻人像",
  "Portrait/031-street-artist-woman-spray-mural.png": "欧洲女性街头艺术家在砖墙上喷涂鲜艳的壁画，衣服上溅满彩色颜料，城市小巷背景，创意反叛，动感动作人像",
  "Portrait/032-woman-irish-sweater-rugged-cliff.png": "身着传统爱尔兰渔夫毛衣的欧洲女性站在崎岖悬崖上，海风拂面，脚下是壮阔的大西洋，凯尔特传统，阴郁多云天空，电影感风景人像",
  "Portrait/033-young-man-acoustic-guitar-sunset-dock.png": "欧洲年轻男子在日落时分的木制码头弹奏原声吉他，湖面倒影，音乐家的灵魂，温暖琥珀色调，忧郁之美，民谣艺术家人像",
  "Portrait/034-woman-midwife-holding-newborn.png": "欧洲女性助产士抱着新生儿，温柔微笑，柔和光线的医院房间，温馨时刻，专业关怀人像，暖色调",
  "Portrait/035-man-leather-jacket-vintage-motorcycle-desert.png": "穿皮夹克的欧洲男子骑着复古摩托车行驶在沙漠公路上，风沙飞扬，自由与反叛，黄金时刻光线，电影感公路人像",
  "Portrait/036-woman-beekeeper-white-suit-honeycomb.png": "身着白色防护服的欧洲女性养蜂人，周围是金色蜂巢框架，阳光透过蜂箱，宁静专注的表情，温暖的琥珀色调，纪录片人像",
  "Portrait/037-man-glassblower-molten-glass-furnace.png": "欧洲男性玻璃吹制工用长管塑造熔融玻璃，熔炉发出橙色光芒，戴着护目镜，工匠作坊人像，戏剧性暖光",
  "Portrait/038-woman-choir-singer-gothic-cathedral.png": "欧洲女性唱诗班歌手身着天鹅绒长袍站在哥特式大教堂内，烛光照亮她的脸庞，虔诚的表情，神圣氛围人像，浓郁的酒红与金色调",
  "Portrait/039-boy-scout-compass-pine-forest.png": "欧洲童子军手持指南针背着背包站在松树林中，坚定地查看地图，秋叶飘零，冒险人像，朴实的绿棕色调",
  "Portrait/332-woman-sommelier-wine-cellar-barrels.png": "欧洲女性侍酒师在水晶杯中旋转红酒，身后是昏暗酒窖和橡木桶，精致表情，优雅人像，深红和酒红色调",
  "Portrait/333-man-luthier-carving-violin-workshop.png": "欧洲男性小提琴制作师在阳光充足的工作室雕刻小提琴琴身，工作台上有木屑，专注的双手，工匠人像，温暖的金色木色调",
  "Portrait/040-woman-deep-sea-diver-boat-deck.png": "欧洲女性深海潜水员身着装备站在船甲板上，身后是海平面，手持面罩，海风夹杂着盐雾，冒险人像，青蓝和钢蓝色调",
  "Portrait/335-elderly-man-clockmaker-antique-timepieces.png": "欧洲老年钟表匠被古董钟表环绕，眼睛上架着放大镜，用灵巧的手调整齿轮，亲密作坊人像， sepia 和黄铜色调",
  "Portrait/041-woman-circus-ringmaster-red-coat.png": "欧洲女性马戏团领班身着红色外套和金色肩章，站在聚光灯下的中央舞台，手持鞭子，自信而戏剧化的姿态，复古马戏团人像，酒红和金色灯光",
  "Portrait/042-woman-reading-window-seat-rain.png": "欧洲年轻女子坐在窗边座位读书，窗外下着雨，盖着舒适羊毛毯，茶杯冒着热气，沉思的表情，雨日下午人像，柔和灰色和温暖琥珀色调",
  "Portrait/043-man-blacksmith-hammering-iron-sparks.png": "欧洲男性铁匠在铁砧上锤打炽热铁块，火花飞溅，皮围裙，肌肉发达的手臂，火光映照的铁匠铺人像，戏剧性橙黑色调",
  "Portrait/044-woman-midwife-sunlit-birthing-room.png": "欧洲女性助产士在阳光充足的产房中，温柔的双手和温暖的微笑，薰衣草色和白色环境，关怀专业人像，柔和粉彩色调",
  "Portrait/045-teenager-girl-chess-park-pavilion.png": "欧洲少女在公园凉亭里下棋，专注地盯着棋盘，秋日午后，知性青春人像，温暖的琥珀和绿色调",
  "Portrait/046-man-organic-farmer-sunflower-field.png": "欧洲男性有机农场主站在向日葵田中，戴着草帽，粗糙的双手捧着泥土，乡村自豪感人像，金黄和大地色调",
  "Portrait/047-woman-opera-singer-rehearsal-grand-piano.png": "欧洲女性歌剧演员在带有三角钢琴的排练室排练，戏剧性的手势，激情的表情，艺术人像，戏剧性聚光灯与阴影",
  "Portrait/048-man-astronaut-white-spacesuit-lunar-sim.png": "欧洲男性宇航员身着白色宇航服站在模拟月球表面，面罩反射着星光，未来感训练基地人像，纯白和深蓝色调",
  "Portrait/049-woman-pastry-chef-piping-cake-decorations.png": "欧洲女性糕点师在高耸的蛋糕上裱制精致装饰，粉彩厨房，糖霜花朵，快乐而专注，烹饪艺术家人像，柔和粉色和奶油色调",
  "Portrait/050-elderly-woman-knitting-farmhouse-porch.png": "欧洲老年女性在农舍门廊上编织彩色毯子，猫在她身旁熟睡，金色午后阳光，宁静乡村人像，温暖多彩纱线色调",
  "Portrait/051-man-pilot-propeller-plane-grass-airstrip.png": "欧洲男性飞行员身着制服站在草地机场的小型螺旋桨飞机旁，戴着飞行员墨镜，风吹乱头发，冒险天空人像，天蓝和卡其色调",
  "Portrait/052-woman-archaeologist-desert-tent-pottery.png": "欧洲女性考古学家在沙漠帐篷中用放大镜仔细检查古代陶片，阳光普照的挖掘现场人像，沙金和赤陶色调",
  "Portrait/053-young-couple-ballroom-dancers-practice-hall.png": "欧洲年轻男女舞者在练习厅里跳交谊舞，镜面墙壁，优雅的华尔兹姿势，正式礼服，舞伴人像，温暖的反射光线",
  "Portrait/054-woman-tea-master-traditional-ceremony.png": "欧洲女性茶艺师在极简房间里进行传统茶道，陶壶升起蒸汽，冥想般的宁静，文化人像，柔和绿色和奶油色调",
  "Urban/018-shipping-container-vertical-city-fog.png": "由数千个堆叠集装箱改造而成的垂直城市，外挂楼梯和空中花园，工业时尚的城市生活，雾气在集装箱之间的走廊中穿行，电影级广角镜头",
  "Urban/019-tokyo-intersection-rainy-3am-neon.png": "凌晨3点的东京十字路口，雨后空旷的街道，水洼中倒映着一辆出租车，霓虹招牌映在湿润的柏油路上，忧郁的城市孤独感，忧郁的蓝橙色调",
  "Urban/020-abandoned-subway-underground-art-gallery.png": "废弃地铁站改造成地下艺术画廊，瓷砖墙上的涂鸦壁画，流浪猫在长椅上慵懒地躺着，闪烁的荧光灯，氛围感十足的城市衰败摄影",
  "Urban/021-floating-market-river-asian-city.png": "河流穿行于密集的亚洲城市，河上漂浮着满载蔬菜和鲜花的小船，灯笼挂在桥拱下，晨雾弥漫，温暖的金色光线，纪录片风格",
  "Urban/354-rooftop-basketball-brooklyn-sunset.png": "布鲁克林屋顶篮球场，涂鸦覆盖的墙壁，曼哈顿天际线上的日落，少年们在打球，黄金时刻的温暖光线，都市青年文化纪录片人像",
  "Urban/022-taipei-night-market-steaming-stalls.png": "台北夜市，食物摊位升起蒸汽，红灯笼，拥挤狭窄的街道，摊主吆喝，霓虹店招倒映在潮湿地面，充满活力的都市气息，街头摄影",
  "Urban/356-medieval-alley-electric-scooters-cafe.png": "欧洲古城小巷，中世纪石拱门，现代电动滑板车停靠在古老墙壁旁，串灯咖啡馆，雨后湿润的鹅卵石路面，新旧城市生活的融合",
  "Urban/023-coastal-city-turquoise-ocean-beach-boulevard.png": "海滨城市航拍视角，碧绿海水与白色沙滩相接，棕榈树成荫的林荫大道，低矮的度假建筑，晨光在水面闪烁，度假天堂都市风景摄影",
  "Urban/358-berlin-wall-murals-autumn-tourists.png": "柏林墙残垣覆盖着壁画，游客拍照，地面铺满秋叶，灰色天空，历史都市遗迹与现代城市生活相遇，广角纪录片风格",
  "Urban/359-venice-canal-dawn-water-taxi-fog.png": "威尼斯运河黎明时分，水上出租车卸载农产品，晨雾将建筑融入水面，贡多拉船夫准备船只，文艺复兴建筑与日常都市物流相遇，柔和粉彩光线",
  "Urban/360-ny-fire-escape-plants-laundry-chat.png": "纽约消防逃生梯上摆着盆栽和晾晒的衣物，邻居隔着窗户聊天，猫儿趴在栏杆上，温暖的午后阳光，亲密的都市公寓生活纪录片",
  "Urban/361-underground-utility-tunnel-city-pipes.png": "大城市地下的公用隧道，巨大的管道和电缆，头戴安全灯的工人，应急照明灯带，令人窒息的工业都市基础设施摄影",
  "Urban/024-mumbai-commuter-train-rush-hour-rain.png": "孟买高峰时段的通勤列车，人们挂在车门和车窗上，车厢内拥挤不堪，季风暴雨透过敞开的车窗吹入，戏剧性的都市交通纪录片，动态模糊效果",
  "Urban/363-urban-greenhouse-demolished-lot-farming.png": "拆迁空地上的都市温室，回收容器里种植着蔬菜，社区志愿者浇水，背景是公寓楼，草根都市农业项目，明亮的午后光线",
  "Urban/025-ginza-rain-soaked-night-umbrella-woman.png": "雨夜浸透的银座街区，奢侈品橱窗昏暗，一位女子撑伞独行，抛光路面上的倒影，精致的都市忧郁，黑色电影摄影风格",
  "Urban/026-roman-aqueduct-modern-city-cars-cafes.png": "古罗马水道桥穿行于现代地中海城市，汽车驶过石拱之下，咖啡馆开在拱门洞内，两千年的基础设施服务当代都市生活，温暖日落",
  "Urban/027-shanghai-bund-foggy-dawn-jogger.png": "薄雾黎明中的上海外滩，殖民建筑在升腾的雾气中剪影，一名孤独的晨跑者，浦东塔楼在雾中若隐若现，充满氛围的都市过渡时刻",
  "Urban/036-street-saxophonist-railway-bridge-pigeons.png": "铁路桥下的街头萨克斯乐手，鸽子聚集周围，上班族匆匆而过不曾停留，孤独的都市表演者纪录片，忧郁的 sepia 色调",
  "Urban/028-vertical-slum-hillside-improvised-housing.png": "山坡上建造的垂直贫民窟，色彩斑斓的临时住房堆叠数十层，电缆和软管在楼层间纠缠，屋顶上的卫星天线，极端都市密度纪录片广角镜头",
  "Urban/029-chinatown-gate-dusk-red-lanterns-cards.png": "黄昏时的唐人街牌坊，红灯笼亮起，面馆蒸汽升腾，老人在人行道上打牌，多元文化都市社区夜晚场景，温暖的琥珀色灯光",
  "Urban/030-rooftop-infinity-pool-city-skyline-dawn.png": "豪华屋顶无边泳池俯瞰现代城市天际线，黎明的冷蓝色晨光，水面倒映塔楼剪影，优雅的都市生活方式建筑摄影",
  "Urban/371-london-taxi-westminster-bridge-rain.png": "伦敦黑色出租车堵在威斯敏斯特桥上，身后是大本钟和议会大厦，雨水落在挡风玻璃上，司机查看手机，标志性的都市拥堵纪录片，阴沉灰色光线",
  "Urban/372-shipping-container-village-waterfront-rainbow.png": "城市滨水区的回收集装箱村落，彩虹色集装箱，单元之间是社区花园，孩子们玩耍，富有创意的草根都市更新项目，明亮欢快的午后",
  "Urban/037-paris-cafe-terrace-autumn-espresso-leaves.png": "秋日巴黎咖啡馆露台，侍者端着浓缩咖啡托盘，鹅卵石地面上的落叶，衣着时尚的顾客，经典欧洲都市咖啡馆文化，温暖金棕色调",
  "Urban/374-concrete-skatepark-highway-overpass-graffiti.png": "高速公路立交桥下混凝土滑板公园，桥柱上的涂鸦艺术，滑板者做动作，午后光线从缝隙中洒下，原始都市青年娱乐空间，充满活力的纪录片风格",
  "Urban/031-circular-roundabout-flowing-cars-autumn-park.png": "环形环岛车流如液体般流动，周围公园树木呈同心圆环，金黄秋叶，几何城市规划摄影，鸟瞰视角，温暖琥珀色调",
  "Urban/376-warehouse-vertical-climbing-gym-rusted-beams.png": "废弃工业仓库改造成垂直攀岩馆，彩色绳索和岩点固定在生锈钢梁上，年轻攀岩者向上攀登，衰败与活力的戏剧性对比，都市改造摄影",
  "Urban/032-highway-interchange-five-levels-dusk-streaming.png": "黄昏时分的多层高速公路互通，五层弯曲立交桥交织如混凝土折纸，车灯如发光血管般流动，宏大尺度与复杂性，工程景观摄影",
  "Urban/033-zen-courtyard-stone-lantern-moss-bamboo.png": "小小禅意庭院花园，石灯笼、微型竹林、覆苔踏脚石、冥想用水钵，被现代混凝土墙环绕，宁静的都市庇护所摄影，柔和晨光",
  "Urban/379-smart-city-holographic-bus-stops-data-streams.png": "未来智慧城市街区夜景，建筑外墙上投影着发光数据流，全息公交站，人们穿行在发光走廊中，赛博都市生活摄影，蓝绿与洋红调色",
  "Urban/380-yellow-tram-modern-glass-boulevard-morning.png": "经典欧洲电车穿行于现代玻璃钢铁大道，复古黄色电车与流线型当代建筑形成对比，早晨通勤场景，时间碰撞的都市摄影",
  "Urban/381-vertical-community-garden-20-story-balcony.png": "20层公寓阳台的垂直社区菜园，每层种植不同蔬菜和花卉，悬挂花箱、浇水系统，翠绿植物沿混凝土立面倾泻而下，可持续城市摄影",
  "Urban/382-outdoor-escalator-hillside-murals-flowers.png": "户外扶梯系统沿陡峭山坡社区攀升，人们乘坐扶梯穿越彩色壁画和层层花箱，地中海山城，都市基础设施摄影，温暖赭石色调",
  "Urban/383-frozen-fountain-winter-square-ice-crystals.png": "冬日城市广场中结冰的喷泉，冰晶在石质盆沿上形成精巧的自然雕塑，积雪覆盖的长椅，一把红伞路过，诗意冬季都市摄影",
  "Urban/384-food-truck-rally-highway-overpass-neon-steam.png": "高架桥下夜晚餐车集会，彩色餐车霓虹招牌，烤架升起蒸汽，人们围坐野餐桌，串灯在混凝土上方营造温暖天篷，都市美食摄影",
  "Urban/034-old-bookstore-corner-surrounded-by-high-rises.png": "街角幸存的一家旧书店，被闪闪发亮的新高层包围，温暖室内灯光透过积尘窗户溢出，可见书堆，对城市开发的抵抗，怀旧城市摄影",
  "Urban/386-skybridge-glass-tunnel-rain-avenue-below.png": "连接两座玻璃塔的高空步行天桥，人们穿行在繁忙大道上方的透明隧道中，下方街道下雨而隧道内干爽，漂浮的都市通道摄影",
  "Urban/035-transit-hub-thousands-commuters-umbrellas-dawn.png": "亚洲巨型城市交通枢纽的雨后黎明，成千上万的通勤者通过弧形混凝土屋顶下的闸机，雨伞如花朵般绽开，有序的混乱，都市晨间节奏摄影，柔和大地色调",
  "Fantasy/388-dream-dimension-tea-house-abyss.png": "梦境边缘的悬浮茶馆，丝线悬于无尽深渊之上，半透明灵体从瓷杯中品茶，薄雾穿过敞开的窗户卷入，温暖琥珀色灯笼光，超现实奇幻概念艺术，高度细节",
  "Fantasy/389-clockwork-angel-glass-body-brass-gears.png": "玻璃身体内显露滴答作响黄铜齿轮的发条天使，机械翅膀折叠于大教堂墙壁旁，水晶肌肤折射烛光，蒸汽朋克神灵概念艺术，精密机械细节，温暖金属色调",
  "Fantasy/024-mushroom-forest-house-fairies-snails.png": "巨型生物发光蘑菇森林，高耸真菌作为房屋，微小仙女骑着花园蜗牛沿菌丝公路行进，发光孢子如雪飘浮，奇趣暗奇幻，精密微缩世界，冷蓝绿光",
  "Fantasy/391-forgotten-god-sleeping-subway-tunnel.png": "被遗忘的古神沉睡在废弃地铁隧道中，苔藓藤蔓覆盖巨大石面，现代通勤者走过毫无察觉神灵就在身边，都市神话混搭，神圣与日常的对比，昏暗荧光灯光",
  "Fantasy/025-library-books-growing-trees-ink-streams.png": "魔法图书馆中书籍如树从石地生长，书页在空灵风中翻飞，墨水如溪流在书架间流淌，树皮封面上发光符文，知识成为活生态系，温暖琥珀光，奇幻概念艺术",
  "Fantasy/393-ghost-caravan-desert-trading-memories.png": "幽灵商队穿越星光沙漠，半透明灵驼背负装瓶记忆的晶罐，幽灵商人用怀旧交换遗忘的梦，银色月光洒在沙上，超现实奇幻，电影感广角",
  "Fantasy/394-underwater-moon-goddess-temple-jellyfish.png": "月女神水下神殿，银色月光透过珊瑚覆盖的柱间渗入，祭司身穿飘逸海丝长袍，生物发光水母充当活灯笼，深海神话，冷青银色调",
  "Fantasy/395-witch-kitchen-self-chopping-cauldron-opera.png": "女巫厨房中蔬菜自行飞切悬浮空中，坩埚冒着泡哼着歌剧旋律，黑猫从浮空羊皮纸读食谱，面粉在天花板拼出符文圆圈，奇趣暗喜剧奇幻，温暖烛光内景",
  "Fantasy/026-giant-snail-carrying-medieval-village.png": "巨蜗牛壳上驮着中世纪村庄，微型骑士巡逻螺旋街道，小旗帜从塔顶飘扬，荒诞奇幻概念艺术，精密微缩建筑，田园风景背景，奇趣尺度对比",
  "Fantasy/397-cloud-city-inside-thunderstorm-lightning-harvest.png": "永恒雷暴之眼内建造的云城，铜塔尖收集闪电作为能源，市民穿防静电长袍走过雾桥，电光建筑泛紫光，戏剧性风暴奇幻概念艺术",
  "Fantasy/027-walking-castle-migrating-lava-plain-legs.png": "行走城堡以巨石腿穿越火山熔岩平原迁徙，村民安于厚重城墙内，烟囱炊烟与火山灰交融，游牧堡垒奇幻概念艺术，史诗尺度，戏剧性红橙光",
  "Fantasy/028-origami-dragon-unfolding-paper-crane-metamorphosis.png": "折纸龙从孩童纸鹤中自我展开，平坦纸纹蜕变为活彩虹色鳞片，魔法变形被捕捉于半途中，半纸半活生物，温暖影棚光，创意奇幻概念艺术",
  "Fantasy/029-fairy-garden-rusted-cars-post-apocalyptic.png": "末日后童话花园从锈蚀车骸中绽放，魔法野花穿过碎裂挡风玻璃，小精灵在残破交通灯中筑巢，自然以魔法收回衰败，奇幻遇都市废墟，柔粉与锈色调",
  "Fantasy/401-mirror-dimension-reversed-gravity-trees-downward.png": "镜像维度天在脚下树向下生长，映像过着独立生活，重力颠倒，超现实奇幻风景，不可能的建筑，埃舍尔灵感，冷银紫色调",
  "Fantasy/030-goblin-bazaar-dragon-egg-auction-underground.png": "地精地下集市拍卖龙蛋于天鹅绒展台，戴礼帽的暗商人，发光龙蛋脉动内焰，晶灯照亮岩洞，奇幻商市与阴谋，温暖琥珀金色调，精密人群场景",
  "Fantasy/403-bamboo-forest-sleeping-monk-stalks-meditation.png": "超现实竹林中竹竿本身已化为石化僧侣，每根垂直绿竹都显现出冥想僧侣的雕刻面容、合十双手与衣褶，苔藓覆盖树皮般的肌肤，薄雾在人行竹柱间飘移，奇幻恐怖概念艺术，宁静却诡异的氛围，柔绿灰色调",
  "Fantasy/404-space-whale-nursing-calf-asteroid-nebula.png": "宇宙太空鲸在两条小行星带间哺育幼崽，生物发光奶云流入星云溪流，母性深空神话，星空背景，生物概念艺术，温柔紫金宇宙光",
  "Fantasy/405-ghost-seamstress-stitching-moonlight-gowns.png": "维多利亚幽灵裁缝用捕获的月光缝制裙袍，银色丝线与半透明面料，幽灵之手在织机编织，月辉面料闪烁，空灵工坊奇幻，冷蓝银色调，精密织物纹理",
  "Fantasy/031-chess-kingdom-pawns-rebel-marble-battlefield.png": "活棋盘王国中兵卒起义反抗国王，微型士兵在棋子王国大战场上行进，小小战旗飘扬，政治奇幻讽刺，宏观视角展示棋子面部，温暖戏剧性灯光",
  "Fantasy/407-lighthouse-edge-reality-dimension-beam.png": "现实边缘灯塔，守灯人投射光束照亮下方海中不同世界，每圈涟漪展现不同维度，维度守卫奇幻，宇宙地平线，戏剧性青金光",
  "Fantasy/408-library-silence-physical-form-crystal.png": "浩瀚图书馆中寂静已化为漂浮的半透明水晶形态，穿隔音丝绒长袍的图书管理员在玻璃罐中捕捉低语，柔和尘埃悬浮在琥珀色光中，超现实奇幻概念艺术，宁静神秘氛围",
  "Fantasy/032-desert-city-giant-turtle-sand-dunes.png": "沙漠城市建造在巨型海龟壳上，海龟缓缓穿行于沙丘而非水中，背上有尖塔与圆顶，沙浪在其古老四肢周围分开，游牧奇幻建筑，温暖金色时光",
  "Fantasy/033-post-office-dead-ghost-letters-skeletal-clerks.png": "暮光领域中的亡灵邮局，骷髅职员将半透明幽灵信件分拣到标有来世目的地的信箱，邮票泛着空灵墨水微光，阴郁却官僚的氛围，带冷幽默的黑暗奇幻",
  "Fantasy/034-garden-eyeball-flowers-watching-viewer.png": "巨型花朵其实是茎上眼球的花园，每朵花用不同颜色虹膜注视观者，花瓣上露珠如泪，超现实恐怖奇幻，不安的植物场景，柔和阴天光",
  "Fantasy/412-volcano-forge-emotions-into-weapons.png": "活火山内部的铁匠铺，铁匠将原始情感锻造成武器，发光铁砧将愤怒塑成剑、悲伤塑成盾，情感结晶时火花四溅，戏剧性橙红工业奇幻",
  "Fantasy/036-bone-cathedral-ribcage-arches-skulls.png": "完全由骨骼建造的大教堂，胸腔肋骨拱支撑天花板，头骨嵌入柱中，彩色玻璃窗由有色薄膜制成，庄严而阴森的神圣奇幻，冷调柔和光线",
  "Fantasy/414-cloud-market-bottled-weather-storm-jars.png": "漂浮云市场，商人售卖瓶装天气，玻璃罐装着微型风暴、阳光小瓶和雾罐，顾客在棉花摊位间浏览，奇趣天空集市奇幻，柔和粉彩光",
  "Fantasy/415-forest-detached-shadows-dancing-owners.png": "一片影子从主人身上脱离并独立生活的森林，影子生物在 abandoned 靴子与斗篷周围起舞，前主人凝固为白色剪影，诡异却 playful 的奇幻，高对比光线",
  "Fantasy/416-underwater-ballroom-fish-tail-aristocrats-algae.png": "水下舞厅中，身穿巴洛克礼服、鱼尾的贵族在生物发光藻类吊灯下跳华尔兹，珊瑚柱、气泡帘，优雅深海奇幻，冷蓝绿光配金色点缀",
  "Fantasy/417-prison-forgotten-gods-divine-cells.png": "被遗忘神灵的监狱，每个牢房关押着一位逐渐消逝的神明，守卫穿着锚定现实的盔甲，神圣光芒从铁栅门泄漏，宇宙监狱奇幻，戏剧性明暗光线",
  "Fantasy/418-robot-forest-spirit-tea-ceremony.png": "生锈机器人与古老森林精灵之间的茶道，陶瓷杯中混合油与露水，苔藓覆盖金属关节，樱花在两者之间飘落，科技与自然和谐奇幻，温暖柔光",
  "Fantasy/037-mountain-range-sleeping-titan-towns-ridge.png": "山脉其实是沉睡的泰坦，城镇沿其脊背而建，山谷由其疤痕形成，瀑布从它沉睡的口中倾泻，史诗级活景观奇幻，鸟瞰视角，金色日出",
  "Fantasy/420-bakery-bread-memories-kneaded-dough.png": "一家面包店，面团中揉入记忆使面包膨胀，新鲜面包的蒸汽中展现过往场景，老面包师塑形时记忆在上方飘浮，怀旧魔幻现实主义奇幻，温暖金色内景",
  "Fantasy/421-clock-tower-different-season-each-hour.png": "一座钟楼，每个小时显示不同季节，正午是开花春季，午夜是飘雪冬季，季节绘于钟面，时间以天气形式可视化，超现实时间奇幻，混合季节光线",
  "Fantasy/038-carnival-extinct-animals-carousel-mammoth.png": "灭绝动物嘉年华，长毛猛犸象在旋转木马上，渡渡鸟在碰碰车里，剑齿虎在杂耍摊，黄昏时分的史前游乐场，怀旧而苦乐参半的奇幻，温暖串灯与暮色天空",
  "Fantasy/423-observatory-telescopes-inward-body-universe.png": "一座天文台，望远镜向内而非向外，揭示人体内的星系与星云，内部宇宙解剖学，学者在沉睡主体旁记录，超现实内省奇幻，深色背景配体内星光",
  "Fantasy/424-monster-symphony-orchestra-werewolf-dragon.png": "怪物交响乐团，狼人拉大提琴、塞壬任指挥、巨龙吹铜管、克拉肯打打击乐，带漂浮包厢的不可能音乐厅，宏大哥特音乐奇幻，戏剧性舞台灯光",
  "Still Life/024-chess-set-food-pieces-bread-cheese-wine.png": "超现实静物画，棋盘上每枚棋子都由食物构成，主教是硬壳面包雕刻而成，骑士由陈年切达干酪塑形，城堡是葡萄酒瓶，国王是多层婚礼蛋糕，摆放在大理石棋盘上，戏剧性侧光，写实食物艺术摄影，暖色调",
  "Still Life/025-vanity-table-natural-elements-moss-berries-dew.png": "超现实静物画，古董梳妆台上的化妆品被自然元素取代，粉底是一块绿苔藓，口红是黄铜管中的碎浆果，香水是叶子上汇聚的晨露，粉饼镜框绕着细小藤蔓，柔和窗光，写实丰富质感",
  "Still Life/026-desk-every-object-glass-book-pen-candle.png": "极简静物画，书桌上每件物品都由透明玻璃制成，一本有玻璃页的玻璃书，一支蘸着液态玻璃墨水的玻璃笔，一支冻结着玻璃火焰的玻璃蜡烛，全部放置在黑色反光面上，戏剧性背光，写实工作室摄影，冷蓝色调",
  "Still Life/027-time-traveler-pocket-contents-coin-key-watch-phone.png": "静物画，时间旅行者口袋中的物品排列在老旧木板上，一枚罗马硬币，一把中世纪铁钥匙，一块维多利亚银怀表，一部现代智能手机，以及一块来自未来的神秘发光半透明圆盘，戏剧性聚光灯，写实产品摄影，冷暖对比",
  "Still Life/028-breakfast-precious-stones-amber-pearl-obsidian.png": "超现实静物画，早餐桌上所有食物都变成了宝石，金琥珀色的吐司片，珍珠蛋黄的煎蛋，水晶杯中的液态黑曜石咖啡，一块玉石般的黄油，晨光透过窗户照入，写实丰富反射，温暖金色调",
  "Still Life/029-teacups-tiny-weather-systems-thunderstorm-fog-rainbow.png": "奇幻静物画，三个瓷茶杯各含不同的微型天气系统，一杯中有微缩雷暴与闪电，一杯中有金色翻滚的雾气，一杯中有薄雾上的小彩虹，排列在蕾丝桌布上，柔和漫射光，写实微距摄影，粉彩色调",
  "Still Life/431-musical-instruments-growing-plants-violin-ivy-trumpet-daisies.png": "超现实静物画，乐器开始生长植物，小提琴通过f孔萌发常春藤，小号喇叭口绽放雏菊，旧鼓皮上生长苔藓，置于木地板舞台上，温暖聚光灯，写实有机质感，绿铜色调",
  "Still Life/432-mechanic-tools-fossilized-stone-granite-marble.png": "超现实静物画， mechanic 工作台上每件工具都化石化为石头，花岗岩扳手，白色大理石螺丝刀，砂岩螺母和螺栓，全部放在风化木工作台上，光束中飘浮尘埃，写实粗糙石质纹理，泥土色调",
  "Still Life/030-perfume-bottles-captured-landscapes-desert-forest-ocean.png": "超现实静物画，香水瓶中每个玻璃瓶都装着一片被捕获的风景，一瓶有微缩沙丘和微小太阳，一瓶有微缩冰冻森林，一瓶有翻涌海浪，一瓶有夜晚发光城市，排列在镜面上，戏剧性灯光，写实产品摄影，多彩色调",
  "Still Life/031-objects-submerged-honey-golden-refraction-watch-key-rose.png": "静物画，物品半浸入蜂蜜中放在粗犷木桌上，黄铜怀表、华丽钥匙和红玫瑰都部分浸在金色蜂蜜中，浓稠蜂蜜滴落并折射光线，温暖琥珀色背光，写实微距摄影，浓郁金色调",
  "Still Life/435-writer-desk-floating-3d-ink-letters-words.png": "超现实静物画，作家书桌上的墨水活了过来，三维光泽黑色字母漂浮在手写页面上方，文字如雕塑般悬浮空中，钢笔墨水仍在向上流淌，单一光源照射暗色木桌，写实光泽反射，单色配金色点缀",
  "Still Life/032-keys-impossible-materials-smoke-ice-light-shadow.png": "超现实静物画，不可能材质的钥匙排列在深色天鹅绒上，一把烟雾旋转的钥匙，一把水晶般透明的冰钥匙，一把纯白光的钥匙，一把固态影子的钥匙，一把粉石英钥匙，各自微微发光，戏剧性低调光，写实工作室摄影，深色阴郁背景",
  "Still Life/033-photo-frames-pressed-flowers-matching-silhouettes.png": "怀旧静物画，复古相框中的照片被压花取代并匹配原始剪影，人像形状填满雏菊，站立人影以蕨类勾勒，合影形状填满薰衣草，排列在做旧木桌上，柔和自然光，写实细腻质感，温暖柔和色调",
  "Still Life/034-alchemist-shelf-impossible-substances-moonlight-sunset.png": "超现实静物画，炼金术士木架上的药剂瓶装着不可能的物质，一瓶发银光的液态月光，一瓶固化为灰色水晶的回声，一瓶渐变橙紫色的瓶装日落，一瓶凝结为白霜的低语，戏剧性烛光，写实奇幻静物，温暖神秘色调",
  "Still Life/439-emotion-tools-hammer-anger-brush-joy-scalpel-sorrow.png": "概念静物画，抽象情感的工具排列在暗色桌上，红热发光锤头的愤怒，彩虹色鬃毛画笔的喜悦，泪滴形刀片手术刀的悲伤，星形指针指南针的希望，戏剧性聚光灯配深影，写实产品摄影，浓郁饱和色彩",
  "Still Life/035-timekeeping-devices-different-eras-sundial-hourglass-atomic.png": "静物画，不同时代的计时设备各自停在不同时刻，青铜日晷、陶水钟、沙子悬停的玻璃沙漏、银怀表、数字原子钟，全部排列在深色石板桌上，戏剧性侧光，写实金属反射，冷暖对比",
  "Still Life/036-butterfly-collection-half-alive-flying-color-trails.png": "超现实静物画，蝴蝶标本收藏中部分复活，玻璃柜中钉着的蝴蝶旁有飞走的个体留下彩色粉末轨迹，展示柜中一些空针，柔和博物馆灯光配尘埃粒子，写实微距摄影，鲜艳色彩映衬深色背景",
  "Still Life/037-future-vanity-table-holographic-beauty-tools-chrome.png": "未来静物画，3000年的梳妆台上摆放着尚未发明的美容工具，发光球体护肤仪，粒子喷雾器，光棱镜眼部增强器，全息镜子，全部铬与玻璃材质配蓝色全息点缀，戏剧性工作室灯光，写实科幻产品摄影，冷蓝银色调",
  "Still Life/443-food-crystallized-geodes-bread-amethyst-apple-quartz.png": "超现实静物画，食物结晶成晶洞，裂开的面包露出内部紫色紫水晶，切开的苹果显示透明石英，破碎的酒瓶内部晶洞闪烁，置于深色石面上，戏剧性背光，写实水晶反射，紫金色调",
  "Still Life/038-magician-top-hat-spilling-stars-water-cards-lightning.png": "超现实静物画，魔术师礼帽侧翻倒下，不可能的物体溢出，一只由闪烁星辰构成的兔子，流动的水做成的扑克牌，噼啪作响的小闪电魔杖，一枚液态金币，置于深色天鹅绒布上，戏剧性聚光灯，写实奇幻静物，神奇发光色调",
  "Still Life/445-letters-floating-scripts-latin-arabic-chinese-gothic.png": "静物画，不同世纪的手写信件排列在古董桌上，每封信的墨水以原始文字浮于纸面上方，拉丁书法、阿拉伯文、中文毛笔字、哥特黑体字，全部以光泽三维文字悬浮，温暖灯光，写实纸质纹理，温暖棕褐色调",
  "Still Life/039-compasses-pointing-impossible-directions-spinning-upward.png": "超现实静物画，古董指南针排列在黄铜桌上，每个指向不可能的方向，一个飞速旋转，一个笔直向上指，一个发蓝光，一个直指观者，一个用小星星代替指针，戏剧性暖光配反射，写实产品摄影，黄铜金色调",
  "Still Life/040-picnic-interrupted-nature-ants-crystal-vines-butterflies.png": "超现实静物画，野餐被自然打断，微小蚂蚁搬运水晶杯，绿色藤蔓穿过柳条篮生长，蝴蝶偷走银叉，小鸟在瓷盘上筑巢，散落的水果变成花朵，树间斑驳阳光，写实生动细节，温暖绿金色调",
  "Still Life/041-potion-workbench-vials-colored-liquids-smoke-glitter-fish.png": "奇幻静物画，药剂师工作台上有彩色液体小瓶，一瓶冒紫色烟雾，一瓶装金色闪粉，一瓶有游动的微型霓虹鱼，一瓶有飘浮花瓣，一瓶有旋转银河图案，玻璃管和铜线圈，温暖烛光，写实奇幻产品摄影，浓郁宝石色调",
  "Still Life/042-vintage-cameras-lenses-eyes-reflecting-scenes.png": "超现实静物画，复古相机的镜头变成了眼睛，每个镜头反射不同场景，一个显出山脉，一个海洋，一个茂密森林，一个城市天际线，排列在深色木架上，戏剧性聚光灯，写实玻璃反射，暖棕与冷蓝对比",
  "Still Life/043-masks-natural-materials-bark-ice-sand-moss-ash.png": "静物画，面具挂在风化石墙上，每个面具由不同自然材质制成，树皮、透明冰、压缩沙、活苔藓、黑色火山灰、白色海盐，侧面戏剧性斜射光，写实丰富表面纹理，泥土自然色调",
  "Still Life/451-chess-board-broken-fallen-pieces-defiant-pawn.png": "戏剧性静物画，棋盘对弈中倒下的棋子破碎在桌上，骑士长矛折断，主教权杖裂开，皇后倒下冠冕脱落，而一个木制小兵桀骜地直立着，戏剧性低角度灯光配深影，写实木石纹理，深色戏剧性色调",
  "Still Life/044-apothecary-herbs-color-gradient-purple-gold-arrangement.png": "静物画，药剂师桌上干草药和药物按完美色彩渐变排列，从左侧深紫色薰衣草经蓝色矢车菊、绿色鼠尾草、黄色姜黄到右侧淡金色洋甘菊，玻璃瓶和石臼杵，柔和自然窗光，写实植物细节，温暖自然色调",
  "Still Life/045-modern-objects-trapped-amber-smartphone-key-coin-watch.png": "超现实静物画，现代物品困在巨大金色琥珀块中，智能手机、黄铜钥匙、银币、数字手表，全部冻结在半透明琥珀内，置于深色天鹅绒布上，温暖光线穿透琥珀，写实金色折射与反射，浓郁琥珀与深色调",
  "Nature/045-crystal-forest-trees-light-refracting-prism.png": "超现实森林，每棵树都由半透明水晶构成，阳光穿过水晶枝干在地面折射出彩虹棱镜光斑，水晶树叶在微风中叮当作响，写实风景摄影，空灵氛围，冷蓝与彩虹色调",
  "Nature/046-ocean-waves-frozen-mid-motion-sculpture.png": "超现实海景，海浪在运动中被冻结为固态透明冰雕，水晶般的浪花悬停在海滩上方，阳光透过冰冻水面发光，写实风景摄影，戏剧性而不可思议，蓝白色调",
  "Nature/047-desert-dunes-crushed-gemstones-rainbow-colors.png": "沙漠沙丘由碎宝石构成呈现彩虹色彩，红宝石红丘旁是蓝宝石蓝丘，祖母绿山谷介于紫水晶山脊之间，在晴空下闪烁，写实风景摄影，鲜艳饱和色彩",
  "Nature/048-mountain-peaks-bioluminescence-glowing-night.png": "夜间山脉岩石山峰发出天然生物荧光的蓝绿光芒，发光矿物脉络贯穿岩石，下方镜面湖反射发光山峰，上方星空，写实风景摄影，神秘氛围，深蓝绿光芒",
  "Nature/049-meadow-flowers-geometric-patterns-spirals.png": "野花草甸中花朵以不可能的完美几何图案绽放，不同颜色花朵的同心螺旋，自然中的数学精度，花瓣的分形排列，柔和晨光，写实微距风景，鲜艳自然色彩配空灵质感",
  "Nature/050-river-flowing-upward-defying-gravity-sky.png": "超现实风景，河流逆重力向上流淌，水以扭曲丝带状向天空倾泻，水滴如反向雨般上升，两岸翠绿，上方戏剧性云层，写实风景摄影，不可能的物理，蓝绿色调",
  "Nature/051-glacier-transparent-glass-ancient-landscape-inside.png": "巨大冰川完全透明如玻璃，内部揭示古老冰冻景观，史前树木和冰冻湖泊透过清澈冰壁可见，阳光深入穿透，写实风景摄影，冷蓝与水晶清澈色调",
  "Nature/052-canyon-walls-layered-amethyst-agate-crystal.png": "壮丽峡谷岩壁由层叠紫水晶和玛瑙构成，紫色和橙色水晶带条纹悬崖，底部细河捕捉彩色反射，金色时光光线，写实风景摄影，浓郁紫色与温暖橙色调",
  "Nature/053-cloud-forest-clouds-rooted-trees-growing-cotton.png": "神秘云雾林中云朵在树上扎根，白色云团如棉花般从枝条生长，雾气植被攀附树干，柔和漫射光透过白色树冠，写实风景摄影，空灵白色与绿色调",
  "Nature/054-volcanic-lava-cooled-obsidian-animal-sculptures.png": "火山景观中熔岩冷却成光泽黑曜石，自然雕塑成动物形态，奔跑的狼、翱翔的鹰、休息的狮子都凝固在火山玻璃中，附近活跃喷气孔冒出蒸汽，写实风景摄影，黑色与橙色调",
  "Nature/055-tundra-permafrost-crystallized-diamond-formations.png": "北极苔原永久冻土结晶成钻石般形态，闪耀透明晶体如草般从冻土生长，北极光在晶体表面反射，写实风景摄影，寒冷纯净，白色与绿色调",
  "Nature/056-mangrove-swamp-roots-bioluminescent-blue-glow.png": "红树林沼泽在暮色中水下根部发出生物荧光蓝光，形成水下发光线条网络，平静暗水反射蓝色光芒，上方鸟类剪影，写实风景摄影，神秘氛围，深蓝与黑色调",
  "Nature/057-waterfall-slow-motion-droplets-jewels-suspended.png": "壮丽瀑布以极慢动作捕捉，每滴水珠如钻石般悬停在空中，阳光穿过个体水滴折射出微型彩虹，葱郁热带悬崖，写实高速摄影，蓝色与绿色配棱镜高光",
  "Nature/058-bamboo-forest-rainbow-colors-each-stalk-different.png": "高耸竹林中每根竹竿是彩虹不同颜色，红橙黄绿蓝靛紫竹竿直指天空，柔和阳光透过彩色树冠，写实风景摄影，鲜艳而宁静，全光谱色彩",
  "Nature/468-salt-flat-reflects-alternate-landscape-not-sky.png": "广袤盐滩反射的不是上方天空而是不可能的异世景观，显示现实中不存在的山脉和森林，白色盐壳如另一个世界的镜子，孤独身影站在边缘，写实风景摄影，超现实而神秘，白色与反射色彩",
  "Nature/059-geothermal-mineral-pools-perfect-color-wheel.png": "地热区矿物温泉从上空看形成完美色轮，蒸腾水池按彩虹渐变排列，从红硫磺经橙铁、黄硫磺、绿铜、蓝硫酸铜到紫锰，写实航拍风景摄影，鲜艳饱和色彩",
  "Nature/060-forest-leaves-change-color-sound-visual-symphony.png": "魔法森林树叶随声音变色，创造旋转秋色的视觉交响乐，附近瀑布在树冠引起橙红涟漪，鸟鸣创造粉色和金色爆发，写实风景摄影，动态多彩，温暖光谱色调",
  "Nature/061-black-sand-beach-bioluminescent-plankton-glowing-waves.png": "夜间黑色火山沙滩上拍岸海浪发出璀璨蓝色生物荧光浮游生物光芒，每道浪在暗沙上留下蓝色光迹，上方星空与发光海岸相映，写实风景摄影，戏剧性对比，黑色与电蓝色调",
  "Nature/472-circular-mountain-lake-reflects-different-sky.png": "完美圆形高山湖泊反射出与上方完全不同的天空，显示有双月的紫色异星日落而实际天空晴朗蔚蓝，岩石山脉环绕湖泊，写实风景摄影，超现实而令人不安，上方蓝色下方紫色",
  "Nature/062-savanna-copper-wire-grass-hums-wind.png": "非洲稀树草原的草由细铜线制成在风中嗡鸣，金色铜丝如波浪般在平原上起伏，金合欢树有铜叶，温暖夕阳照亮金属草丛，写实风景摄影，温暖铜金色调",
  "Nature/474-iceberg-floating-upside-down-pointed-bottom-sky.png": "巨大冰山倒置漂浮在平静极地海中，尖端底部朝上指向天空，平坦顶部浸入水下，清澈冰有蓝色纹路，戏剧性极地天空，写实风景摄影，超现实而不可能，蓝白色调",
  "Nature/063-field-giant-crystals-growing-like-wheat-glowing.png": "广袤田野中巨大半透明晶体如麦秆般从大地生长，六英尺高的发光石英和紫水晶以内在光芒闪烁，在风中轻柔摇摆，紫色暮色天空下远处山脉，写实风景摄影，空灵而壮丽，紫色与水晶色调",
  "Abstract/042-sound-waves-visible-ripples-liquid-color-frequencies.png": "声音波抽象可视化，暗色液体表面的涟漪，不同频率以不同颜色的同心圆向外辐射，低频为大型红色波浪，高频为微小蓝色涟漪，写实微距摄影配戏剧性灯光，深色与鲜艳色调",
  "Abstract/043-black-hole-liquid-ink-pulling-colorful-light-streams.png": "黑洞抽象艺术，旋转液态墨构成的黑洞拉入彩色光流，引力透镜扭曲周围空间，恒星在事件视界周围弯曲，鲜艳色彩被黑暗吞噬，写实数字艺术，戏剧性宇宙氛围",
  "Abstract/044-magnetic-field-lines-glowing-golden-threads-sculpture.png": "磁场线抽象可视化，发光金色丝线穿过暗色空间编织，形成曲线和螺旋的隐形雕塑，铁屑排列成完美图案，戏剧性工作室灯光，写实微距摄影，黑金色调",
  "Abstract/045-time-visualized-transparent-film-layers-amber-gradient.png": "时间抽象概念，以透明琥珀色薄膜层可视化，每层显示不同冻结时刻，堆叠形成从淡金到深琥珀的渐变，光线穿过产生复杂干涉图案，写实工作室摄影，温暖金色调",
  "Abstract/046-emotions-topographic-landscape-red-peaks-blue-canyons.png": "情感地形图抽象艺术，愤怒为尖锐锯齿红色山峰，喜悦为平滑金色山谷，悲伤为深蓝峡谷，恐惧为暗紫裂缝，以3D浮雕地图渲染配戏剧性俯瞰灯光，写实3D渲染，鲜明情感色彩",
  "Abstract/047-symphony-flowing-ribbons-color-each-instrument-hue.png": "交响乐抽象可视化，暗色空间中流动的彩色丝带，每件乐器不同色调贯穿构图，弦乐为金色丝绸，铜管为橙色缎面，打击乐为红色天鹅绒，创建精致三维挂毯，写实3D渲染，浓郁宝石色调",
  "Abstract/048-mathematical-equations-3d-sculptures-golden-ratio-fibonacci.png": "数学方程抽象艺术渲染为3D雕塑，黄金比例为发光螺旋，斐波那契数列为递增堆叠立方体，圆周率为同心圆层，欧拉恒等式为相交光平面，暗色背景配戏剧性画廊灯光，写实3D渲染，白金色调",
  "Abstract/049-gravity-waves-distortions-grid-light-points-bending.png": "引力波抽象可视化，完美发光点网格中的扭曲，巨大不可见物体弯曲空间，网格在引力中心周围扭曲拉伸，写实3D渲染配粒子效果，暗色背景配蓝白光点",
  "Abstract/050-memory-fragments-glass-shards-spiral-galaxy-forgotten.png": "记忆碎片抽象艺术，漂浮的玻璃碎片每片反射不同遗忘场景，排列成螺旋星系形态，部分碎片因生动记忆更亮，其他褪为透明，暗色宇宙背景，写实3D渲染，棱镜与深色调",
  "Abstract/051-heat-visible-color-waves-rising-coffee-thermal-volcano.png": "热量抽象可视化，日常物体上升的可见色波，咖啡杯为红橙热能火山，灯泡为蓝色热量塔，冰块为冷蓝虚空，热成像美学但具艺术性，写实3D渲染，暖冷热成像色调",
  "Abstract/052-quantum-probability-clouds-translucent-spheres-overlapping.png": "量子概率抽象可视化，不同颜色半透明球体重叠干涉，波函数渲染为起伏色彩渐变，不确定性为模糊边缘，叠加态为多态同时可见，暗色背景配发光粒子，写实3D渲染，鲜艳霓虹色调",
  "Abstract/053-words-dissolving-abstract-shapes-meaning-energy.png": "不同语言文字溶解为抽象形状的艺术，字母碎裂转化为流动能量，汉字变成水墨山峦，阿拉伯文变成流沙，拉丁字母变成几何光线，暗色背景配发光转化，写实数字艺术，多彩空灵色调",
  "Abstract/054-dreamscape-thoughts-physical-objects-zero-gravity-threads.png": "抽象梦境，思想为零重力中漂浮的实体物，融化成球的时钟，长出羽毛的钥匙，显示另一维度的镜子，全部由精致光丝相连，暗色宇宙背景，写实3D渲染，超现实空灵色调",
  "Abstract/055-echo-visible-sound-rings-bouncing-canyon-mirrors.png": "回声抽象可视化，可见声波环在镜面峡谷中弹跳，每次反射创建新色环，环在传播中倍增并衰减，声音衰减的视觉呈现，戏剧性灯光配彩色光迹，写实3D渲染，反射与鲜艳色调",
  "Abstract/056-colors-bleeding-wet-paper-emotional-landscape.png": "颜色渗透湿纸抽象艺术，每种颜色承载一种情感，红色侵略性扩散代表愤怒，蓝色平静汇聚代表和平，黄色辐射代表喜悦，在纹理水彩纸上创建抽象情感风景，俯瞰工作室灯光，写实微距摄影，柔和鲜艳水彩色调",
  "Abstract/057-maze-light-dead-ends-darkness-paths-glow-choices.png": "光之迷宫抽象艺术，死路溶解为黑暗，正确路径更亮发光，人生选择的抽象呈现，金色光墙与纯黑虚空，一个明亮身影穿行迷宫，戏剧性高对比灯光，写实3D渲染，黑色与金光色调",
  "Nature/064-cactus-desert-turned-ice-sculptures-frozen-oasis.png": "亚利桑那沙漠中的仙人掌变成 towering 冰雕，每根刺上的冰冻水珠形成水晶吊灯，沙丘覆盖霜花图案如雪蕾丝，冰缘棕榈树的冰冻绿洲池塘，超现实冰冷沙漠氛围，照片级真实风景，蓝白色调与琥珀沙色对比",
  "Nature/493-waterfall-flowing-upward-into-clouds-reverse-gravity.png": "巨大瀑布从峡谷底部向上流入云层，水以优雅螺旋柱形反抗重力，水雾上升而非下降，鱼沿上升水流向上游，峡谷壁苔藓和常春藤向下生长，超现实逆重力风景，照片级真实自然摄影，戏剧性垂直构图",
  "Still Life/046-grandfather-clock-melting-into-golden-honey-pool.png": "木质落地钟融化成大理石桌面上的金色蜂蜜池，钟面如温热焦糖般滴落，黄铜齿轮如琥珀蜜饯漂浮在蜂蜜中，钟摆溶解成粘稠丝线，达利风格超现实静物，温暖琥珀金色灯光，照片级真实影棚摄影，丰富质感细节",
  "Still Life/047-old-book-growing-ivy-vines-sprouting-flowers-pages.png": "古旧皮革封面书放在木桌上，书页间长出常春藤藤蔓，页边空白处绽放白色兰花，根系如活书签穿行于文字间，封面裂开蕨类植物萌出，苔藓蔓延覆盖桌面，超现实植物静物，温暖自然灯光，照片级真实微距摄影，绿棕色调",
  "Fantasy/496-clockmaker-galaxy-forge-assembling-miniature-stars.png": "钟表匠矮人在巨大黄铜星盘内部工作，在微型黄铜臂架上组装小型星系，每个齿轮是旋转行星，钟摆摆动如彗星轨迹，工坊充满玻璃罐中漂浮的星系原型，星座蓝图钉在墙上，蒸汽朋克宇宙工坊，温暖黄铜与蓝色星光，照片级真实奇幻艺术，精密机械细节",
  "Fantasy/039-quill-pen-writing-words-transforming-into-flying-birds.png": "发光羽毛笔在羊皮纸上书写，每个字母从纸面升起变成小鸟，文字变成金色麻雀群向上飞流，墨滴变成蝴蝶，羊皮纸本身卷曲成巢，魔法图书馆飘浮书籍，温暖烛光与金色光芒，照片级真实奇幻插画，琥珀与金色调",
  "Fantasy/498-mirror-maze-each-reflection-showing-different-world.png": "无限镜面迷宫，每面镜子映出完全不同的世界——一面映出水下珊瑚王国，另一面火山锻造场，下一面翼人居民的云城，再一面水晶洞穴，行走者同时看到所有世界，反射无限延伸，照片级真实奇幻概念艺术，棱镜多彩灯光，超现实氛围",
  "Abstract/058-echo-visualized-sound-wave-sculpture-resonating-canyon.png": "回声的抽象可视化——共鸣峡谷中的物理声波雕塑，原始声音为中心鲜红球体，每次回声为渐小球体，颜色从橙色到黄色到淡白递减，峡谷壁以镜像模式反射波纹，照片级真实3D渲染，暖到冷渐变色调，暗背景戏剧性画廊灯光",
  "Abstract/059-code-weaving-digital-tapestry-binary-threads-pattern.png": "计算机代码编织成数字挂毯的抽象艺术，二进制0和1作为经纬线创建精密几何图案，函数调用如金色刺绣，循环如递归螺旋纹样，错误行如红色断裂线，挂毯悬挂在暗色虚拟画廊，照片级真实3D渲染，暗背景青金红色线色彩，戏剧性纤维灯光",
};
