window.promptExamples = [
  { title: 'Professional headshot of confident businesswoman in her 30s', src: 'prompts-final/prompts-previews/Portrait/001-corporate.png' },
  { title: 'Futuristic cyberpunk city at night', src: 'prompts-final/prompts-previews/Urban/001-cyberpunk.png' },
  { title: 'Swiss luxury watch close-up', src: 'prompts-final/prompts-previews/Still Life/001-luxury.png' },
  { title: 'Pastoral countryside in Studio Ghibli animation style', src: 'prompts-final/prompts-previews/Fantasy/001-ghibli.png' },
  { title: 'Snow-capped mountain range at sunrise', src: 'prompts-final/prompts-previews/Nature/001-landscape.png' },
  { title: 'Gourmet burger with stacked ingredients', src: 'prompts-final/prompts-previews/Still Life/002-food.png' },
  { title: 'Majestic dragon on mountain peak', src: 'prompts-final/prompts-previews/Fantasy/002-dragon.png' },
  { title: 'Ancient forest with morning mist', src: 'prompts-final/prompts-previews/Nature/002-forest.png' },
  { title: 'Anime portrait of a young woman with neon pink twin-tail hai', src: 'prompts-final/prompts-previews/Fantasy/009-cyberanime.png' },
  { title: '1970s film photography portrait of a woman in her late 20s', src: 'prompts-final/prompts-previews/Portrait/002-1970s.png' },
  { title: 'Cinematic concept art of a massive floating castle above a s', src: 'prompts-final/prompts-previews/Fantasy/003-castle.png' },
  { title: 'VHS glitch aesthetic portrait', src: 'prompts-final/prompts-previews/Abstract/001-vhs.png' },
  { title: 'Ancient city ruins underwater', src: 'prompts-final/prompts-previews/Fantasy/004-atlantis.png' },
  { title: 'Abstract fluid art', src: 'prompts-final/prompts-previews/Abstract/002-abstract.png' },
  { title: 'Close-up portrait of weathered fisherman in his 60s', src: 'prompts-final/prompts-previews/Portrait/003-documentary.png' },
  { title: 'Sci-fi concept art of an alien moon surface with two suns se', src: 'prompts-final/prompts-previews/Fantasy/005-alien.png' },
  { title: 'A surreal', src: 'prompts-final/prompts-previews/Abstract/003-photorealistic-miniature-construction-on-giant-kfc-french-fr.png' },
  { title: 'Hyper-realistic', src: 'prompts-final/prompts-previews/Abstract/018-miniature-construction-on-air-jordan-1-sneaker-art-diorama.png' },
  { title: 'A screenshot of the Google home page with a banana Google do', src: 'prompts-final/prompts-previews/Abstract/021-playful-banana-google-logo-search-page-design.png' },
  { title: 'Close-up', src: 'prompts-final/prompts-previews/Abstract/022-vintage-digital-camera-portrait-y2k-aesthetic-nostalgia.png' },
  { title: 'A flash photography snapshot taken on a disposable camera in', src: 'prompts-final/prompts-previews/Abstract/024-candid-90s-party-photo-young-man-laughing-red-eye.png' },
  { title: 'Imagine a pencil tip seen through a microscope. Imagine how', src: 'prompts-final/prompts-previews/Abstract/004-extreme-close-up-broken-pencil-graphite-wood-texture.png' },
  { title: 'minimalist geometric abstract art', src: 'prompts-final/prompts-previews/Abstract/005-geometric-abstract-composition.png' },
  { title: 'fluid marble ink swirls in water', src: 'prompts-final/prompts-previews/Abstract/006-fluid-marble-ink-swirl.png' },
  { title: 'minimalist gradient wave design', src: 'prompts-final/prompts-previews/Abstract/007-minimalist-gradient-wave.png' },
  { title: 'fractal crystal growth macro photography', src: 'prompts-final/prompts-previews/Abstract/008-fractal-crystal-growth.png' },
  { title: 'abstract neon light tube sculpture', src: 'prompts-final/prompts-previews/Abstract/009-neon-light-tube-sculpture.png' },
  { title: 'explosion of colorful powder frozen in time', src: 'prompts-final/prompts-previews/Abstract/010-color-explosion-powder-art.png' },
  { title: 'abstract origami paper landscape', src: 'prompts-final/prompts-previews/Abstract/011-origami-paper-landscape.png' },
  { title: 'liquid mercury chrome sphere', src: 'prompts-final/prompts-previews/Abstract/012-liquid-metal-reflection.png' },
  { title: 'intricate kaleidoscope mandala', src: 'prompts-final/prompts-previews/Abstract/013-kaleidoscope-mandala.png' },
  { title: 'The Google Android robot', src: 'prompts-final/prompts-previews/Fantasy/006-bugdroid-internal-scan-sci-fi-thermal-x-ray-robot-art.png' },
  { title: 'Clean early-2000s rom-com studio poster composite. Two adult', src: 'prompts-final/prompts-previews/Fantasy/035-romantic-comedy-poster-how-to-lose-a-guy-in-10-days.png' },
  { title: 'A lone figure in a long coat walking across a barren landsca', src: 'prompts-final/prompts-previews/Fantasy/007-cinematic-desert-walk-solitary-figure-in-orange-haze.png' },
  { title: 'hidden elven kingdom in ancient forest', src: 'prompts-final/prompts-previews/Fantasy/010-elven-forest-kingdom.png' },
  { title: 'dark sorcerer tower atop jagged mountain', src: 'prompts-final/prompts-previews/Fantasy/011-necromancer-dark-tower.png' },
  { title: 'massive steampunk airship fleet in aerial battle', src: 'prompts-final/prompts-previews/Fantasy/012-steampunk-airship-battle.png' },
  { title: 'ancient Atlantis ruins deep underwater', src: 'prompts-final/prompts-previews/Fantasy/013-underwater-atlantis-ruins.png' },
  { title: 'fantasy castle on floating island', src: 'prompts-final/prompts-previews/Fantasy/014-floating-castle-islands.png' },
  { title: 'ice queen on frozen crystal throne', src: 'prompts-final/prompts-previews/Fantasy/040-ice-queen-frozen-throne.png' },
  { title: 'dwarven blacksmith forge deep underground', src: 'prompts-final/prompts-previews/Fantasy/015-dwarf-forge-underground.png' },
  { title: 'majestic forest spirit deer with antlers made of glowing bra', src: 'prompts-final/prompts-previews/Fantasy/016-forest-spirit-deer.png' },
  { title: 'cyberpunk samurai in neon-lit alley', src: 'prompts-final/prompts-previews/Fantasy/041-cyberpunk-samurai-duel.png' },
  { title: 'phoenix rising from volcanic ashes', src: 'prompts-final/prompts-previews/Fantasy/017-phoenix-rising-from-ashes.png' },
  { title: 'spectral pirate ghost ship sailing through supernatural stor', src: 'prompts-final/prompts-previews/Fantasy/018-pirate-ghost-ship-storm.png' },
  { title: 'Victorian steampunk time travel laboratory', src: 'prompts-final/prompts-previews/Fantasy/019-time-traveler-steampunk-lab.png' },
  { title: 'colossal ancient mecha robot half-buried in desert ruins', src: 'prompts-final/prompts-previews/Fantasy/020-giant-robot-ancient-ruins.png' },
  { title: 'infinite magical library with floating books', src: 'prompts-final/prompts-previews/Fantasy/021-magical-library-infinite.png' },
  { title: 'werewolf transformation under full moon', src: 'prompts-final/prompts-previews/Fantasy/022-werewolf-full-moon-forest.png' },
  { title: 'giant sky whale floating through clouds above ocean', src: 'prompts-final/prompts-previews/Fantasy/023-sky-whale-cloud-voyager.png' },
  { title: 'epic fantasy realism', src: 'prompts-final/prompts-previews/Nature/003-alpine-village-majestic-snow-capped-mountains-landscape.png' },
  { title: 'A photorealistic image of a cloud in the sky', src: 'prompts-final/prompts-previews/Nature/004-photorealistic-cloud-world-map-art-on-blue-sky.png' },
  { title: 'sunrise over a misty mountain valley', src: 'prompts-final/prompts-previews/Nature/005-misty-mountain-valley-sunrise.png' },
  { title: 'dense forest path with soft rays of sunlight through tall tr', src: 'prompts-final/prompts-previews/Nature/006-sunlit-forest-path.png' },
  { title: 'rocky coastline with large waves crashing against cliffs', src: 'prompts-final/prompts-previews/Nature/007-rocky-coastline-waves.png' },
  { title: 'snowy mountain peak under a clear blue sky', src: 'prompts-final/prompts-previews/Nature/008-snowy-mountain-peak.png' },
  { title: 'tropical beach with turquoise water', src: 'prompts-final/prompts-previews/Nature/009-tropical-beach-paradise.png' },
  { title: 'forest river with smooth long exposure water', src: 'prompts-final/prompts-previews/Nature/010-forest-river-long-exposure.png' },
  { title: 'desert sand dunes at sunset', src: 'prompts-final/prompts-previews/Nature/011-desert-dunes-sunset.png' },
  { title: 'calm lake with perfect mountain reflection', src: 'prompts-final/prompts-previews/Nature/012-mirror-lake-reflection.png' },
  { title: 'lush jungle waterfall', src: 'prompts-final/prompts-previews/Nature/013-jungle-waterfall.png' },
  { title: 'night sky over a rural landscape', src: 'prompts-final/prompts-previews/Nature/014-milky-way-night-sky.png' },
  { title: 'field of tall golden wheat', src: 'prompts-final/prompts-previews/Nature/015-golden-wheat-field.png' },
  { title: 'northern lights over a snowy landscape', src: 'prompts-final/prompts-previews/Nature/016-northern-lights-aurora.png' },
  { title: 'wildflower meadow in spring', src: 'prompts-final/prompts-previews/Nature/017-wildflower-spring-meadow.png' },
  { title: 'foggy lake at dawn', src: 'prompts-final/prompts-previews/Nature/018-dawn-foggy-lake-pier.png' },
  { title: 'winter forest with snow-covered trees', src: 'prompts-final/prompts-previews/Nature/019-winter-forest-blue-hour.png' },
  { title: 'cliffs above a turquoise bay', src: 'prompts-final/prompts-previews/Nature/020-turquoise-bay-cliffs.png' },
  { title: 'winding river seen from above', src: 'prompts-final/prompts-previews/Nature/021-winding-river-aerial.png' },
  { title: 'rolling green hills under dramatic storm clouds', src: 'prompts-final/prompts-previews/Nature/022-rolling-hills-storm.png' },
  { title: 'rocky canyon with river at the bottom', src: 'prompts-final/prompts-previews/Nature/023-rocky-canyon-river.png' },
  { title: 'countryside road lined with trees', src: 'prompts-final/prompts-previews/Nature/024-countryside-road-golden-hour.png' },
  { title: 'cherry blossom trees in full bloom along a park path', src: 'prompts-final/prompts-previews/Nature/025-cherry-blossom-spring-park.png' },
  { title: 'aerial view of autumn forest canopy', src: 'prompts-final/prompts-previews/Nature/026-autumn-forest-canopy.png' },
  { title: 'Sahara desert sand dunes at dawn', src: 'prompts-final/prompts-previews/Nature/027-sahara-sand-dunes-dawn.png' },
  { title: 'crystal clear alpine lake in Swiss Alps', src: 'prompts-final/prompts-previews/Nature/028-alpine-lake-crystal-clear.png' },
  { title: 'towering bamboo forest in Kyoto', src: 'prompts-final/prompts-previews/Nature/029-bamboo-forest-kyoto.png' },
  { title: 'inside an ice cave in Iceland glacier', src: 'prompts-final/prompts-previews/Nature/030-iceland-glacier-ice-cave.png' },
  { title: 'endless lavender field in Provence France', src: 'prompts-final/prompts-previews/Nature/031-lavender-field-provence.png' },
  { title: 'dramatic thunderstorm over open ocean', src: 'prompts-final/prompts-previews/Nature/032-thunderstorm-over-ocean.png' },
  { title: 'vibrant coral reef underwater scene', src: 'prompts-final/prompts-previews/Nature/033-coral-reef-underwater.png' },
  { title: 'African savannah at sunset', src: 'prompts-final/prompts-previews/Nature/034-african-savannah-sunset.png' },
  { title: 'Mount Fuji with cherry blossoms in foreground', src: 'prompts-final/prompts-previews/Nature/035-mount-fuji-cherry-blossom.png' },
  { title: 'Patagonia mountain range at sunrise', src: 'prompts-final/prompts-previews/Nature/036-patagonia-mountain-range.png' },
  { title: 'massive waterfall with rainbow forming in mist', src: 'prompts-final/prompts-previews/Nature/037-rainbow-over-waterfall.png' },
  { title: 'Mono Lake tufa towers at sunrise', src: 'prompts-final/prompts-previews/Nature/038-mono-lake-tufa-towers.png' },
  { title: 'Santorini Greece at sunset', src: 'prompts-final/prompts-previews/Nature/039-santorini-sunset-aegean.png' },
  { title: 'Yosemite Valley in autumn', src: 'prompts-final/prompts-previews/Nature/040-yosemite-valley-autumn.png' },
  { title: 'aerial view of Great Barrier Reef Australia', src: 'prompts-final/prompts-previews/Nature/041-great-barrier-reef-aerial.png' },
  { title: 'Milford Sound New Zealand at dawn', src: 'prompts-final/prompts-previews/Nature/042-new-zealand-milford-sound.png' },
  { title: 'Death Valley at night', src: 'prompts-final/prompts-previews/Nature/043-death-valley-star-trails.png' },
  { title: 'Kilauea volcano lava flow entering ocean at night', src: 'prompts-final/prompts-previews/Nature/044-hawaii-volcano-lava-flow.png' },
  { title: 'A young woman sitting on yoga mat', src: 'prompts-final/prompts-previews/Portrait/004-woman-post-workout-hydration-fitness-gym-scene.png' },
  { title: 'Glamorous Woman Applying Lip Gloss in Mirror Reflection. You', src: 'prompts-final/prompts-previews/Portrait/005-stylish-woman-mirror-selfie-pink-top-gold-skirt-fashion.png' },
  { title: 'professional headshot of confident Caucasian man in 30s', src: 'prompts-final/prompts-previews/Portrait/006-professional-corporate-headshot.png' },
  { title: 'studio beauty portrait of Caucasian woman with flawless make', src: 'prompts-final/prompts-previews/Portrait/007-studio-beauty-portrait.png' },
  { title: 'candid street portrait of stylish young Caucasian man', src: 'prompts-final/prompts-previews/Portrait/008-candid-street-portrait.png' },
  { title: 'black and white fine art portrait', src: 'prompts-final/prompts-previews/Portrait/009-dramatic-noir-portrait.png' },
  { title: 'romantic Caucasian couple portrait at sunset', src: 'prompts-final/prompts-previews/Portrait/010-bohemian-sunset-couple.png' },
  { title: '1970s film photography portrait of Caucasian woman', src: 'prompts-final/prompts-previews/Portrait/011-vintage-1970s-portrait.png' },
  { title: 'dynamic action portrait of Caucasian male athlete mid-motion', src: 'prompts-final/prompts-previews/Portrait/012-athletic-action-portrait.png' },
  { title: 'candid portrait of curious Caucasian child', src: 'prompts-final/prompts-previews/Portrait/013-child-wonder-portrait.png' },
  { title: 'character portrait of elderly Caucasian man with weathered f', src: 'prompts-final/prompts-previews/Portrait/014-senior-wisdom-portrait.png' },
  { title: 'dynamic photorealistic chocolate chip cookies suspended mid-', src: 'prompts-final/prompts-previews/Still Life/003-chocolate-chip-cookie-splash.png' },
  { title: 'luxury perfume bottle on reflective water surface', src: 'prompts-final/prompts-previews/Still Life/004-minimalist-perfume-bottle.png' },
  { title: 'Hyper-realistic mirror selfie scene in a bathroom. A young w', src: 'prompts-final/prompts-previews/Portrait/055-mirror-selfie.png' },
  { title: 'High-definition fashion portrait', src: 'prompts-final/prompts-previews/Portrait/056-sculpted-stillness.png' },
  { title: 'still life of fresh seasonal fruits on rustic wooden table', src: 'prompts-final/prompts-previews/Still Life/005-fresh-fruit-still-life.png' },
  { title: 'single modern athletic sneaker', src: 'prompts-final/prompts-previews/Still Life/006-sneaker-product-studio.png' },
  { title: 'colorful macaron display on marble counter', src: 'prompts-final/prompts-previews/Still Life/007-macaron-pastel-display.png' },
  { title: 'beautifully arranged sushi platter', src: 'prompts-final/prompts-previews/Still Life/008-sushi-platter-japanese.png' },
  { title: 'flat lay of gold minimalist jewelry', src: 'prompts-final/prompts-previews/Still Life/009-gold-jewelry-flat-lay.png' },
  { title: 'collection of handcrafted ceramic pottery', src: 'prompts-final/prompts-previews/Still Life/010-handcrafted-pottery-collection.png' },
  { title: 'freshly baked artisan sourdough bread', src: 'prompts-final/prompts-previews/Still Life/011-fresh-baked-bread-loaf.png' },
  { title: 'modern smartphone on minimal white pedestal', src: 'prompts-final/prompts-previews/Still Life/012-smartphone-clean-product.png' },
  { title: 'elegant floral bouquet arrangement with roses peonies eucaly', src: 'prompts-final/prompts-previews/Still Life/013-floral-bouquet-arrangement.png' },
  { title: 'minimalist skincare product lineup', src: 'prompts-final/prompts-previews/Still Life/014-skincare-products-lineup.png' },
  { title: 'classic single-lens rangefinder Leica film camera on wooden', src: 'prompts-final/prompts-previews/Still Life/015-vintage-film-camera-product.png' },
  { title: 'premium sunglasses on reflective black surface', src: 'prompts-final/prompts-previews/Still Life/016-sunglasses-brand-photography.png' },
  { title: 'macro shot of luxury lipstick', src: 'prompts-final/prompts-previews/Still Life/017-lipstick-beauty-macro.png' },
  { title: 'decadent ice cream sundae with chocolate sauce dripping', src: 'prompts-final/prompts-previews/Still Life/018-ice-cream-sundae-dessert.png' },
  { title: 'extreme macro of mechanical watch movement', src: 'prompts-final/prompts-previews/Still Life/019-mechanical-watch-movement.png' },
  { title: 'Japanese matcha tea ceremony setup', src: 'prompts-final/prompts-previews/Still Life/020-tea-ceremony-japanese.png' },
  { title: 'vintage vinyl record player with LP spinning', src: 'prompts-final/prompts-previews/Still Life/021-vinyl-record-player.png' },
  { title: 'minimalist candle collection', src: 'prompts-final/prompts-previews/Still Life/022-candle-collection-minimalist.png' },
  { title: 'running shoes suspended mid-air', src: 'prompts-final/prompts-previews/Still Life/023-running-shoes-action-freeze.png' },
  { title: 'Tokyo Shinjuku at night', src: 'prompts-final/prompts-previews/Urban/002-tokyo-shinjuku-night-alley.png' },
  { title: 'futuristic city skyline at dusk', src: 'prompts-final/prompts-previews/Urban/003-dusk-skyline-flying-cars.png' },
  { title: 'moody twilight of megastructure under construction', src: 'prompts-final/prompts-previews/Urban/004-megastructure-construction-twilight.png' },
  { title: 'charming European old town square at blue hour', src: 'prompts-final/prompts-previews/Urban/005-european-old-town-square.png' },
  { title: 'London street after rain', src: 'prompts-final/prompts-previews/Urban/006-london-rainy-street-reflection.png' },
  { title: 'San Francisco at dawn with rolling fog through Golden Gate B', src: 'prompts-final/prompts-previews/Urban/007-san-francisco-morning-fog.png' },
  { title: 'Paris Montmartre at sunrise', src: 'prompts-final/prompts-previews/Urban/008-paris-montmartre-morning.png' },
  { title: 'Hong Kong at night from Victoria Peak', src: 'prompts-final/prompts-previews/Urban/009-hong-kong-neon-night.png' },
  { title: 'Venice canal at golden hour', src: 'prompts-final/prompts-previews/Urban/010-venice-canal-gondola.png' },
  { title: 'Seoul night street food market', src: 'prompts-final/prompts-previews/Urban/011-seoul-night-street-food.png' },
  { title: 'Barcelona Gothic Quarter narrow stone alley', src: 'prompts-final/prompts-previews/Urban/012-barcelona-gothic-quarter.png' },
  { title: 'Amsterdam canal lined with bicycles', src: 'prompts-final/prompts-previews/Urban/013-amsterdam-canal-bikes.png' },
  { title: 'Prague Charles Bridge at dawn', src: 'prompts-final/prompts-previews/Urban/014-prague-charles-bridge-dawn.png' },
  { title: 'Moscow Red Square covered in fresh snow', src: 'prompts-final/prompts-previews/Urban/015-moscow-red-square-snow.png' },
  { title: 'Singapore Marina Bay at blue hour', src: 'prompts-final/prompts-previews/Urban/016-singapore-marina-bay.png' },
  { title: 'Copenhagen Nyhavn colorful historic harbor buildings reflect', src: 'prompts-final/prompts-previews/Urban/017-copenhagen-nyhavn-colorful.png' },
  { title: 'Golden retriever wearing reading glasses', src: 'prompts-final/prompts-previews/Animals/001-golden-retriever-reading-newspaper-fireplace.png' },
  { title: 'Tiny glowing octopus floating inside a glass teapot', src: 'prompts-final/prompts-previews/Animals/002-octopus-inside-glass-teapot-steaming.png' },
  { title: 'Pink flamingo standing on one leg atop a glowing neon roofto', src: 'prompts-final/prompts-previews/Animals/003-flamingo-neon-rooftop-cyberpunk-night.png' },
  { title: 'Garden snail carrying a tiny detailed medieval castle on its', src: 'prompts-final/prompts-previews/Animals/004-snail-carrying-medieval-castle-mossy-forest.png' },
  { title: 'Emperor penguin in a fitted tuxedo walking through golden ca', src: 'prompts-final/prompts-previews/Animals/005-penguin-tuxedo-monte-carlo-casino.png' },
  { title: 'Giant koi fish swimming through golden sunset clouds in the', src: 'prompts-final/prompts-previews/Animals/006-koi-fish-swimming-through-sky-clouds-sunset.png' },
  { title: 'Red fox curled up sleeping inside a hollow oak tree trunk', src: 'prompts-final/prompts-previews/Animals/007-fox-sleeping-hollow-tree-snowfall.png' },
  { title: 'Hummingbird hovering near a glowing crystal flower in a dark', src: 'prompts-final/prompts-previews/Animals/008-hummingbird-glowing-crystal-flower-dark-cave.png' },
  { title: 'Massive elephant made entirely of swirling autumn leaves wal', src: 'prompts-final/prompts-previews/Animals/009-elephant-made-of-autumn-leaves-foggy-meadow.png' },
  { title: 'Orange tabby cat sitting on a stool behind a vintage vinyl r', src: 'prompts-final/prompts-previews/Animals/010-cat-round-sunglasses-vinyl-record-shop.png' },
  { title: 'Wise barn owl wearing tiny round spectacles perched on a sta', src: 'prompts-final/prompts-previews/Animals/011-owl-librarian-ancient-library-candlelight.png' },
  { title: 'Ancient turtle carrying a miniature Japanese zen garden on i', src: 'prompts-final/prompts-previews/Animals/012-turtle-japanese-garden-on-shell-ukiyoe.png' },
  { title: 'Giant translucent jellyfish drifting through an abandoned su', src: 'prompts-final/prompts-previews/Animals/013-jellyfish-floating-subway-station-surreal.png' },
  { title: 'Polar bear sitting on a frozen Arctic lake at night', src: 'prompts-final/prompts-previews/Animals/014-polar-bear-ice-fishing-aurora-frozen-lake.png' },
  { title: 'Chameleon blending perfectly into a towering Gothic cathedra', src: 'prompts-final/prompts-previews/Animals/015-chameleon-stained-glass-window-gothic.png' },
  { title: 'Black crow standing upright on a rain-soaked cobblestone all', src: 'prompts-final/prompts-previews/Animals/016-crow-detective-fedora-foggy-london-alley.png' },
  { title: 'Majestic lion formed entirely from constellations and stardu', src: 'prompts-final/prompts-previews/Animals/017-lion-made-of-constellations-night-sky.png' },
  { title: 'Five emperor penguins forming a jazz band on a floating iceb', src: 'prompts-final/prompts-previews/Animals/018-penguin-band-iceberg-jazz-vintage-poster.png' },
  { title: 'Fat hippopotamus relaxing in an oversized bubble bath in a c', src: 'prompts-final/prompts-previews/Animals/019-hippo-bubble-bath-rubber-ducks-whimsical.png' },
  { title: 'Giraffe standing on a rocky coast with its long neck serving', src: 'prompts-final/prompts-previews/Animals/020-giraffe-lighthouse-rocky-coast-surreal.png' },
  { title: 'Peacock displaying its tail feathers', src: 'prompts-final/prompts-previews/Animals/021-peacock-tail-feathers-famous-paintings-art-nouveau.png' },
  { title: 'Brown bear sleeping soundly inside a cave made entirely of c', src: 'prompts-final/prompts-previews/Animals/022-bear-hibernating-candy-cave-fantasy.png' },
  { title: 'Bottlenose dolphin mid-leap bursting out of a golden-framed', src: 'prompts-final/prompts-previews/Animals/023-dolphin-leaping-out-of-painting-into-gallery.png' },
  { title: 'Red squirrel with puffed cheeks hoarding golden acorns in a', src: 'prompts-final/prompts-previews/Animals/024-squirrel-golden-acorns-autumn-library.png' },
  { title: 'Tiger stalking silently through a dense bamboo forest', src: 'prompts-final/prompts-previews/Animals/025-tiger-bamboo-forest-chinese-ink-wash.png' },
  { title: 'Cute koala wearing a vintage white space helmet and silver a', src: 'prompts-final/prompts-previews/Animals/026-koala-astronaut-moon-eucalyptus-flag.png' },
  { title: 'Elegant white swan wearing a pale pink ballet tutu and tiny', src: 'prompts-final/prompts-previews/Animals/027-swan-ballerina-opera-stage-tutu.png' },
  { title: 'Realistic mantis shrimp standing upright on a boxing ring ca', src: 'prompts-final/prompts-previews/Animals/028-mantis-shrimp-boxer-boxing-ring.png' },
  { title: 'Sleepy sloth hanging upside down from a giant brass pocket w', src: 'prompts-final/prompts-previews/Animals/029-sloth-steampunk-clock-tower-pocket-watch.png' },
  { title: 'Adorable hedgehog curled up into a perfect ball of colorful', src: 'prompts-final/prompts-previews/Animals/030-hedgehog-yarn-ball-knitting-needles.png' },
  { title: 'Pink axolotl with fluffy external gills relaxing in a claw-f', src: 'prompts-final/prompts-previews/Animals/031-axolotl-victorian-bathtub-rose-petals.png' },
  { title: 'Fluffy sheep wearing a hand-knitted rainbow striped sweater', src: 'prompts-final/prompts-previews/Animals/032-sheep-rainbow-sweater-scottish-highland.png' },
  { title: 'Sea otter floating peacefully inside a giant porcelain teacu', src: 'prompts-final/prompts-previews/Animals/033-otter-kelp-forest-teacup.png' },
  { title: 'Male peacock spider performing a colorful mating dance on a', src: 'prompts-final/prompts-previews/Animals/034-peacock-spider-disco-ball-dance.png' },
  { title: 'Atlantic puffin wearing a bright yellow fisherman\'s raincoat', src: 'prompts-final/prompts-previews/Animals/035-puffin-raincoat-stormy-scottish-cliff.png' },
  { title: 'Colorful day gecko sitting behind a small stall in a bustlin', src: 'prompts-final/prompts-previews/Animals/036-gecko-jewelry-seller-moroccan-bazaar.png' },
  { title: 'Mechanical owl made entirely of brass gears', src: 'prompts-final/prompts-previews/Animals/037-owl-clockwork-gears-steampunk-workshop.png' },
  { title: 'Raccoon wearing a black eye mask and burglar cap', src: 'prompts-final/prompts-previews/Animals/038-raccoon-burglar-jewelry-store-night.png' },
  { title: 'Giant dragonfly with translucent wings made of stained glass', src: 'prompts-final/prompts-previews/Animals/039-dragonfly-stained-glass-wings-lily-pond.png' },
  { title: 'Walrus with a thick white mustache wearing a navy captain\'s', src: 'prompts-final/prompts-previews/Animals/040-walrus-sea-captain-ice-ship.png' },
  { title: 'Fennec fox with oversized ears wearing large professional he', src: 'prompts-final/prompts-previews/Animals/041-fennec-fox-headphones-sahara-dunes.png' },
  { title: 'Narwhal swimming in deep blue arctic water', src: 'prompts-final/prompts-previews/Animals/042-narwhal-lightsaber-tusk-underwater.png' },
  { title: 'Fluffy chinchilla sleeping curled up on a soft cloud made of', src: 'prompts-final/prompts-previews/Animals/043-chinchilla-cotton-candy-cloud-bed.png' },
  { title: 'Towering stack of golden pancakes with maple syrup cascading', src: 'prompts-final/prompts-previews/Food/001-pancake-stack-syrup-waterfall-kayakers.png' },
  { title: 'Giant flaky croissant glowing like a crescent moon suspended', src: 'prompts-final/prompts-previews/Food/002-croissant-crescent-moon-paris-rooftops.png' },
  { title: 'Steaming bowl of tonkotsu ramen placed on a rain-soaked coun', src: 'prompts-final/prompts-previews/Food/003-ramen-cyberpunk-alley-neon-signs.png' },
  { title: 'Avocado toast on sourdough with tiny hipster figures sitting', src: 'prompts-final/prompts-previews/Food/004-avocado-toast-tiny-hipster-cafe.png' },
  { title: 'Colorful French macarons arranged on a painter\'s palette lik', src: 'prompts-final/prompts-previews/Food/005-macarons-impressionist-palette.png' },
  { title: 'Gourmet burger deconstructed into floating ingredients again', src: 'prompts-final/prompts-previews/Food/006-burger-ingredients-zero-gravity.png' },
  { title: 'Vietnamese pho in a deep ceramic bowl', src: 'prompts-final/prompts-previews/Food/007-pho-steam-forming-dragon.png' },
  { title: 'Giant slice of pepperoni pizza transformed into a resort swi', src: 'prompts-final/prompts-previews/Food/008-pizza-slice-swimming-pool-tiny-swimmers.png' },
  { title: 'Close-up of a cup of coffee with latte art depicting a swirl', src: 'prompts-final/prompts-previews/Food/009-coffee-latte-art-galaxy.png' },
  { title: 'Giant pink frosted donut floating in space like a planet', src: 'prompts-final/prompts-previews/Food/010-donut-planet-with-sprinkle-rings.png' },
  { title: 'Lobster roll in a split-top brioche bun', src: 'prompts-final/prompts-previews/Food/011-lobster-roll-new-england-beach-sunset.png' },
  { title: 'Bamboo steamer baskets transformed into colorful hot air bal', src: 'prompts-final/prompts-previews/Food/012-dim-sum-hot-air-balloons.png' },
  { title: 'Vanilla ice cream cone melting over the edge of a table', src: 'prompts-final/prompts-previews/Food/013-ice-cream-cone-melting-dali-clock.png' },
  { title: 'Three vibrant street tacos on a decorative altar surrounded', src: 'prompts-final/prompts-previews/Food/014-tacos-day-of-dead-celebration.png' },
  { title: 'Everything bagel with cream cheese and smoked salmon arrange', src: 'prompts-final/prompts-previews/Food/015-bagel-lox-new-york-cityscape.png' },
  { title: 'Traditional Japanese matcha tea ceremony setup in a serene b', src: 'prompts-final/prompts-previews/Food/016-matcha-tea-ceremony-bamboo-forest.png' },
  { title: 'Tower of elaborately decorated cupcakes stacked to form a fa', src: 'prompts-final/prompts-previews/Food/017-cupcake-tower-fairy-tale-castle.png' },
  { title: 'Perfectly seared medium-rare steak resting on a black volcan', src: 'prompts-final/prompts-previews/Food/018-steak-volcanic-rock-lava-glow.png' },
  { title: 'Belgian waffle on a white plate with berries and cream arran', src: 'prompts-final/prompts-previews/Food/019-waffles-berries-kandinsky-painting.png' },
  { title: 'Japanese bento box opened to reveal a meticulously arranged', src: 'prompts-final/prompts-previews/Food/020-bento-box-japanese-garden.png' },
  { title: 'Close-up of a cinnamon roll from above', src: 'prompts-final/prompts-previews/Food/021-cinnamon-roll-spiral-galaxy.png' },
  { title: 'Bamboo steamer flying through space like a spaceship', src: 'prompts-final/prompts-previews/Food/022-soup-dumplings-bamboo-steamer-spaceship.png' },
  { title: 'Crispy golden french fries standing upright like a miniature', src: 'prompts-final/prompts-previews/Food/023-french-fries-golden-forest.png' },
  { title: 'Giant bubble tea cup as a cosmic scene', src: 'prompts-final/prompts-previews/Food/024-bubble-tea-tapioca-planets.png' },
  { title: 'Gourmet grilled cheese sandwich cut in half', src: 'prompts-final/prompts-previews/Food/025-cheese-board-mountain-landscape.png' },
  { title: 'Creamy mushroom risotto in a black bowl', src: 'prompts-final/prompts-previews/Food/026-risotto-glowing-moon-italian-vineyard.png' },
  { title: 'Giant soft pretzel twisted into the shape of a Bavarian cloc', src: 'prompts-final/prompts-previews/Food/027-pretzel-bavarian-clock-tower.png' },
  { title: 'Fresh fruit tart viewed from above', src: 'prompts-final/prompts-previews/Food/028-fruit-tart-stained-glass-window.png' },
  { title: 'A thin French crepe folded into an arch bridge shape spannin', src: 'prompts-final/prompts-previews/Food/029-crepe-bridge-nutella-river.png' },
  { title: 'Whole roasted Peking duck with crispy lacquered skin hanging', src: 'prompts-final/prompts-previews/Food/030-peking-duck-lantern-temple.png' },
  { title: 'Scoops of colorful gelato arranged as rolling desert sand du', src: 'prompts-final/prompts-previews/Food/031-gelato-colorful-sand-dunes.png' },
  { title: 'Hollowed sourdough bread boule transformed into a miniature', src: 'prompts-final/prompts-previews/Food/032-sourdough-bread-hollow-bakery.png' },
  { title: 'Assorted mochi ice cream balls floating in a dark Japanese n', src: 'prompts-final/prompts-previews/Food/033-mochi-moons-japanese-night-sky.png' },
  { title: 'Giant paella pan viewed from above as a sunken treasure site', src: 'prompts-final/prompts-previews/Food/034-paella-sunken-treasure-coral-reef.png' },
  { title: 'Elongated chocolate eclair shaped like a Victorian railway c', src: 'prompts-final/prompts-previews/Food/035-eclair-victorian-railway-carriage.png' },
  { title: 'A single beautifully pleated Chinese dumpling folded to rese', src: 'prompts-final/prompts-previews/Food/036-dumpling-origami-crane.png' },
  { title: 'Square slice of tiramisu displayed as an archaeological exca', src: 'prompts-final/prompts-previews/Food/037-tiramisu-archaeological-dig.png' },
  { title: 'Vertical kebab skewer as a Pacific Northwest totem pole', src: 'prompts-final/prompts-previews/Food/038-kebab-skewer-totem-pole.png' },
  { title: 'A tall slice of New York cheesecake standing upright on a pl', src: 'prompts-final/prompts-previews/Food/039-cheesecake-art-deco-skyscraper.png' },
  { title: 'Split scone with clotted cream and strawberry jam placed at', src: 'prompts-final/prompts-previews/Food/040-scone-english-garden-maze.png' },
  { title: 'Korean bibimbap in a stone bowl arranged as a painter\'s colo', src: 'prompts-final/prompts-previews/Food/041-bibimbap-color-wheel-painter-studio.png' },
  { title: 'Cinnamon sugar churros coiled into a golden spiral staircase', src: 'prompts-final/prompts-previews/Food/042-churros-golden-spiral-staircase.png' },
  { title: 'Close-up of creme brulee with its caramelized sugar surface', src: 'prompts-final/prompts-previews/Food/043-creme-brulee-starry-night.png' },
  { title: 'Crispy golden spring rolls stacked and arranged to form a mu', src: 'prompts-final/prompts-previews/Food/044-spring-rolls-chinese-pagoda.png' },
  { title: 'Pavlova meringue floating like a soft white cloud in a paste', src: 'prompts-final/prompts-previews/Food/045-pavlova-cloud-fruit-rainbow.png' },
  { title: 'Pan-fried gyoza dumplings arranged in a circular pattern as', src: 'prompts-final/prompts-previews/Food/046-gyoza-lotus-flower-pond.png' },
  { title: 'Brownie broken in half revealing a sparkling geode interior', src: 'prompts-final/prompts-previews/Food/047-brownie-geode-crystal-interior.png' },
  { title: 'Ratatouille arranged from above as a pixel art mosaic', src: 'prompts-final/prompts-previews/Food/048-ratatouille-pixel-art-mosaic.png' },
  { title: 'Italian cannoli standing upright as Roman columns in a minia', src: 'prompts-final/prompts-previews/Food/049-cannoli-roman-columns-forum.png' },
  { title: 'Campfire s\'mores scene where graham crackers form tiny A-fra', src: 'prompts-final/prompts-previews/Food/050-smores-campfire-marshmallow-tents.png' },
  { title: 'Bowl of mapo tofu photographed as a volcanic eruption scene', src: 'prompts-final/prompts-previews/Food/051-mapo-tofu-volcanic-eruption.png' },
  { title: 'Tower of cream-filled profiteroles stacked as an elegant wed', src: 'prompts-final/prompts-previews/Food/052-profiterole-wedding-cake-topiary.png' },
  { title: 'Black ink dropped into clear water', src: 'prompts-final/prompts-previews/Abstract/014-ink-drop-water-city-skyline.png' },
  { title: 'Liquid mercury splashing upward and freezing mid-motion into', src: 'prompts-final/prompts-previews/Abstract/015-liquid-mercury-geometric-crystals.png' },
  { title: 'Streams of neon light in electric blue and magenta bending a', src: 'prompts-final/prompts-previews/Abstract/016-neon-light-magnetic-field-bending.png' },
  { title: 'Sand dunes made of pulverized gemstones in an aerodynamic wi', src: 'prompts-final/prompts-previews/Abstract/017-gemstone-sand-dunes-wind-tunnel.png' },
  { title: 'Elegant white smoke rings floating in a dark studio', src: 'prompts-final/prompts-previews/Abstract/019-smoke-rings-mathematical-equations.png' },
  { title: 'Molten glass captured at the exact moment of explosive shatt', src: 'prompts-final/prompts-previews/Abstract/020-molten-glass-frozen-explosion-color.png' },
  { title: 'Hundreds of colored yarn threads stretched and woven in thre', src: 'prompts-final/prompts-previews/Abstract/023-yarn-threads-topographic-map.png' },
  { title: 'A single beam of white light entering a dense rainforest can', src: 'prompts-final/prompts-previews/Abstract/025-prismatic-light-rainforest-canopy.png' },
  { title: 'Black ferrofluid responding to hidden magnets', src: 'prompts-final/prompts-previews/Abstract/026-ferrofluid-baroque-cathedral-spires.png' },
  { title: 'Explosive paint splatter frozen in mid-air', src: 'prompts-final/prompts-previews/Abstract/027-paint-splatter-inner-galaxy.png' },
  { title: 'Aerial view of cracked frozen lake ice forming a natural man', src: 'prompts-final/prompts-previews/Abstract/028-cracked-ice-mandala-northern-lights.png' },
  { title: 'Golden honey dripping in extreme slow motion', src: 'prompts-final/prompts-previews/Abstract/029-honey-slow-motion-abstract-calligraphy.png' },
  { title: 'Green and violet aurora borealis reflected in a perfectly st', src: 'prompts-final/prompts-previews/Abstract/030-aurora-reflected-liquid-gold-pool.png' },
  { title: 'Shattered pieces of stained glass floating in mid-air and re', src: 'prompts-final/prompts-previews/Abstract/031-stained-glass-butterfly-wing-reassembly.png' },
  { title: 'Long exposure light painting tracing the outlines of impossi', src: 'prompts-final/prompts-previews/Abstract/032-light-painting-dream-architecture.png' },
  { title: 'Cherry blossom petals dissolving in mid-fall', src: 'prompts-final/prompts-previews/Abstract/033-petals-dissolving-watercolor-pixels.png' },
  { title: 'Iridescent rainbow bismuth crystals growing in a formation r', src: 'prompts-final/prompts-previews/Abstract/034-bismuth-crystals-spiral-staircase.png' },
  { title: 'Macro photograph of a thin soap film bubble surface', src: 'prompts-final/prompts-previews/Abstract/035-soap-film-sunset-microscopic.png' },
  { title: 'Traditional marbled paper art viewed from above', src: 'prompts-final/prompts-previews/Abstract/036-marbled-paper-alien-planet-landscape.png' },
  { title: 'Round epoxy resin art piece capturing a miniature frozen sto', src: 'prompts-final/prompts-previews/Abstract/037-resin-art-frozen-storm-system.png' },
  { title: 'Extreme macro of colorful lichen growing on weathered stone', src: 'prompts-final/prompts-previews/Abstract/038-lichen-ancient-map-patterns.png' },
  { title: 'Shattered mirror pieces scattered on a dark surface', src: 'prompts-final/prompts-previews/Abstract/039-shattered-mirror-kaleidoscope-memories.png' },
  { title: 'Electric blue copper sulfate crystals growing on a dark surf', src: 'prompts-final/prompts-previews/Abstract/040-copper-sulfate-crystals-growing-reef.png' },
  { title: 'Hundreds of small white origami paper folds arranged on a li', src: 'prompts-final/prompts-previews/Abstract/041-origami-paper-folds-shadow-geometry.png' },
  { title: 'Caucasian European woman with flowing auburn hair standing i', src: 'prompts-final/prompts-previews/Portrait/015-lavender-field-auburn-hair-woman.png' },
  { title: 'Caucasian European elderly man with weathered hands and kind', src: 'prompts-final/prompts-previews/Portrait/016-elderly-storyteller-wooden-porch.png' },
  { title: 'Caucasian European teenage girl with paint-stained overalls', src: 'prompts-final/prompts-previews/Portrait/017-teenage-artist-paint-stained-overalls.png' },
  { title: 'Caucasian European woman archaeologist in desert excavation', src: 'prompts-final/prompts-previews/Portrait/018-woman-archaeologist-desert-excavation.png' },
  { title: 'Caucasian European young man in a tailored navy suit on a ro', src: 'prompts-final/prompts-previews/Portrait/019-young-man-navy-suit-rooftop-bar.png' },
  { title: 'Caucasian European mother and toddler daughter picking straw', src: 'prompts-final/prompts-previews/Portrait/020-mother-daughter-strawberry-garden.png' },
  { title: 'Caucasian European ballet dancer mid-arabesque on an empty t', src: 'prompts-final/prompts-previews/Portrait/057-ballet-dancer-arabesque-empty-stage.png' },
  { title: 'Caucasian European grandfather teaching his grandson to fish', src: 'prompts-final/prompts-previews/Portrait/021-grandfather-grandson-fishing-misty-lake.png' },
  { title: 'Caucasian European woman scientist in a white lab coat', src: 'prompts-final/prompts-previews/Portrait/022-woman-scientist-lab-coat-microscope.png' },
  { title: 'Caucasian European street musician woman playing saxophone o', src: 'prompts-final/prompts-previews/Portrait/023-street-musician-saxophone-rainy-paris.png' },
  { title: 'Caucasian European young woman in a vintage 1920s flapper dr', src: 'prompts-final/prompts-previews/Portrait/024-flapper-dress-1920s-jazz-club.png' },
  { title: 'Caucasian European male chef in white uniform', src: 'prompts-final/prompts-previews/Portrait/025-male-chef-wok-flames-action.png' },
  { title: 'Caucasian European little girl in a yellow raincoat splashin', src: 'prompts-final/prompts-previews/Portrait/026-little-girl-yellow-raincoat-puddles.png' },
  { title: 'Caucasian European woman mountain climber at summit', src: 'prompts-final/prompts-previews/Portrait/027-woman-mountain-climber-summit-victory.png' },
  { title: 'Caucasian European tattoo artist woman in her studio', src: 'prompts-final/prompts-previews/Portrait/058-tattoo-artist-woman-neon-studio.png' },
  { title: 'Caucasian European couple dancing tango in a dimly lit Bueno', src: 'prompts-final/prompts-previews/Portrait/028-couple-tango-buenos-aires-milonga.png' },
  { title: 'Caucasian European woman librarian surrounded by towering bo', src: 'prompts-final/prompts-previews/Portrait/029-woman-librarian-bookshelves-manuscript.png' },
  { title: 'Caucasian European woman astronaut in training', src: 'prompts-final/prompts-previews/Portrait/030-woman-astronaut-training-simulator.png' },
  { title: 'Caucasian European street artist woman spray-painting a vibr', src: 'prompts-final/prompts-previews/Portrait/031-street-artist-woman-spray-mural.png' },
  { title: 'Caucasian European woman in a traditional Irish fisherman sw', src: 'prompts-final/prompts-previews/Portrait/032-woman-irish-sweater-rugged-cliff.png' },
  { title: 'Caucasian European young man playing acoustic guitar on a wo', src: 'prompts-final/prompts-previews/Portrait/033-young-man-acoustic-guitar-sunset-dock.png' },
  { title: 'Caucasian European woman midwife holding a newborn baby', src: 'prompts-final/prompts-previews/Portrait/034-woman-midwife-holding-newborn.png' },
  { title: 'Caucasian European man in a leather jacket riding a vintage', src: 'prompts-final/prompts-previews/Portrait/035-man-leather-jacket-vintage-motorcycle-desert.png' },
  { title: 'Caucasian European woman beekeeper in a white suit surrounde', src: 'prompts-final/prompts-previews/Portrait/036-woman-beekeeper-white-suit-honeycomb.png' },
  { title: 'Caucasian European man glassblower shaping molten glass with', src: 'prompts-final/prompts-previews/Portrait/037-man-glassblower-molten-glass-furnace.png' },
  { title: 'Caucasian European woman choir singer in velvet robe inside', src: 'prompts-final/prompts-previews/Portrait/038-woman-choir-singer-gothic-cathedral.png' },
  { title: 'Caucasian European boy scout with compass and backpack in a', src: 'prompts-final/prompts-previews/Portrait/039-boy-scout-compass-pine-forest.png' },
  { title: 'Caucasian European woman deep sea diver in gear on a boat de', src: 'prompts-final/prompts-previews/Portrait/040-woman-deep-sea-diver-boat-deck.png' },
  { title: 'Caucasian European woman circus ringmaster in a red coat and', src: 'prompts-final/prompts-previews/Portrait/041-woman-circus-ringmaster-red-coat.png' },
  { title: 'Caucasian European young woman reading a book on a window se', src: 'prompts-final/prompts-previews/Portrait/042-woman-reading-window-seat-rain.png' },
  { title: 'Caucasian European man blacksmith hammering glowing iron on', src: 'prompts-final/prompts-previews/Portrait/043-man-blacksmith-hammering-iron-sparks.png' },
  { title: 'Caucasian European woman midwife in a sunlit birthing room', src: 'prompts-final/prompts-previews/Portrait/044-woman-midwife-sunlit-birthing-room.png' },
  { title: 'Caucasian European teenager girl playing chess in a park pav', src: 'prompts-final/prompts-previews/Portrait/045-teenager-girl-chess-park-pavilion.png' },
  { title: 'Caucasian European man organic farmer standing in a sunflowe', src: 'prompts-final/prompts-previews/Portrait/046-man-organic-farmer-sunflower-field.png' },
  { title: 'Caucasian European woman opera singer rehearsing in a rehear', src: 'prompts-final/prompts-previews/Portrait/047-woman-opera-singer-rehearsal-grand-piano.png' },
  { title: 'Caucasian European man astronaut in a white spacesuit standi', src: 'prompts-final/prompts-previews/Portrait/048-man-astronaut-white-spacesuit-lunar-sim.png' },
  { title: 'Caucasian European woman pastry chef piping intricate decora', src: 'prompts-final/prompts-previews/Portrait/049-woman-pastry-chef-piping-cake-decorations.png' },
  { title: 'Caucasian European elderly woman knitting a colorful blanket', src: 'prompts-final/prompts-previews/Portrait/050-elderly-woman-knitting-farmhouse-porch.png' },
  { title: 'Caucasian European man pilot in uniform standing by a small', src: 'prompts-final/prompts-previews/Portrait/051-man-pilot-propeller-plane-grass-airstrip.png' },
  { title: 'Caucasian European woman archaeologist examining a fragment', src: 'prompts-final/prompts-previews/Portrait/052-woman-archaeologist-desert-tent-pottery.png' },
  { title: 'Caucasian European young man and woman ballroom dancers in a', src: 'prompts-final/prompts-previews/Portrait/053-young-couple-ballroom-dancers-practice-hall.png' },
  { title: 'Caucasian European woman tea master performing a traditional', src: 'prompts-final/prompts-previews/Portrait/054-woman-tea-master-traditional-ceremony.png' },
  { title: 'Vertical city with thousands of stacked shipping containers', src: 'prompts-final/prompts-previews/Urban/018-shipping-container-vertical-city-fog.png' },
  { title: 'Tokyo intersection at 3am', src: 'prompts-final/prompts-previews/Urban/019-tokyo-intersection-rainy-3am-neon.png' },
  { title: 'Abandoned subway station turned into underground art gallery', src: 'prompts-final/prompts-previews/Urban/020-abandoned-subway-underground-art-gallery.png' },
  { title: 'Floating market on a river running through a dense Asian cit', src: 'prompts-final/prompts-previews/Urban/021-floating-market-river-asian-city.png' },
  { title: 'Night market in Taipei', src: 'prompts-final/prompts-previews/Urban/022-taipei-night-market-steaming-stalls.png' },
  { title: 'Aerial drone view of a coastal city with turquoise ocean mee', src: 'prompts-final/prompts-previews/Urban/023-coastal-city-turquoise-ocean-beach-boulevard.png' },
  { title: 'Mumbai commuter train at rush hour', src: 'prompts-final/prompts-previews/Urban/024-mumbai-commuter-train-rush-hour-rain.png' },
  { title: 'Rain-soaked Ginza district at night', src: 'prompts-final/prompts-previews/Urban/025-ginza-rain-soaked-night-umbrella-woman.png' },
  { title: 'Ancient Roman aqueduct running through a modern Mediterranea', src: 'prompts-final/prompts-previews/Urban/026-roman-aqueduct-modern-city-cars-cafes.png' },
  { title: 'Shanghai Bund at foggy dawn', src: 'prompts-final/prompts-previews/Urban/027-shanghai-bund-foggy-dawn-jogger.png' },
  { title: 'Street musician playing saxophone under a railway bridge', src: 'prompts-final/prompts-previews/Urban/036-street-saxophonist-railway-bridge-pigeons.png' },
  { title: 'Vertical slum built on a hillside', src: 'prompts-final/prompts-previews/Urban/028-vertical-slum-hillside-improvised-housing.png' },
  { title: 'Chinatown entrance gate at dusk', src: 'prompts-final/prompts-previews/Urban/029-chinatown-gate-dusk-red-lanterns-cards.png' },
  { title: 'Luxury rooftop infinity pool overlooking a modern city skyli', src: 'prompts-final/prompts-previews/Urban/030-rooftop-infinity-pool-city-skyline-dawn.png' },
  { title: 'Parisian cafe terrace in autumn', src: 'prompts-final/prompts-previews/Urban/037-paris-cafe-terrace-autumn-espresso-leaves.png' },
  { title: 'Aerial view of a circular roundabout with cars flowing like', src: 'prompts-final/prompts-previews/Urban/031-circular-roundabout-flowing-cars-autumn-park.png' },
  { title: 'A massive highway interchange at dusk', src: 'prompts-final/prompts-previews/Urban/032-highway-interchange-five-levels-dusk-streaming.png' },
  { title: 'A small zen courtyard garden with a stone lantern', src: 'prompts-final/prompts-previews/Urban/033-zen-courtyard-stone-lantern-moss-bamboo.png' },
  { title: 'A single surviving old bookstore on a corner surrounded by g', src: 'prompts-final/prompts-previews/Urban/034-old-bookstore-corner-surrounded-by-high-rises.png' },
  { title: 'A rainy dawn at a Asian mega-city transit hub', src: 'prompts-final/prompts-previews/Urban/035-transit-hub-thousands-commuters-umbrellas-dawn.png' },
  { title: 'Giant bioluminescent mushroom forest where towering fungi se', src: 'prompts-final/prompts-previews/Fantasy/024-mushroom-forest-house-fairies-snails.png' },
  { title: 'Magical library where books grow like trees from stone floor', src: 'prompts-final/prompts-previews/Fantasy/025-library-books-growing-trees-ink-streams.png' },
  { title: 'Enormous snail carrying a medieval village on its shell', src: 'prompts-final/prompts-previews/Fantasy/026-giant-snail-carrying-medieval-village.png' },
  { title: 'Walking castle migrating across a volcanic lava plain on eno', src: 'prompts-final/prompts-previews/Fantasy/027-walking-castle-migrating-lava-plain-legs.png' },
  { title: 'Origami dragon unfolding itself from a child paper crane', src: 'prompts-final/prompts-previews/Fantasy/028-origami-dragon-unfolding-paper-crane-metamorphosis.png' },
  { title: 'Post-apocalyptic fairy garden blooming from rusted car husks', src: 'prompts-final/prompts-previews/Fantasy/029-fairy-garden-rusted-cars-post-apocalyptic.png' },
  { title: 'Goblin underground bazaar auctioning dragon eggs on velvet p', src: 'prompts-final/prompts-previews/Fantasy/030-goblin-bazaar-dragon-egg-auction-underground.png' },
  { title: 'Living chess board kingdom where pawns have rebelled against', src: 'prompts-final/prompts-previews/Fantasy/031-chess-kingdom-pawns-rebel-marble-battlefield.png' },
  { title: 'A desert city built on the shell of a colossal turtle slowly', src: 'prompts-final/prompts-previews/Fantasy/032-desert-city-giant-turtle-sand-dunes.png' },
  { title: 'A post office for the dead in a twilight realm', src: 'prompts-final/prompts-previews/Fantasy/033-post-office-dead-ghost-letters-skeletal-clerks.png' },
  { title: 'A garden of giant flowers that are actually eyeballs on stem', src: 'prompts-final/prompts-previews/Fantasy/034-garden-eyeball-flowers-watching-viewer.png' },
  { title: 'A cathedral constructed entirely from bones', src: 'prompts-final/prompts-previews/Fantasy/036-bone-cathedral-ribcage-arches-skulls.png' },
  { title: 'A mountain range that is actually a sleeping titan', src: 'prompts-final/prompts-previews/Fantasy/037-mountain-range-sleeping-titan-towns-ridge.png' },
  { title: 'A carnival of extinct animals', src: 'prompts-final/prompts-previews/Fantasy/038-carnival-extinct-animals-carousel-mammoth.png' },
  { title: 'A surreal still life of a chess set where every piece is mad', src: 'prompts-final/prompts-previews/Still Life/024-chess-set-food-pieces-bread-cheese-wine.png' },
  { title: 'A surreal still life of an antique vanity table where cosmet', src: 'prompts-final/prompts-previews/Still Life/025-vanity-table-natural-elements-moss-berries-dew.png' },
  { title: 'A minimalist still life of a desk where every object is made', src: 'prompts-final/prompts-previews/Still Life/026-desk-every-object-glass-book-pen-candle.png' },
  { title: 'A still life of items from a time traveler\'s pocket arranged', src: 'prompts-final/prompts-previews/Still Life/027-time-traveler-pocket-contents-coin-key-watch-phone.png' },
  { title: 'A surreal still life of a breakfast table where all food has', src: 'prompts-final/prompts-previews/Still Life/028-breakfast-precious-stones-amber-pearl-obsidian.png' },
  { title: 'A whimsical still life of three porcelain teacups each conta', src: 'prompts-final/prompts-previews/Still Life/029-teacups-tiny-weather-systems-thunderstorm-fog-rainbow.png' },
  { title: 'A surreal still life of perfume bottles where each glass bot', src: 'prompts-final/prompts-previews/Still Life/030-perfume-bottles-captured-landscapes-desert-forest-ocean.png' },
  { title: 'A still life of objects half-submerged in honey on a rustic', src: 'prompts-final/prompts-previews/Still Life/031-objects-submerged-honey-golden-refraction-watch-key-rose.png' },
  { title: 'A surreal still life of keys made of impossible materials ar', src: 'prompts-final/prompts-previews/Still Life/032-keys-impossible-materials-smoke-ice-light-shadow.png' },
  { title: 'A nostalgic still life of vintage photograph frames where ph', src: 'prompts-final/prompts-previews/Still Life/033-photo-frames-pressed-flowers-matching-silhouettes.png' },
  { title: 'A surreal still life of an alchemist\'s wooden shelf with apo', src: 'prompts-final/prompts-previews/Still Life/034-alchemist-shelf-impossible-substances-moonlight-sunset.png' },
  { title: 'A still life of timekeeping devices from different eras each', src: 'prompts-final/prompts-previews/Still Life/035-timekeeping-devices-different-eras-sundial-hourglass-atomic.png' },
  { title: 'A surreal still life of a butterfly collection where some sp', src: 'prompts-final/prompts-previews/Still Life/036-butterfly-collection-half-alive-flying-color-trails.png' },
  { title: 'A futuristic still life of a vanity table from the year 3000', src: 'prompts-final/prompts-previews/Still Life/037-future-vanity-table-holographic-beauty-tools-chrome.png' },
  { title: 'A surreal still life of a magician\'s top hat tipped on its s', src: 'prompts-final/prompts-previews/Still Life/038-magician-top-hat-spilling-stars-water-cards-lightning.png' },
  { title: 'A surreal still life of antique compasses on a brass table', src: 'prompts-final/prompts-previews/Still Life/039-compasses-pointing-impossible-directions-spinning-upward.png' },
  { title: 'A surreal still life of a picnic interrupted by nature', src: 'prompts-final/prompts-previews/Still Life/040-picnic-interrupted-nature-ants-crystal-vines-butterflies.png' },
  { title: 'A fantasy still life of a potion maker\'s workbench with vial', src: 'prompts-final/prompts-previews/Still Life/041-potion-workbench-vials-colored-liquids-smoke-glitter-fish.png' },
  { title: 'A surreal still life of vintage cameras where the lenses hav', src: 'prompts-final/prompts-previews/Still Life/042-vintage-cameras-lenses-eyes-reflecting-scenes.png' },
  { title: 'A still life of masks hanging on a weathered stone wall', src: 'prompts-final/prompts-previews/Still Life/043-masks-natural-materials-bark-ice-sand-moss-ash.png' },
  { title: 'A still life of an apothecary\'s table with dried herbs and m', src: 'prompts-final/prompts-previews/Still Life/044-apothecary-herbs-color-gradient-purple-gold-arrangement.png' },
  { title: 'A surreal still life of modern objects trapped in a massive', src: 'prompts-final/prompts-previews/Still Life/045-modern-objects-trapped-amber-smartphone-key-coin-watch.png' },
  { title: 'A surreal forest where every tree is made of translucent cry', src: 'prompts-final/prompts-previews/Nature/045-crystal-forest-trees-light-refracting-prism.png' },
  { title: 'A surreal seascape where ocean waves are frozen in mid-motio', src: 'prompts-final/prompts-previews/Nature/046-ocean-waves-frozen-mid-motion-sculpture.png' },
  { title: 'A desert where the sand dunes are made of crushed gemstones', src: 'prompts-final/prompts-previews/Nature/047-desert-dunes-crushed-gemstones-rainbow-colors.png' },
  { title: 'A mountain range at night where the rocky peaks glow with na', src: 'prompts-final/prompts-previews/Nature/048-mountain-peaks-bioluminescence-glowing-night.png' },
  { title: 'A wildflower meadow where flowers bloom in impossible perfec', src: 'prompts-final/prompts-previews/Nature/049-meadow-flowers-geometric-patterns-spirals.png' },
  { title: 'A surreal landscape where a river flows upward defying gravi', src: 'prompts-final/prompts-previews/Nature/050-river-flowing-upward-defying-gravity-sky.png' },
  { title: 'A massive glacier that is completely transparent like glass', src: 'prompts-final/prompts-previews/Nature/051-glacier-transparent-glass-ancient-landscape-inside.png' },
  { title: 'A dramatic canyon where the rock walls are made of layered a', src: 'prompts-final/prompts-previews/Nature/052-canyon-walls-layered-amethyst-agate-crystal.png' },
  { title: 'A mystical cloud forest where clouds have taken root in the', src: 'prompts-final/prompts-previews/Nature/053-cloud-forest-clouds-rooted-trees-growing-cotton.png' },
  { title: 'A volcanic landscape where lava has cooled into glossy black', src: 'prompts-final/prompts-previews/Nature/054-volcanic-lava-cooled-obsidian-animal-sculptures.png' },
  { title: 'An arctic tundra where the permafrost has crystallized into', src: 'prompts-final/prompts-previews/Nature/055-tundra-permafrost-crystallized-diamond-formations.png' },
  { title: 'A mangrove swamp at twilight where the underwater roots glow', src: 'prompts-final/prompts-previews/Nature/056-mangrove-swamp-roots-bioluminescent-blue-glow.png' },
  { title: 'A majestic waterfall captured in extreme slow motion', src: 'prompts-final/prompts-previews/Nature/057-waterfall-slow-motion-droplets-jewels-suspended.png' },
  { title: 'A towering bamboo forest where each stalk is a different col', src: 'prompts-final/prompts-previews/Nature/058-bamboo-forest-rainbow-colors-each-stalk-different.png' },
  { title: 'A geothermal area where mineral hot springs form a perfect c', src: 'prompts-final/prompts-previews/Nature/059-geothermal-mineral-pools-perfect-color-wheel.png' },
  { title: 'A magical forest where the leaves change color in response t', src: 'prompts-final/prompts-previews/Nature/060-forest-leaves-change-color-sound-visual-symphony.png' },
  { title: 'A black volcanic sand beach at night where the crashing wave', src: 'prompts-final/prompts-previews/Nature/061-black-sand-beach-bioluminescent-plankton-glowing-waves.png' },
  { title: 'An African savanna where the grass is made of thin copper wi', src: 'prompts-final/prompts-previews/Nature/062-savanna-copper-wire-grass-hums-wind.png' },
  { title: 'A vast field where giant translucent crystals grow from the', src: 'prompts-final/prompts-previews/Nature/063-field-giant-crystals-growing-like-wheat-glowing.png' },
  { title: 'Abstract visualization of sound waves as ripples in a dark l', src: 'prompts-final/prompts-previews/Abstract/042-sound-waves-visible-ripples-liquid-color-frequencies.png' },
  { title: 'Abstract art of a black hole made of swirling liquid ink pul', src: 'prompts-final/prompts-previews/Abstract/043-black-hole-liquid-ink-pulling-colorful-light-streams.png' },
  { title: 'Abstract visualization of magnetic field lines as glowing go', src: 'prompts-final/prompts-previews/Abstract/044-magnetic-field-lines-glowing-golden-threads-sculpture.png' },
  { title: 'Abstract concept of time visualized as layers of transparent', src: 'prompts-final/prompts-previews/Abstract/045-time-visualized-transparent-film-layers-amber-gradient.png' },
  { title: 'Abstract topographic landscape mapping emotions', src: 'prompts-final/prompts-previews/Abstract/046-emotions-topographic-landscape-red-peaks-blue-canyons.png' },
  { title: 'Abstract visualization of a symphony as flowing ribbons of c', src: 'prompts-final/prompts-previews/Abstract/047-symphony-flowing-ribbons-color-each-instrument-hue.png' },
  { title: 'Abstract art of mathematical equations rendered as 3D sculpt', src: 'prompts-final/prompts-previews/Abstract/048-mathematical-equations-3d-sculptures-golden-ratio-fibonacci.png' },
  { title: 'Abstract visualization of gravity waves as distortions in a', src: 'prompts-final/prompts-previews/Abstract/049-gravity-waves-distortions-grid-light-points-bending.png' },
  { title: 'Abstract art of memory fragments as floating glass shards', src: 'prompts-final/prompts-previews/Abstract/050-memory-fragments-glass-shards-spiral-galaxy-forgotten.png' },
  { title: 'Abstract visualization of heat as visible color waves rising', src: 'prompts-final/prompts-previews/Abstract/051-heat-visible-color-waves-rising-coffee-thermal-volcano.png' },
  { title: 'Abstract visualization of quantum probability as semi-transp', src: 'prompts-final/prompts-previews/Abstract/052-quantum-probability-clouds-translucent-spheres-overlapping.png' },
  { title: 'Abstract art of words from different languages dissolving in', src: 'prompts-final/prompts-previews/Abstract/053-words-dissolving-abstract-shapes-meaning-energy.png' },
  { title: 'Abstract dreamscape where thoughts are physical objects floa', src: 'prompts-final/prompts-previews/Abstract/054-dreamscape-thoughts-physical-objects-zero-gravity-threads.png' },
  { title: 'Abstract visualization of echo as visible sound rings bounci', src: 'prompts-final/prompts-previews/Abstract/055-echo-visible-sound-rings-bouncing-canyon-mirrors.png' },
  { title: 'Abstract art of colors bleeding through wet paper', src: 'prompts-final/prompts-previews/Abstract/056-colors-bleeding-wet-paper-emotional-landscape.png' },
  { title: 'Abstract maze made entirely of light where dead ends dissolv', src: 'prompts-final/prompts-previews/Abstract/057-maze-light-dead-ends-darkness-paths-glow-choices.png' },
  { title: 'Saguaro cacti in the Arizona desert transformed into towerin', src: 'prompts-final/prompts-previews/Nature/064-cactus-desert-turned-ice-sculptures-frozen-oasis.png' },
  { title: 'A wooden grandfather clock melting into a pool of golden hon', src: 'prompts-final/prompts-previews/Still Life/046-grandfather-clock-melting-into-golden-honey-pool.png' },
  { title: 'An ancient leather-bound book on a wooden desk with ivy vine', src: 'prompts-final/prompts-previews/Still Life/047-old-book-growing-ivy-vines-sprouting-flowers-pages.png' },
  { title: 'A glowing feather quill writing on parchment', src: 'prompts-final/prompts-previews/Fantasy/039-quill-pen-writing-words-transforming-into-flying-birds.png' },
  { title: 'Abstract visualization of an echo as a physical sound wave s', src: 'prompts-final/prompts-previews/Abstract/058-echo-visualized-sound-wave-sculpture-resonating-canyon.png' },
  { title: 'Abstract art of computer code woven into a digital tapestry', src: 'prompts-final/prompts-previews/Abstract/059-code-weaving-digital-tapestry-binary-threads-pattern.png' },
];
